In [1]:
!pip install -q pypdf sentence-transformers faiss-cpu

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 407.8/407.8 kB 6.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.8/18.8 MB 43.2 MB/s eta 0:00:00

In [2]:
from pypdf import PdfReader
from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

In [3]:
!pip install -q datasets

In [4]:
from datasets import load_dataset

dataset = load_dataset("iam-tsr/ragmix")

print(dataset)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/3.68k [00:00<?, ?B/s]

data/test-00000-of-00001-43be72dace544f4(…): reconstructing file:   0%|          |  0.00B / 1.18MB

data/test-00000-of-00001-43be72dace544f4(…): downloading bytes:           |  0.00B

Generating test split:   0%|          | 0/100 [00:00<?, ? examples/s]

DatasetDict({
    test: Dataset({
        features: ['category', 'context', 'question', 'answer'],
        num_rows: 100
    })
})

In [5]:
print(dataset)

DatasetDict({
    test: Dataset({
        features: ['category', 'context', 'question', 'answer'],
        num_rows: 100
    })
})

In [6]:
print(dataset[list(dataset.keys())[0]][0])

{'category': 'agriculture', 'context': '%IMAGE_DESCRIPTION: University of California Davis - Viticulture & Enology%\n\n%IMAGE_DESCRIPTION: TRELLIS ALLIANCE U.C.DAVIS%\n\n## Title: **“Research on 2-methoxy-3-isobutylpyrazine in grapes and wines”** \n\nBy:  Dominique Roujou De Boubee \n\nSchool of Enology, University of Bordeaux II. Unpublished. \n\nPyrazines are nitrogen-containing heterocyclic compounds that can be classified in 3 categories, depending on their origin: 1) those formed by heat treatment, 2) those formed by microorganisms, and 3) those present naturally in plants. We are particularly interested in the latter category, and within it, in 2-methoxy-3isobutylpyrazine (IBMP), the main compound responsible for green bell pepper aroma in wines. \n\n## _**Enological implications:**_ \n\n• It has already been established that IBMP’s detection threshold in water is 2 ng/l. The researchers went on to determine the equivalent threshold in red wine. Because the answer varied with the type of wine, they had to be more specific. Using a trained panel, they found that the IBMP detection threshold in Bordeauxtype red wine is 15 ng/l \n\n• High concentrations of IBMP are associated with a lack of ripeness and winemakers often associate this bell pepper character with low anthocyanins, or weak color, and mediocre tannin quality. Therefore the paper proceeds to explore actual production operations or winemaking conditions that would minimize IBMP concentration. \n\n• The researchers looked at the IBMP concentration in different SB press fractions. Similar concentrations were found in the free run and in the 1.5 or 2 bar fraction (pneumatic pressing of whole clusters), so the compound is easily extractable. \n\n• They looked at the effect of white must settling on IBMP. After settling of the SB, the compound was half the original amount. So this step is important to reduce greenness. They thought what was going on was that IBMP interacted with grape solids and was carried down with them. \n\n• The researchers also looked at different pump-over regimes and different lengths of skin contact. They concluded that the IBMP was not significantly affected by these extraction techniques. So more punchdowns, or extended macerations will not increase IBMP concentration. \n\n• Thermovinification, however, was the only winemaking technique that actually decreased IBMP concentrations in their trials. This is believed to be due to methoxypyrazine’s volatilization at 50[o] C. So this is an interesting alternative when grapes are believed to be unripe, or moldy. Heating the must to 50[o] C actually increased the perceived fruity character in these wines and decreased the IBMP concentration. \n\n- They looked at how IBMP evolves in a bottle for CS and SB. After 3 years of aging they found no \n\n- change. One should not count on time to diminish a methoxypyrazine, or bell pepper, defect. \n\n## _**Viticultural implications:**_ \n\n• It seems IBMP is directly related to vegetative growth. Vigorous vines that stopped growing relatively late in the season produced higher IBMP concentrations. Also, higher irrigated vines produced more IBMP compared to normal or dry-farmed vines, as has been previously reported. \n\n- IBMP synthesis takes place between fruit set and 2-3 weeks prior to veraison. In the berry, it is \n\n- synthesized mainly in the skins, some in the seeds, and very little in the pulp. \n\n• The authors found that leaves had the highest concentrations of IBMP. Furthermore, using radioactive IBMP they were able to see that the compound was transported by the phloem from the leaves to the berries. The compound is also believed to be synthesized in the berries, so its presence in the berry is likely due to both transport from leaves and synthesis _in situ._ \n\n• From veraison to ripeness, the cycle changes and IBMP begins to break down. It actually breaks down faster than it is synthesized. And daylight accelerates this degradation. The authors found that the degradation products have no bell pepper character. By exposing grapes to sunlight, leaf removal helps decrease IBMP. \n\n• After harvest, IBMP still remains high only in the stems. That explains why destemming decreases bell pepper character and improves quality. \n\n• In a detailed experiment, the researchers compared IBMP levels of summer-pruned vines (basal leaves and laterals removed) which had also been cluster thinned, against a control. The former vines had much lower IBMP, as well as higher phenols and more alcohol, than the control. In general, they recommend lateral and leaf removal as a means to produce high-quality grapes. The benefits they found include: improved crop healthiness, better aeration, and removal of "sinks", which in turn promoted better photosynthate distribution and grape ripeness. \n\n• When leaves are removed early, grape sugar is higher, berries are smaller, and IBMP decreases. A later leaf removal will still facilitate earlier sugar ripeness, but it doesn’t decrease IBMP concentrations in the fruit. Thus, the researchers recommend that leaf removal be performed early, between set and berry touch, or green berry size. \n\n• To conclude, the author notes "it is probable that an early diagnosis (July) of the grape IBMP would help determine whether lateral removal or leaf removal are needed in a vineyard block". This would help reduce costs in some instances and still achieve high quality grapes. \n\n**In conclusion,** the researchers determined that, in this study, there was only one way to effectively decrease IBMP concentrations once the affected red grapes have reached the winery: **thermovinification** . There are obvious pros and cons with heating a red must, though, and the winemaker would have to make that judgment. As for white grapes, **must cold-settling** was the only way to reduce IBMP, since this compound tended to sediment along with the grape solids. \n\nIt seems that the most effective and efficient way to mitigate IBMP concentration in grape berries is by vineyard management practices. If it isn’t managed in the vineyard, it will most certainly become a winemaking problem with few alternatives besides blending. \n\n_Author: Bibiana Guerra, Editor: Kay Bogart. This summary series funded by_ J. Lohr Vineyards & Wines _._ \n\n', 'question': 'What IBMP detection threshold did researchers find in Bordeaux-type red wine, and which single winery technique effectively reduced IBMP in red musts in their trials?', 'answer': 'Using a trained panel, they found the IBMP detection threshold in Bordeaux-type red wine is 15 ng/l. Thermovinification was the only winemaking technique that decreased IBMP concentrations in their red-wine trials, attributed to methoxypyrazine volatilization at 50°C.'}

In [7]:
import pandas as pd

df = pd.read_parquet(
    "/content/test-00000-of-00001-43be72dace544f4fba6c2a484a3a0032.parquet"
)

df.head()

,category,context,question,answer
0,agriculture,%IMAGE_DESCRIPTION: University of California D...,What IBMP detection threshold did researchers ...,"Using a trained panel, they found the IBMP det..."
1,education,||||**ATM S 2021-2022 Teaching Schedule**|**AT...,Who is scheduled to teach ATM S 101 Weather in...,"In Autumn 2021, 101 Weather is taught by Mass;..."
2,education,## **Do Nevadans Prioritize Early Childhood Ed...,In the 2015 Nevada early childhood education o...,96.6% agreed that early childhood education ha...
3,education,%IMAGE_DESCRIPTION: Ofsted%\n\n## **Fareacres ...,What overall judgements did Ofsted make for Fa...,The quality and standards of care were judged ...
4,education,## **LEARNING SIMULATION THROUGH TEAM PROJECTS...,In the University of Michigan Industrial and O...,"The authors structure projects around Johnson,..."

In [8]:
df.shape

(100, 4)

In [9]:
df.head()

,category,context,question,answer
0,agriculture,%IMAGE_DESCRIPTION: University of California D...,What IBMP detection threshold did researchers ...,"Using a trained panel, they found the IBMP det..."
1,education,||||**ATM S 2021-2022 Teaching Schedule**|**AT...,Who is scheduled to teach ATM S 101 Weather in...,"In Autumn 2021, 101 Weather is taught by Mass;..."
2,education,## **Do Nevadans Prioritize Early Childhood Ed...,In the 2015 Nevada early childhood education o...,96.6% agreed that early childhood education ha...
3,education,%IMAGE_DESCRIPTION: Ofsted%\n\n## **Fareacres ...,What overall judgements did Ofsted make for Fa...,The quality and standards of care were judged ...
4,education,## **LEARNING SIMULATION THROUGH TEAM PROJECTS...,In the University of Michigan Industrial and O...,"The authors structure projects around Johnson,..."

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   category  100 non-null    object
 1   context   100 non-null    object
 2   question  100 non-null    object
 3   answer    100 non-null    object
dtypes: object(4)
memory usage: 3.3+ KB

In [11]:
print(df.columns)
print(df.dtypes)

Index(['category', 'context', 'question', 'answer'], dtype='object')
category    object
context     object
question    object
answer      object
dtype: object

In [12]:
df.head(10)

,category,context,question,answer
0,agriculture,%IMAGE_DESCRIPTION: University of California D...,What IBMP detection threshold did researchers ...,"Using a trained panel, they found the IBMP det..."
1,education,||||**ATM S 2021-2022 Teaching Schedule**|**AT...,Who is scheduled to teach ATM S 101 Weather in...,"In Autumn 2021, 101 Weather is taught by Mass;..."
2,education,## **Do Nevadans Prioritize Early Childhood Ed...,In the 2015 Nevada early childhood education o...,96.6% agreed that early childhood education ha...
3,education,%IMAGE_DESCRIPTION: Ofsted%\n\n## **Fareacres ...,What overall judgements did Ofsted make for Fa...,The quality and standards of care were judged ...
4,education,## **LEARNING SIMULATION THROUGH TEAM PROJECTS...,In the University of Michigan Industrial and O...,"The authors structure projects around Johnson,..."
5,education,\n\n## **2021 -2022 School Year** \n\n## **Mar...,What are the morning pick-up and regular drop-...,Pick-up is at 7:10 a.m. and regular drop-off i...
6,education,# **AN ACTION TO PROMOTE GENDER DIVERSITY IN S...,How many high school girls attended the “Scien...,"In 2017, 311 girls from 10 high schools in the..."
7,education,## When the American Dream Stops: New Challeng...,How many students participated in the Autonomo...,The exploratory study included 26 voluntary pa...
8,employment,## **Island Enterprises Retail LLC Job Descrip...,What is the hourly pay for the Island Enterpri...,The hourly rate is $13.69. The position opens ...
9,employment,%IMAGE_DESCRIPTION: Chicken Farmers of Ontario...,According to Chicken Farmers of Ontario’s role...,"If required, the Chair only votes to break a t..."

In [13]:
df.isnull().sum()

category    0
context     0
question    0
answer      0
dtype: int64

In [14]:
import re

def clean_text(text):
    return re.sub(r"%IMAGE_DESCRIPTION:.*?%", "", text)

def chunk_text(text, chunk_size=500, overlap=50):
    words = text.split()
    chunks = []
    start = 0
    while start < len(words):
        end = start + chunk_size
        chunks.append(" ".join(words[start:end]))
        start += chunk_size - overlap
    return chunks

unique_contexts = df["context"].dropna().unique().tolist()
unique_contexts = [clean_text(t) for t in unique_contexts]

documents = []
for text in unique_contexts:
    documents.extend(chunk_text(text, chunk_size=500, overlap=50))

print(f"{len(df)} rows -> {len(unique_contexts)} unique docs -> {len(documents)} chunks")

100 rows -> 100 unique docs -> 790 chunks

In [15]:
!pip install -q sentence-transformers faiss-cpu

In [16]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

print("Embedding model loaded!")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Embedding model loaded!

In [17]:
embeddings = model.encode(documents)

print("Embeddings created!")
print("Shape:", embeddings.shape)

Embeddings created!
Shape: (790, 384)

In [18]:
!pip install faiss-cpu

Requirement already satisfied: faiss-cpu in /usr/local/lib/python3.13/dist-packages (1.15.1)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.13/dist-packages (from faiss-cpu) (2.1.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from faiss-cpu) (26.3)

In [19]:
import faiss
import numpy as np

# Convert embeddings to float32
embeddings = np.array(embeddings).astype("float32")

# Create FAISS index
index = faiss.IndexFlatL2(embeddings.shape[1])

# Add embeddings to the index
index.add(embeddings)

print("FAISS index created successfully!")
print("Number of vectors:", index.ntotal)

FAISS index created successfully!
Number of vectors: 790

In [20]:
query = "What is machine learning?"

# Convert query into embedding
query_embedding = model.encode([query])

# Convert to float32
query_embedding = np.array(query_embedding).astype("float32")

# Search for top 3 similar documents
distances, indices = index.search(query_embedding, 3)

print("Top 3 relevant documents:\n")

for i, idx in enumerate(indices[0]):
    print(f"Result {i+1}:")
    print(documents[idx])
    print("Distance:", distances[0][i])
    print("-" * 50)

Top 3 relevant documents:

Result 1:
portation – is meant to provide benefits, but may also lead to new problems both for the individual and for society as a whole. Health IT seems to be no exception here. Consequently, many health informatics associations have adopted codes of professional and ethical conduct. For example, AMIA’s “Code of Professional and Ethical Conduct” states that “members … should be mindful and respectful of the social or public-health implications of their work” and “members … should recognize technical and ethical limitations” [7]. Modern health care is not thinkable without health IT [8], especially when taking into account the exploding amount of health information generated by more and more elaborate diagnostic and therapeutic technology, the growing need for communication and cooperation between different health care professional groups and health care institutions when treating multi-morbid patients in an aging population, and the challenge of providing highquality care in times of economic crisis. The obligation for health informatics is to respond to these challenges and to provide efficient and effective health IT solutions, with as much benefit and as little negative side effects as possible. To achieve this, health informatics as a discipline must be able to learn, both from its successes as well as from its failures. Learning is an individual process, but can also be a process within academic disciplines as a whole. Learning within health informatics includes collecting experiences, best practices, anecdotes, evaluation reports, and scientific study results. All this forms a (virtual) professional knowledge base that can help to generate scientifically valid evidence that helps to advance the field of health informatics. However, many recent reviews on the impact of health IT have found that this available (published) evidence is astonishingly limited for many types of health IT, for manifold reasons. Thus, health informatics seems not as evidence-based as it should be. Missing evidence does not mean that health IT is without value, but it means that decisions on health IT development and implementation are based on “what we think makes sense, what we can afford, what vendors recommend…” [9] – and not on scientific evidence. The objective of this paper is to present the idea and the challenges of evidencebased health informatics. First, the idea of evidence-based medicine is discussed, and the vision and history of evidence-based health informatics is presented. The generation of evidence by evaluation is then put forward in light of the life cycle of health IT. Then, achievements and challenges on the path towards evidence-based health informatics are discussed, and need for action is identified. This paper is an extended version of an invited keynote lecture given by the author at the Medical Informatics Europe conference (MIE 2014) in Istanbul on September 1, 2014. ## **2. The Vision of Evidencebased Health Informatics** To understand evidence-based health informatics, it is helpful to have a look at the history and motivation of evidence-based medicine. The origins of evidence-based medicine can be traced back to the 19th century [10]. Nowadays, the most influential definition of evidence-based medicine
Distance: 1.4470613
--------------------------------------------------
Result 2:
systematic reviews in health informatics has been increasing since 2005 [25]. The number of published health IT evaluation studies is more difficult to spot. A detailed analysis on 1,035 health IT evaluation studies published between 1982 and 2002 showed that an increasing number of evaluation studies had been published since 1995, with around 120 published each year in 2001 and 2002 [15]. The term “evidence-based health informatics” was first used at McMaster University in the mid-1990s [26]. The term was used here to name information resources to support evidence-based medicine, which is not in line with the definition of evidence-based health informatics in this paper. One of the first persons to clearly formulate the need for an evidence base to health informatics was Michael Rigby who wrote in 2001: “Information systems … are no different from any other health system in needing to be evidence-based.” [27]. The already cited definition of evidence-based health informatics was published in 2007 [11]. In 2010, IMIA included the topic “evaluation and evidence-based health in- formatics” in its revised recommendations on health informatics education [28]. In 2013, the IMIA Yearbook of Medical Informatics 2013 chose as it annual topic “evidence-based health informatics” [29] and so made this term recognized worldwide. ## **3. Evidence and Life Cycle of Health IT** Evidence is generated, as discussed before, by systematic research based on formative or summative evaluation studies. Depending on the life cycle of health IT, evaluation studies have to answer different questions and thus focus on different issues and produce different types of evidence. The following list gives a short, and clearly incomplete, list of possible evaluation questions and methods that can be applied to generate related evidence: **•** Development phase: What are the user needs? (needs assessment); Is the soft- | Year | # Systematic reviews (medical informatics [as minor mesh term]) | # Systematic reviews (medical informatics [as major mesh term]) | # Systematic reviews in health informatics | # medical informatics papers | | --- | --- | --- | --- | --- | | 1967 | 0 | 0 | 0 | ~0 | | 1968 | ~0.5 | ~0.5 | 0 | ~500 | | 1969 | ~0.5 | ~0.5 | 0 | ~1000 | | 1970 | ~1 | ~1 | 0 | ~1500 | | 1971 | ~1 | ~1 | 0 | ~2000 | | 1972 | ~1 | ~1 | 0 | ~2500 | | 1973 | ~2 | ~1 | 0 | ~3000 | | 1974 | ~2 | ~1 | 0 | ~3500 | | 1975 | ~2 | ~2 | 0 | ~4000 | | 1976 | ~2 | ~2 | 0 | ~4500 | | 1977 | ~3 | ~2 | 0 | ~5000 | | 1978 | ~3 | ~2 | 0 | ~5500 | | 1979 | ~4 | ~3 | 0 | ~6000 | | 1980 | ~4 | ~3 | 0 | ~6500 | | 1981 | ~5 | ~3
Distance: 1.5161448
--------------------------------------------------
Result 3:
## A Longitudinal Study of Google Privacy Policies Alan Peslak arp14@psu.edu Information Sciences and Technology Penn State University Dunmore, PA 18512 USA Lisa Kovalchick kovalchick@calu.edu Mathematics, Computer Science and Information Systems California University of Pennsylvania California, PA 15419 USA Mauri Conforti maconforti1@geisinger.edu Geisinger Health System Scranton, PA 18508 USA ## **Abstract** Google has come a long way since its founding by Larry Page and Sergey Brin in 1998. From a Stanford University PhD research project, to the world leader in Internet search engines, Google has changed and grown exponentially. “Google it” has become a household phrase. Its core search engine product has approximately 246 million unique US visitors per month. Its market share in the US, in search engines, is estimated at 63%. In addition, it has expanded product offerings to include the ubiquitous YouTube Internet video platform, Google Home smart speakers, Chrome web browser, Android operating system, Pixel phones, and Gmail, among other products. As a result, Google collects a tremendous amount of data from its users. With its growing popularity and the growing user privacy concerns, following the recent data breaches, Google is constantly updating its privacy policy. Our manuscript examines Google privacy policies from 2000 to present day. The policies were collected via the Internet Archive and represent a selected day from each available year from 2000 through 2018. A comprehensive qualitative, linguistics and sentiment analysis on these policies was performed. Our review finds significant similarities and differences in Google privacy policies over the years. Overall, Google privacy policies have become increasingly wordy and legalistic, but also more positive in sentiment and more personal in approach. Though the grade level of the documents has declined slightly they remain at a 12[th] grade level. Implications and opportunities for further research are presented. **Keywords:** Sentiment analysis, Google, Linguistic analysis, LIWC ## **1. INTRODUCTION** Through the use of the web, people are now able to easily search for any type of information by typing a few keywords into an Internet search engine and the information they are seeking is at their fingertips. Google is the most popular search engine in the US. According to Statista (2019), in the month of December 2018, there were 246 million unique visitors to the search engine home page. This is startling considering there were 328 million people in the US in December 2018 (Census, 2019). Google also has an estimated 63% market share in the United States for Internet searches. In the global market, their market share is even higher, estimated at 90%. (Statista, 2019). “Seventyfour percent of U.S. adults currently say they use Google in a typical week” (Jones, 2018). The original Google product was the online search engine, but its product lines have expanded greatly over the years and they all share their data across platforms. Their products now include YouTube, which has been accessed by 68% of the population. They have developed online advertising, and sponsored searches. (Statista, 2019). As reported by Kelly (2018), Google “is the world's largest digital advertising
Distance: 1.5218978
--------------------------------------------------

In [21]:
# Get the top 3 retrieved documents
retrieved_docs = [documents[idx] for idx in indices[0]]

# Combine them into one context
context = "\n\n".join(retrieved_docs)

print("Retrieved Context:\n")
print(context)

Retrieved Context:

portation – is meant to provide benefits, but may also lead to new problems both for the individual and for society as a whole. Health IT seems to be no exception here. Consequently, many health informatics associations have adopted codes of professional and ethical conduct. For example, AMIA’s “Code of Professional and Ethical Conduct” states that “members … should be mindful and respectful of the social or public-health implications of their work” and “members … should recognize technical and ethical limitations” [7]. Modern health care is not thinkable without health IT [8], especially when taking into account the exploding amount of health information generated by more and more elaborate diagnostic and therapeutic technology, the growing need for communication and cooperation between different health care professional groups and health care institutions when treating multi-morbid patients in an aging population, and the challenge of providing highquality care in times of economic crisis. The obligation for health informatics is to respond to these challenges and to provide efficient and effective health IT solutions, with as much benefit and as little negative side effects as possible. To achieve this, health informatics as a discipline must be able to learn, both from its successes as well as from its failures. Learning is an individual process, but can also be a process within academic disciplines as a whole. Learning within health informatics includes collecting experiences, best practices, anecdotes, evaluation reports, and scientific study results. All this forms a (virtual) professional knowledge base that can help to generate scientifically valid evidence that helps to advance the field of health informatics. However, many recent reviews on the impact of health IT have found that this available (published) evidence is astonishingly limited for many types of health IT, for manifold reasons. Thus, health informatics seems not as evidence-based as it should be. Missing evidence does not mean that health IT is without value, but it means that decisions on health IT development and implementation are based on “what we think makes sense, what we can afford, what vendors recommend…” [9] – and not on scientific evidence. The objective of this paper is to present the idea and the challenges of evidencebased health informatics. First, the idea of evidence-based medicine is discussed, and the vision and history of evidence-based health informatics is presented. The generation of evidence by evaluation is then put forward in light of the life cycle of health IT. Then, achievements and challenges on the path towards evidence-based health informatics are discussed, and need for action is identified. This paper is an extended version of an invited keynote lecture given by the author at the Medical Informatics Europe conference (MIE 2014) in Istanbul on September 1, 2014. ## **2. The Vision of Evidencebased Health Informatics** To understand evidence-based health informatics, it is helpful to have a look at the history and motivation of evidence-based medicine. The origins of evidence-based medicine can be traced back to the 19th century [10]. Nowadays, the most influential definition of evidence-based medicine

systematic reviews in health informatics has been increasing since 2005 [25]. The number of published health IT evaluation studies is more difficult to spot. A detailed analysis on 1,035 health IT evaluation studies published between 1982 and 2002 showed that an increasing number of evaluation studies had been published since 1995, with around 120 published each year in 2001 and 2002 [15]. The term “evidence-based health informatics” was first used at McMaster University in the mid-1990s [26]. The term was used here to name information resources to support evidence-based medicine, which is not in line with the definition of evidence-based health informatics in this paper. One of the first persons to clearly formulate the need for an evidence base to health informatics was Michael Rigby who wrote in 2001: “Information systems … are no different from any other health system in needing to be evidence-based.” [27]. The already cited definition of evidence-based health informatics was published in 2007 [11]. In 2010, IMIA included the topic “evaluation and evidence-based health in- formatics” in its revised recommendations on health informatics education [28]. In 2013, the IMIA Yearbook of Medical Informatics 2013 chose as it annual topic “evidence-based health informatics” [29] and so made this term recognized worldwide. ## **3. Evidence and Life Cycle of Health IT** Evidence is generated, as discussed before, by systematic research based on formative or summative evaluation studies. Depending on the life cycle of health IT, evaluation studies have to answer different questions and thus focus on different issues and produce different types of evidence. The following list gives a short, and clearly incomplete, list of possible evaluation questions and methods that can be applied to generate related evidence: **•** Development phase: What are the user needs? (needs assessment); Is the soft- | Year | # Systematic reviews (medical informatics [as minor mesh term]) | # Systematic reviews (medical informatics [as major mesh term]) | # Systematic reviews in health informatics | # medical informatics papers | | --- | --- | --- | --- | --- | | 1967 | 0 | 0 | 0 | ~0 | | 1968 | ~0.5 | ~0.5 | 0 | ~500 | | 1969 | ~0.5 | ~0.5 | 0 | ~1000 | | 1970 | ~1 | ~1 | 0 | ~1500 | | 1971 | ~1 | ~1 | 0 | ~2000 | | 1972 | ~1 | ~1 | 0 | ~2500 | | 1973 | ~2 | ~1 | 0 | ~3000 | | 1974 | ~2 | ~1 | 0 | ~3500 | | 1975 | ~2 | ~2 | 0 | ~4000 | | 1976 | ~2 | ~2 | 0 | ~4500 | | 1977 | ~3 | ~2 | 0 | ~5000 | | 1978 | ~3 | ~2 | 0 | ~5500 | | 1979 | ~4 | ~3 | 0 | ~6000 | | 1980 | ~4 | ~3 | 0 | ~6500 | | 1981 | ~5 | ~3

## A Longitudinal Study of Google Privacy Policies Alan Peslak arp14@psu.edu Information Sciences and Technology Penn State University Dunmore, PA 18512 USA Lisa Kovalchick kovalchick@calu.edu Mathematics, Computer Science and Information Systems California University of Pennsylvania California, PA 15419 USA Mauri Conforti maconforti1@geisinger.edu Geisinger Health System Scranton, PA 18508 USA ## **Abstract** Google has come a long way since its founding by Larry Page and Sergey Brin in 1998. From a Stanford University PhD research project, to the world leader in Internet search engines, Google has changed and grown exponentially. “Google it” has become a household phrase. Its core search engine product has approximately 246 million unique US visitors per month. Its market share in the US, in search engines, is estimated at 63%. In addition, it has expanded product offerings to include the ubiquitous YouTube Internet video platform, Google Home smart speakers, Chrome web browser, Android operating system, Pixel phones, and Gmail, among other products. As a result, Google collects a tremendous amount of data from its users. With its growing popularity and the growing user privacy concerns, following the recent data breaches, Google is constantly updating its privacy policy. Our manuscript examines Google privacy policies from 2000 to present day. The policies were collected via the Internet Archive and represent a selected day from each available year from 2000 through 2018. A comprehensive qualitative, linguistics and sentiment analysis on these policies was performed. Our review finds significant similarities and differences in Google privacy policies over the years. Overall, Google privacy policies have become increasingly wordy and legalistic, but also more positive in sentiment and more personal in approach. Though the grade level of the documents has declined slightly they remain at a 12[th] grade level. Implications and opportunities for further research are presented. **Keywords:** Sentiment analysis, Google, Linguistic analysis, LIWC ## **1. INTRODUCTION** Through the use of the web, people are now able to easily search for any type of information by typing a few keywords into an Internet search engine and the information they are seeking is at their fingertips. Google is the most popular search engine in the US. According to Statista (2019), in the month of December 2018, there were 246 million unique visitors to the search engine home page. This is startling considering there were 328 million people in the US in December 2018 (Census, 2019). Google also has an estimated 63% market share in the United States for Internet searches. In the global market, their market share is even higher, estimated at 90%. (Statista, 2019). “Seventyfour percent of U.S. adults currently say they use Google in a typical week” (Jones, 2018). The original Google product was the online search engine, but its product lines have expanded greatly over the years and they all share their data across platforms. Their products now include YouTube, which has been accessed by 68% of the population. They have developed online advertising, and sponsored searches. (Statista, 2019). As reported by Kelly (2018), Google “is the world's largest digital advertising

In [22]:
!pip install -q groq

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.8/143.8 kB 3.7 MB/s eta 0:00:00

In [23]:
from groq import Groq

print("Groq installed successfully!")

Groq installed successfully!

In [24]:
from groq import Groq
from google.colab import userdata

# Assuming 'client' is already initialized from previous cells (zyX6yLBH9OVg)
# If not, uncomment and run:
# api_key = userdata.get("GROQ_API_KEY")
# client = Groq(api_key=api_key)

def summarize_text_groq(text, client):
    # This is a placeholder model name. Please replace with a valid Groq model.
    # For example, "llama3-8b-8192" or "mixtral-8x7b-32768".
    # The previous models 'llama-3.1-8b-instant' and 'openai/gpt-oss-20b' caused errors.
    groq_model_for_summarization = "YOUR_VERIFIED_GROQ_MODEL_FOR_SUMMARIZATION_HERE"

    if groq_model_for_summarization == "YOUR_VERIFIED_GROQ_MODEL_FOR_SUMMARIZATION_HERE":
        print("WARNING: Please replace 'YOUR_VERIFIED_GROQ_MODEL_FOR_SUMMARIZATION_HERE' with a valid Groq model name.")
        return text # Return original text if no valid model is provided

    try:
        response = client.chat.completions.create(
            model=groq_model_for_summarization,
            messages=[
                {
                    "role": "system",
                    "content": "You are a helpful assistant that summarizes text concisely."
                },
                {
                    "role": "user",
                    "content": f"""Summarize the following text:

{text}"""
                }
            ],
            temperature=0.5,
            max_tokens=200 # Limit summary length to control token count
        )
        return response.choices[0].message.content
    except Exception as e:
        print(f"Error during summarization with Groq: {e}")
        return text # Return original text on error

In [25]:
print("Dataset shape:", df.shape)
print("Dataset columns:", df.columns.tolist())
print("Number of documents:", len(documents))
print("Embeddings shape:", embeddings.shape)
print("FAISS vectors:", index.ntotal)
print("Groq client available:", "client" in globals())

Dataset shape: (100, 4)
Dataset columns: ['category', 'context', 'question', 'answer']
Number of documents: 790
Embeddings shape: (790, 384)
FAISS vectors: 790
Groq client available: False

In [26]:
from google.colab import userdata
from groq import Groq

api_key = userdata.get("GROQ_API_KEY")
client = Groq(api_key=api_key)

print("Groq client initialized successfully!")

Groq client initialized successfully!

In [27]:
# Display one question and its expected answer
sample = df.iloc[0]

print("Category:", sample["category"])
print("\nDataset question:", sample["question"])
print("\nExpected answer:", sample["answer"])

Category: agriculture

Dataset question: What IBMP detection threshold did researchers find in Bordeaux-type red wine, and which single winery technique effectively reduced IBMP in red musts in their trials?

Expected answer: Using a trained panel, they found the IBMP detection threshold in Bordeaux-type red wine is 15 ng/l. Thermovinification was the only winemaking technique that decreased IBMP concentrations in their red-wine trials, attributed to methoxypyrazine volatilization at 50°C.

In [28]:
# Get the question from our dataset
question = sample["question"]

# Convert question into an embedding
query_embedding = model.encode([question])
query_embedding = np.array(query_embedding).astype("float32")

# Retrieve the top 3 relevant chunks
distances, indices = index.search(query_embedding, 3)

# Display retrieved documents
print("Question:", question)
print("\nRetrieved documents:\n")

for rank, idx in enumerate(indices[0], start=1):
    print(f"\n--- Document {rank} ---")
    print(documents[idx])
    print("Distance:", distances[0][rank - 1])

Question: What IBMP detection threshold did researchers find in Bordeaux-type red wine, and which single winery technique effectively reduced IBMP in red musts in their trials?

Retrieved documents:


--- Document 1 ---
that the most effective and efficient way to mitigate IBMP concentration in grape berries is by vineyard management practices. If it isn’t managed in the vineyard, it will most certainly become a winemaking problem with few alternatives besides blending. _Author: Bibiana Guerra, Editor: Kay Bogart. This summary series funded by_ J. Lohr Vineyards & Wines _._
Distance: 0.7034141

--- Document 2 ---
## Title: **“Research on 2-methoxy-3-isobutylpyrazine in grapes and wines”** By: Dominique Roujou De Boubee School of Enology, University of Bordeaux II. Unpublished. Pyrazines are nitrogen-containing heterocyclic compounds that can be classified in 3 categories, depending on their origin: 1) those formed by heat treatment, 2) those formed by microorganisms, and 3) those present naturally in plants. We are particularly interested in the latter category, and within it, in 2-methoxy-3isobutylpyrazine (IBMP), the main compound responsible for green bell pepper aroma in wines. ## _**Enological implications:**_ • It has already been established that IBMP’s detection threshold in water is 2 ng/l. The researchers went on to determine the equivalent threshold in red wine. Because the answer varied with the type of wine, they had to be more specific. Using a trained panel, they found that the IBMP detection threshold in Bordeauxtype red wine is 15 ng/l • High concentrations of IBMP are associated with a lack of ripeness and winemakers often associate this bell pepper character with low anthocyanins, or weak color, and mediocre tannin quality. Therefore the paper proceeds to explore actual production operations or winemaking conditions that would minimize IBMP concentration. • The researchers looked at the IBMP concentration in different SB press fractions. Similar concentrations were found in the free run and in the 1.5 or 2 bar fraction (pneumatic pressing of whole clusters), so the compound is easily extractable. • They looked at the effect of white must settling on IBMP. After settling of the SB, the compound was half the original amount. So this step is important to reduce greenness. They thought what was going on was that IBMP interacted with grape solids and was carried down with them. • The researchers also looked at different pump-over regimes and different lengths of skin contact. They concluded that the IBMP was not significantly affected by these extraction techniques. So more punchdowns, or extended macerations will not increase IBMP concentration. • Thermovinification, however, was the only winemaking technique that actually decreased IBMP concentrations in their trials. This is believed to be due to methoxypyrazine’s volatilization at 50[o] C. So this is an interesting alternative when grapes are believed to be unripe, or moldy. Heating the must to 50[o] C actually increased the perceived fruity character in these wines and decreased the IBMP concentration. - They looked at how IBMP evolves in a bottle for CS and SB. After 3 years of aging they found no - change. One should not count on time to diminish a methoxypyrazine, or bell pepper, defect. ## _**Viticultural implications:**_ • It seems IBMP is directly related to vegetative growth. Vigorous vines that stopped growing relatively late in the season produced higher IBMP concentrations. Also, higher irrigated vines produced more IBMP compared to normal or dry-farmed vines, as has been previously reported. - IBMP synthesis takes place between fruit set and 2-3 weeks prior to veraison. In the berry, it is - synthesized mainly in the skins, some in the seeds, and very little in
Distance: 0.7094549

--- Document 3 ---
higher irrigated vines produced more IBMP compared to normal or dry-farmed vines, as has been previously reported. - IBMP synthesis takes place between fruit set and 2-3 weeks prior to veraison. In the berry, it is - synthesized mainly in the skins, some in the seeds, and very little in the pulp. • The authors found that leaves had the highest concentrations of IBMP. Furthermore, using radioactive IBMP they were able to see that the compound was transported by the phloem from the leaves to the berries. The compound is also believed to be synthesized in the berries, so its presence in the berry is likely due to both transport from leaves and synthesis _in situ._ • From veraison to ripeness, the cycle changes and IBMP begins to break down. It actually breaks down faster than it is synthesized. And daylight accelerates this degradation. The authors found that the degradation products have no bell pepper character. By exposing grapes to sunlight, leaf removal helps decrease IBMP. • After harvest, IBMP still remains high only in the stems. That explains why destemming decreases bell pepper character and improves quality. • In a detailed experiment, the researchers compared IBMP levels of summer-pruned vines (basal leaves and laterals removed) which had also been cluster thinned, against a control. The former vines had much lower IBMP, as well as higher phenols and more alcohol, than the control. In general, they recommend lateral and leaf removal as a means to produce high-quality grapes. The benefits they found include: improved crop healthiness, better aeration, and removal of "sinks", which in turn promoted better photosynthate distribution and grape ripeness. • When leaves are removed early, grape sugar is higher, berries are smaller, and IBMP decreases. A later leaf removal will still facilitate earlier sugar ripeness, but it doesn’t decrease IBMP concentrations in the fruit. Thus, the researchers recommend that leaf removal be performed early, between set and berry touch, or green berry size. • To conclude, the author notes "it is probable that an early diagnosis (July) of the grape IBMP would help determine whether lateral removal or leaf removal are needed in a vineyard block". This would help reduce costs in some instances and still achieve high quality grapes. **In conclusion,** the researchers determined that, in this study, there was only one way to effectively decrease IBMP concentrations once the affected red grapes have reached the winery: **thermovinification** . There are obvious pros and cons with heating a red must, though, and the winemaker would have to make that judgment. As for white grapes, **must cold-settling** was the only way to reduce IBMP, since this compound tended to sediment along with the grape solids. It seems that the most effective and efficient way to mitigate IBMP concentration in grape berries is by vineyard management practices. If it isn’t managed in the vineyard, it will most certainly become a winemaking problem with few alternatives besides blending. _Author: Bibiana Guerra, Editor: Kay Bogart. This summary series funded by_
Distance: 1.0180715

In [29]:
print("QUESTION:")
print(sample["question"])

print("\nEXPECTED ANSWER:")
print(sample["answer"])

print("\nORIGINAL CONTEXT:")
print(sample["context"])

QUESTION:
What IBMP detection threshold did researchers find in Bordeaux-type red wine, and which single winery technique effectively reduced IBMP in red musts in their trials?

EXPECTED ANSWER:
Using a trained panel, they found the IBMP detection threshold in Bordeaux-type red wine is 15 ng/l. Thermovinification was the only winemaking technique that decreased IBMP concentrations in their red-wine trials, attributed to methoxypyrazine volatilization at 50°C.

ORIGINAL CONTEXT:
%IMAGE_DESCRIPTION: University of California Davis - Viticulture & Enology%

%IMAGE_DESCRIPTION: TRELLIS ALLIANCE U.C.DAVIS%

## Title: **“Research on 2-methoxy-3-isobutylpyrazine in grapes and wines”**

By:  Dominique Roujou De Boubee

School of Enology, University of Bordeaux II. Unpublished.

Pyrazines are nitrogen-containing heterocyclic compounds that can be classified in 3 categories, depending on their origin: 1) those formed by heat treatment, 2) those formed by microorganisms, and 3) those present naturally in plants. We are particularly interested in the latter category, and within it, in 2-methoxy-3isobutylpyrazine (IBMP), the main compound responsible for green bell pepper aroma in wines.

## _**Enological implications:**_

• It has already been established that IBMP’s detection threshold in water is 2 ng/l. The researchers went on to determine the equivalent threshold in red wine. Because the answer varied with the type of wine, they had to be more specific. Using a trained panel, they found that the IBMP detection threshold in Bordeauxtype red wine is 15 ng/l

• High concentrations of IBMP are associated with a lack of ripeness and winemakers often associate this bell pepper character with low anthocyanins, or weak color, and mediocre tannin quality. Therefore the paper proceeds to explore actual production operations or winemaking conditions that would minimize IBMP concentration.

• The researchers looked at the IBMP concentration in different SB press fractions. Similar concentrations were found in the free run and in the 1.5 or 2 bar fraction (pneumatic pressing of whole clusters), so the compound is easily extractable.

• They looked at the effect of white must settling on IBMP. After settling of the SB, the compound was half the original amount. So this step is important to reduce greenness. They thought what was going on was that IBMP interacted with grape solids and was carried down with them.

• The researchers also looked at different pump-over regimes and different lengths of skin contact. They concluded that the IBMP was not significantly affected by these extraction techniques. So more punchdowns, or extended macerations will not increase IBMP concentration.

• Thermovinification, however, was the only winemaking technique that actually decreased IBMP concentrations in their trials. This is believed to be due to methoxypyrazine’s volatilization at 50[o] C. So this is an interesting alternative when grapes are believed to be unripe, or moldy. Heating the must to 50[o] C actually increased the perceived fruity character in these wines and decreased the IBMP concentration.

- They looked at how IBMP evolves in a bottle for CS and SB. After 3 years of aging they found no

- change. One should not count on time to diminish a methoxypyrazine, or bell pepper, defect.

## _**Viticultural implications:**_

• It seems IBMP is directly related to vegetative growth. Vigorous vines that stopped growing relatively late in the season produced higher IBMP concentrations. Also, higher irrigated vines produced more IBMP compared to normal or dry-farmed vines, as has been previously reported.

- IBMP synthesis takes place between fruit set and 2-3 weeks prior to veraison. In the berry, it is

- synthesized mainly in the skins, some in the seeds, and very little in the pulp.

• The authors found that leaves had the highest concentrations of IBMP. Furthermore, using radioactive IBMP they were able to see that the compound was transported by the phloem from the leaves to the berries. The compound is also believed to be synthesized in the berries, so its presence in the berry is likely due to both transport from leaves and synthesis _in situ._

• From veraison to ripeness, the cycle changes and IBMP begins to break down. It actually breaks down faster than it is synthesized. And daylight accelerates this degradation. The authors found that the degradation products have no bell pepper character. By exposing grapes to sunlight, leaf removal helps decrease IBMP.

• After harvest, IBMP still remains high only in the stems. That explains why destemming decreases bell pepper character and improves quality.

• In a detailed experiment, the researchers compared IBMP levels of summer-pruned vines (basal leaves and laterals removed) which had also been cluster thinned, against a control. The former vines had much lower IBMP, as well as higher phenols and more alcohol, than the control. In general, they recommend lateral and leaf removal as a means to produce high-quality grapes. The benefits they found include: improved crop healthiness, better aeration, and removal of "sinks", which in turn promoted better photosynthate distribution and grape ripeness.

• When leaves are removed early, grape sugar is higher, berries are smaller, and IBMP decreases. A later leaf removal will still facilitate earlier sugar ripeness, but it doesn’t decrease IBMP concentrations in the fruit. Thus, the researchers recommend that leaf removal be performed early, between set and berry touch, or green berry size.

• To conclude, the author notes "it is probable that an early diagnosis (July) of the grape IBMP would help determine whether lateral removal or leaf removal are needed in a vineyard block". This would help reduce costs in some instances and still achieve high quality grapes.

**In conclusion,** the researchers determined that, in this study, there was only one way to effectively decrease IBMP concentrations once the affected red grapes have reached the winery: **thermovinification** . There are obvious pros and cons with heating a red must, though, and the winemaker would have to make that judgment. As for white grapes, **must cold-settling** was the only way to reduce IBMP, since this compound tended to sediment along with the grape solids.

It seems that the most effective and efficient way to mitigate IBMP concentration in grape berries is by vineyard management practices. If it isn’t managed in the vineyard, it will most certainly become a winemaking problem with few alternatives besides blending.

_Author: Bibiana Guerra, Editor: Kay Bogart. This summary series funded by_ J. Lohr Vineyards & Wines _._

In [30]:
# Create embeddings for the original 100 contexts
original_contexts = df["context"].fillna("").tolist()

original_embeddings = model.encode(
    original_contexts,
    convert_to_numpy=True
).astype("float32")

print("Original contexts:", len(original_contexts))
print("Embedding shape:", original_embeddings.shape)

Original contexts: 100
Embedding shape: (100, 384)

In [31]:
# Create a FAISS index for the original contexts
original_index = faiss.IndexFlatL2(
    original_embeddings.shape[1]
)

original_index.add(original_embeddings)

# Embed our dataset question
question = sample["question"]

query_embedding = model.encode(
    [question]
).astype("float32")

# Retrieve the top 3 original contexts
distances, indices = original_index.search(
    query_embedding, 3
)

print("Question:", question)
print("\nTop 3 original contexts:\n")

for rank, idx in enumerate(indices[0], start=1):
    print(f"\n--- Result {rank} ---")
    print(original_contexts[idx][:1500])
    print("Distance:", distances[0][rank - 1])

Question: What IBMP detection threshold did researchers find in Bordeaux-type red wine, and which single winery technique effectively reduced IBMP in red musts in their trials?

Top 3 original contexts:


--- Result 1 ---
%IMAGE_DESCRIPTION: University of California Davis - Viticulture & Enology%

%IMAGE_DESCRIPTION: TRELLIS ALLIANCE U.C.DAVIS%

## Title: **“Research on 2-methoxy-3-isobutylpyrazine in grapes and wines”**

By:  Dominique Roujou De Boubee

School of Enology, University of Bordeaux II. Unpublished.

Pyrazines are nitrogen-containing heterocyclic compounds that can be classified in 3 categories, depending on their origin: 1) those formed by heat treatment, 2) those formed by microorganisms, and 3) those present naturally in plants. We are particularly interested in the latter category, and within it, in 2-methoxy-3isobutylpyrazine (IBMP), the main compound responsible for green bell pepper aroma in wines.

## _**Enological implications:**_

• It has already been established that IBMP’s detection threshold in water is 2 ng/l. The researchers went on to determine the equivalent threshold in red wine. Because the answer varied with the type of wine, they had to be more specific. Using a trained panel, they found that the IBMP detection threshold in Bordeauxtype red wine is 15 ng/l

• High concentrations of IBMP are associated with a lack of ripeness and winemakers often associate this bell pepper character with low anthocyanins, or weak color, and mediocre tannin quality. Therefore the paper proceeds to explore actual production operations or winemaking conditions that would minimize IBMP concentration.

• The researchers looked at the IBMP concentration in different SB press
Distance: 0.8701078

--- Result 2 ---
%IMAGE_DESCRIPTION: A woman wearing a blue face mask, blue gloves, and a yellow apron is cleaning a surface with a yellow cloth and blue spray bottle. The image appears to be an article header about sunbed cleaning best practices.%

Third, use a fresh towel to disinfect each bed. Here is a tanning horror story: I was training a salon team and noticed a towel draped over a bottle of disinfectant. They used that towel on every bed, all day long ... terrifying! Tingle products, sweat (and whatever else) being smeared from one sunbed acrylic to the next. I don’t need to say it: don’t do this.

The sunbed disinfectant experts advise you to spray the solution on the acrylic and wait 60 seconds. It takes that

Check the labels thoroughly and make sure you use a product that provides a clean tanning surface and takes the best possible care of your acrylics.

long to sanitize the acrylic – don’t just spray and wipe! Waiting 60 seconds sanitizes and kills 99.9% of fungus and germs. So, spray the acrylic, empty the wastebasket, wipe the door handle and mop the floor, and then wipe the bed with a fresh towel. Your evening routine should be to spray and wait ten minutes to disinfect. This kills 100% of the viruses and other stuff you don’t want on your bed and needs to be done at least once a day.

Finally, solution needs to be made fresh daily and tested with a quat strip. Don’t mix huge quantities to use for several days – it will lose its efficacy quickly.

As I mentioned in the A
Distance: 1.5054929

--- Result 3 ---
## **MEDICAL RESEARCH COUNCIL**

%IMAGE_DESCRIPTION: UK Research Council (UKRI) logo featuring a navy blue and light blue geometric design on the left, with the text "Medical Research Council" on the right%

## **03**

Author: Simone Bryan

Trade Union Access: in part

## **Minutes of the Council meeting held at 58 Victoria Embankment on 17 October 2019**

## **Present:**

|**Council**|**Head Office staff**|
|---|---|
|Professor Fiona Watt (Executive Chair)|Ms Rachel Benny|
|Dr Roger Highfield|Ms Simone Bryan|
|Professor John Iredale|Dr Rob Buckle|
|Mr Richard Murley|Professor Patrick Chinnery|
|Professor Jill Pell|Mr Hugh Dunlop|
|Professor Sir Munir Pirmohamed|Dr Declan Mulkeen|
|Professor Eleanor Riley|Dr Frances Rawle|
|Dr Graham Spittle|Dr Susan Simon|
|Professor Irene Tracey||
|Dr Pauline Williams (via telephone)||
|Dr Louise Wood||
||**Guests**|
|**UKRI Observers**|Lisa Dinh (item 5)|
|Mike Blackburn|Sarah Collinge (Item 8)|
|Isobel Stephen|Toni-Jo Henderson(Item 7)|
||Dr Louise Jones(item 10)|
|**Apologies**|Jill Jones(item 9)|
|John Brown|Professor Catherine Law(item 9)|
|Mene Pangalos|Dr Ian Viney (item 10)|
|Charlotte Watts||



## **1. Welcome and introductions**

Professor Fiona Watt welcomed everyone to the meeting and introduced Isobel Stephen and Mike Blackburn, as the senior UKRI observers. Professor Watt welcomed Rachel Benny who was joining the Council Secretariat as the Governance Manager. Professor Watt also noted that this meeting was the last Dr
Distance: 1.595156

In [32]:
# Find original contexts containing IBMP
matches = df[
    df["context"].str.contains(
        "Research on 2-methoxy-3-isobutylpyrazine",
        case=False,
        na=False
    )
]

print("Matching rows:", len(matches))

for idx, row in matches.iterrows():
    print("\nRow index:", idx)
    print("Category:", row["category"])
    print("Question:", row["question"])
    print("Expected answer:", row["answer"])

Matching rows: 1

Row index: 0
Category: agriculture
Question: What IBMP detection threshold did researchers find in Bordeaux-type red wine, and which single winery technique effectively reduced IBMP in red musts in their trials?
Expected answer: Using a trained panel, they found the IBMP detection threshold in Bordeaux-type red wine is 15 ng/l. Thermovinification was the only winemaking technique that decreased IBMP concentrations in their red-wine trials, attributed to methoxypyrazine volatilization at 50°C.

In [33]:
# Embed the question again
query_embedding = model.encode(
    [sample["question"]]
).astype("float32")

# Calculate similarity distances against all 100 contexts
distances, indices = original_index.search(
    query_embedding, len(original_contexts)
)

# Find the position of the matching original context
matching_index = matches.index[0]
rank = list(indices[0]).index(matching_index) + 1

print("Correct context row:", matching_index)
print("Rank in retrieval:", rank, "out of", len(original_contexts))
print("Distance:", distances[0][rank - 1])

Correct context row: 0
Rank in retrieval: 1 out of 100
Distance: 0.8701078

In [34]:
# Get the best matching original context
best_context = original_contexts[indices[0][0]]

question = sample["question"]

prompt = f"""
Answer the question using only the context below.
If the context does not contain the answer, say so.
Do not invent facts.

Context:
{best_context}

Question:
{question}

Answer:
"""

response = client.chat.completions.create(
    model="openai/gpt-oss-20b",
    messages=[
        {"role": "user", "content": prompt}
    ],
    temperature=0
)

rag_answer = response.choices[0].message.content

print("Question:", question)
print("\nRAG answer:")
print(rag_answer)

print("\nExpected dataset answer:")
print(sample["answer"])

Question: What IBMP detection threshold did researchers find in Bordeaux-type red wine, and which single winery technique effectively reduced IBMP in red musts in their trials?

RAG answer:
The researchers found the IBMP detection threshold in Bordeaux‑type red wine to be **15 ng L⁻¹**.
The only winery technique that effectively reduced IBMP in red musts in their trials was **thermovinification** (heating the must to about 50 °C).

Expected dataset answer:
Using a trained panel, they found the IBMP detection threshold in Bordeaux-type red wine is 15 ng/l. Thermovinification was the only winemaking technique that decreased IBMP concentrations in their red-wine trials, attributed to methoxypyrazine volatilization at 50°C.

In [35]:
def ask_rag(question):
    # 1. Convert question into embedding
    query_embedding = model.encode(
        [question]
    ).astype("float32")

    # 2. Retrieve the best original context
    distances, indices = original_index.search(
        query_embedding, 1
    )

    context = original_contexts[indices[0][0]]

    # 3. Create prompt
    prompt = f"""
Answer the question using only the context below.
If the answer is not available, say so.
Do not invent facts.

Context:
{context}

Question:
{question}

Answer:
"""

    # 4. Generate answer with Groq
    response = client.chat.completions.create(
        model="openai/gpt-oss-20b",
        messages=[{"role": "user", "content": prompt}],
        temperature=0
    )

    return response.choices[0].message.content

In [36]:
question = df.iloc[1]["question"]

print("Question:", question)
print("\nRAG Answer:")
print(ask_rag(question))

Question: Who is scheduled to teach ATM S 101 Weather in Autumn 2021 and Winter 2022, and who teaches 103 Hurricanes & Thunderstorms in Spring 2022?

RAG Answer:

In [37]:
question = df.iloc[1]["question"]

# Retrieve the best matching context
query_embedding = model.encode([question]).astype("float32")
distances, indices = original_index.search(query_embedding, 1)

retrieved_context = original_contexts[indices[0][0]]

print("QUESTION:")
print(question)

print("\nRETRIEVED CONTEXT:")
print(retrieved_context[:2000])

print("\nEXPECTED DATASET ANSWER:")
print(df.iloc[1]["answer"])

QUESTION:
Who is scheduled to teach ATM S 101 Weather in Autumn 2021 and Winter 2022, and who teaches 103 Hurricanes & Thunderstorms in Spring 2022?

RETRIEVED CONTEXT:
||||**ATM S 2021-2022 Teaching Schedule**|**ATM S 2021-2022 Teaching Schedule**|**ATM S 2021-2022 Teaching Schedule**|**ATM S 2021-2022 Teaching Schedule**|**ATM S 2021-2022 Teaching Schedule**|**ATM S 2021-2022 Teaching Schedule**|
|---|---|---|---|---|---|---|---|---|
||||||||||
|**Autumn 2021**|||**Winter 2022**|||**Spring 2022**|||
||||||||||
||||**Undergraduate non-major courses**||||||
|101|Weather|Mass|101|Weather|Hakim|103|Hurricanes & Thunderstorms|Anderson-Frey|
|111|Global Warming|Huybers|111|Global Warming|Huybers|111|Global Warming|Huybers|
|211|Cimate & Climate Change|Fu|220|Exploringthe ATMS|Frierson/Cox|211|Climate & Climate Change|Jaegle|
|220|Exploringthe ATMS|Black|290|The Weather Challenge|Student|220|Exploringthe ATMS|Student|
|290|The Weather Challenge|McMurdie|361|Meteorologyand the Media|Student|490|Non-Major Weather Analysis|Lloveras|
|490|Non-Major Weather Analysis|Lloveras|490|Non-Major Weather Analysis|Student|495|EarthGames|Frierson|
|495|EarthGames|Frierson|495|EarthGames|Frierson||||
||||||||||
||||**Undergraduate major courses**||||||
|301|Intro to Atmosphere Science|Chen/Sava|340|Intro Thermo & Cloud Proc|Pennypacker|321|The Science of Climate|Hartmann|
|310|Python|Anderson-Frey|341|Atmospheric Radiative Transfer|?|341|Atmos Radiative Transfer|Turner|
|350|Ecological Climatology|Swann|358|Fundamentals of Atmospheric C|hThornton|358|Fundamen Atmos Chem|Thornton|
|431|Boundary-Layer Meteorology|Wood|370|Atmos Structure & Analysis|Mass|452|Wea Fore & Adv Syn Met|Mass|
|441(503)|Atmospheric Motions I|Hakim|442(504)|Atmospheric Motions II|Bretherton||||
|458|Air Pollution Chemistry|Thornton|451|Instruments & Observations|Alexander/Anderson-Frey||||
|487(587)|Fund of Climate Change|Frierson|||||||
||||**Undergraduate elective courses**||||||
||||361|Meteorologyand the Media|O'Donnel||||
||||||||||
||||**Graduate required courses**||||||
|501|Fund of Phys & Chem of Atmos|Hartmann/Turner|509|Geophsyical Fluid Dynamics|Durran|502|Intro Synopt

EXPECTED DATASET ANSWER:
In Autumn 2021, 101 Weather is taught by Mass; in Winter 2022 it is taught by Hakim; and in Spring 2022, 103 Hurricanes & Thunderstorms is taught by Anderson-Frey.

In [38]:
print("Dataset question:")
print(df.iloc[1]["question"])

print("\nExpected dataset answer:")
print(df.iloc[1]["answer"])

Dataset question:
Who is scheduled to teach ATM S 101 Weather in Autumn 2021 and Winter 2022, and who teaches 103 Hurricanes & Thunderstorms in Spring 2022?

Expected dataset answer:
In Autumn 2021, 101 Weather is taught by Mass; in Winter 2022 it is taught by Hakim; and in Spring 2022, 103 Hurricanes & Thunderstorms is taught by Anderson-Frey.

In [39]:
def ask_rag(question):
    # 1. Convert question into an embedding
    query_embedding = model.encode(
        [question]
    ).astype("float32")

    # 2. Retrieve the most relevant original context
    distances, indices = original_index.search(
        query_embedding, 1
    )

    context = original_contexts[indices[0][0]]

    # 3. Create a clear prompt
    prompt = f"""
You answer questions using the supplied document.

The document may contain tables. Read the column headings
and match each course to the correct semester.

Use only the document. If information is missing, say so.

Document:
{context}

Question:
{question}

Answer:
"""

    # 4. Generate the answer
    try:
        response = client.chat.completions.create(
            model="openai/gpt-oss-20b",
            messages=[
                {"role": "user", "content": prompt}
            ],
            temperature=0,
            max_tokens=250
        )

        answer = response.choices[0].message.content

        if not answer or not answer.strip():
            return "The model returned an empty answer."

        return answer.strip()

    except Exception as e:
        return f"Groq error: {e}"

In [40]:
question = df.iloc[1]["question"]

print("Question:", question)
print("\nRAG Answer:")
print(ask_rag(question))

Question: Who is scheduled to teach ATM S 101 Weather in Autumn 2021 and Winter 2022, and who teaches 103 Hurricanes & Thunderstorms in Spring 2022?

RAG Answer:
The model returned an empty answer.

In [41]:
response = client.chat.completions.create(
    model="openai/gpt-oss-20b",
    messages=[
        {
            "role": "user",
            "content": "Reply with exactly: Hello, RAG!"
        }
    ],
    temperature=0,
    max_tokens=100
)

print("Finish reason:", response.choices[0].finish_reason)
print("Message:", repr(response.choices[0].message.content))
print("Usage:", response.usage)

Finish reason: stop
Message: 'Hello, RAG!'
Usage: CompletionUsage(completion_tokens=50, prompt_tokens=80, total_tokens=130, completion_time=0.068750933, completion_tokens_details=CompletionTokensDetails(reasoning_tokens=36), prompt_time=0.003822671, prompt_tokens_details=None, queue_time=0.167003149, total_time=0.072573604)

In [42]:
question = df.iloc[1]["question"]
context = original_contexts[1]

response = client.chat.completions.create(
    model="openai/gpt-oss-20b",
    messages=[
        {
            "role": "system",
            "content": "Answer questions clearly using the supplied context."
        },
        {
            "role": "user",
            "content": f"""
Context:
{context}

Question:
{question}

Give a short, direct answer.
"""
        }
    ],
    temperature=0,
    max_tokens=300
)

print("Finish reason:", response.choices[0].finish_reason)
print("Answer:", repr(response.choices[0].message.content))

Finish reason: length
Answer: ''

In [43]:
question = df.iloc[1]["question"]
context = original_contexts[1]

response = client.chat.completions.create(
    model="openai/gpt-oss-20b",
    messages=[
        {
            "role": "user",
            "content": (
                "Answer this question from the document. "
                "Be concise.\n\n"
                f"Document:\n{context}\n\n"
                f"Question: {question}"
            )
        }
    ],
    max_tokens=500,
    temperature=0
)

print("Finish reason:", response.choices[0].finish_reason)
print("Answer:", repr(response.choices[0].message.content))
print("Completion tokens:", response.usage.completion_tokens)

Finish reason: stop
Answer: '- **ATM\u202fS\u202f101\u202fWeather**  \n  - Autumn\u202f2021: **Mass**  \n  - Winter\u202f2022: **Hakim**  \n\n- **ATM\u202fS\u202f103\u202fHurricanes & Thunderstorms** (Spring\u202f2022): **Anderson‑Frey**'
Completion tokens: 378

In [44]:
print("Question:")
print(question)

print("\nRAG Answer:")
print(response.choices[0].message.content)

Question:
Who is scheduled to teach ATM S 101 Weather in Autumn 2021 and Winter 2022, and who teaches 103 Hurricanes & Thunderstorms in Spring 2022?

RAG Answer:
- **ATM S 101 Weather**
  - Autumn 2021: **Mass**
  - Winter 2022: **Hakim**

- **ATM S 103 Hurricanes & Thunderstorms** (Spring 2022): **Anderson‑Frey**

In [45]:
def ask_rag(question):
    # 1. Convert question into an embedding
    query_embedding = model.encode(
        [question]
    ).astype("float32")

    # 2. Retrieve the most relevant original context
    distances, indices = original_index.search(
        query_embedding, 1
    )

    context = original_contexts[indices[0][0]]

    # 3. Prepare a short, clear prompt
    prompt = f"""
Answer the question using only the document.
Be concise and accurate.
If the answer is missing, say so.

Document:
{context}

Question:
{question}

Answer:
"""

    # 4. Generate answer
    response = client.chat.completions.create(
        model="openai/gpt-oss-20b",
        messages=[
            {"role": "user", "content": prompt}
        ],
        temperature=0,
        max_tokens=500
    )

    # 5. Return answer
    answer = response.choices[0].message.content

    if not answer or not answer.strip():
        return "No visible answer returned. Please try again."

    return answer.strip()

In [46]:
question = df.iloc[1]["question"]

print("Question:", question)
print("\nRAG Answer:")
print(ask_rag(question))

Question: Who is scheduled to teach ATM S 101 Weather in Autumn 2021 and Winter 2022, and who teaches 103 Hurricanes & Thunderstorms in Spring 2022?

RAG Answer:
- **ATM S 101 Weather**
  - Autumn 2021: **Mass**
  - Winter 2022: **Hakim**

- **ATM S 103 Hurricanes & Thunderstorms** (Spring 2022): **Anderson‑Frey**

In [47]:
def ask_rag(question):
    query_embedding = model.encode(
        [question]
    ).astype("float32")

    distances, indices = original_index.search(
        query_embedding, 1
    )

    context = original_contexts[indices[0][0]]

    response = client.chat.completions.create(
        model="openai/gpt-oss-20b",
        messages=[
            {
                "role": "user",
                "content": f"""
Use the document to answer every part of the question.
Give one concise sentence. Do not stop after the first part.

Document:
{context}

Question:
{question}
"""
            }
        ],
        temperature=0,
        max_tokens=800
    )

    return response.choices[0].message.content

In [48]:
question = df.iloc[1]["question"]
print(ask_rag(question))

In [49]:
question = df.iloc[1]["question"]

query_embedding = model.encode(
    [question]
).astype("float32")

distances, indices = original_index.search(
    query_embedding, 1
)

context = original_contexts[indices[0][0]]

response = client.chat.completions.create(
    model="openai/gpt-oss-20b",
    messages=[
        {
            "role": "user",
            "content": (
                "Answer briefly using this document.\n\n"
                + context[:4000]
                + "\n\nQuestion: "
                + question
                + "\nGive the complete answer."
            )
        }
    ],
    temperature=0,
    max_tokens=800
)

print("Finish reason:", response.choices[0].finish_reason)
print("Answer:", repr(response.choices[0].message.content))
print("Completion tokens:", response.usage.completion_tokens)

Finish reason: stop
Answer: '- **ATM\u202fS\u202f101\u202fWeather**  \n  - Autumn\u202f2021: taught by **Hakim**  \n  - Winter\u202f2022: taught by **Hakim**\n\n- **ATM\u202fS\u202f103\u202fHurricanes & Thunderstorms**  \n  - Spring\u202f2022: taught by **Anderson‑Frey**'
Completion tokens: 475

In [50]:
print("EXPECTED ANSWER:")
print(df.iloc[1]["answer"])

print("\nSCHEDULE SECTION FROM CONTEXT:")
context = original_contexts[1]

for line in context.splitlines():
    if "101|Weather" in line or "103|Hurricanes" in line:
        print(line)

EXPECTED ANSWER:
In Autumn 2021, 101 Weather is taught by Mass; in Winter 2022 it is taught by Hakim; and in Spring 2022, 103 Hurricanes & Thunderstorms is taught by Anderson-Frey.

SCHEDULE SECTION FROM CONTEXT:
|101|Weather|Mass|101|Weather|Hakim|103|Hurricanes & Thunderstorms|Anderson-Frey|

In [51]:
question = df.iloc[1]["question"]
context = original_contexts[1]

response = client.chat.completions.create(
    model="openai/gpt-oss-20b",
    messages=[
        {
            "role": "user",
            "content": f"""
Read the semester headings and course schedule carefully.
Match each instructor to the correct semester.
Answer all parts of the question in one sentence.

Context:
{context[:6000]}

Question:
{question}
"""
        }
    ],
    temperature=0,
    max_tokens=800
)

print(response.choices[0].message.content)

In [52]:
print("Finish reason:", response.choices[0].finish_reason)
print("Answer:", repr(response.choices[0].message.content))
print("Completion tokens:", response.usage.completion_tokens)
print("Token details:", response.usage.completion_tokens_details)

Finish reason: length
Answer: ''
Completion tokens: 800
Token details: CompletionTokensDetails(reasoning_tokens=798)

In [53]:
question = df.iloc[1]["question"]

response = client.chat.completions.create(
    model="openai/gpt-oss-20b",
    messages=[
        {
            "role": "user",
            "content": (
                "Answer briefly. Use this exact information:\n"
                "Autumn 2021, ATM S 101 Weather: Mass.\n"
                "Winter 2022, ATM S 101 Weather: Hakim.\n"
                "Spring 2022, ATM 103 Hurricanes & Thunderstorms: "
                "Anderson-Frey.\n\n"
                "Return the three assignments in one sentence."
            )
        }
    ],
    reasoning_effort="low",
    max_tokens=300,
    temperature=0
)

print("Finish reason:", response.choices[0].finish_reason)
print("Answer:", response.choices[0].message.content)
print("Token details:", response.usage.completion_tokens_details)

Finish reason: stop
Answer: In Autumn 2021, ATM S 101 Weather: Mass; in Winter 2022, ATM S 101 Weather: Hakim; and in Spring 2022, ATM 103 Hurricanes & Thunderstorms: Anderson‑Frey.
Token details: CompletionTokensDetails(reasoning_tokens=8)

In [54]:
def ask_rag(question):
    # 1. Convert question into an embedding
    query_embedding = model.encode(
        [question]
    ).astype("float32")

    # 2. Retrieve the best matching context
    distances, indices = original_index.search(
        query_embedding, 1
    )

    context = original_contexts[indices[0][0]]

    # 3. Prepare the prompt
    prompt = f"""
Answer the question using only the document.
Be concise and answer every part.
If the answer is missing, say so.

Document:
{context}

Question:
{question}
"""

    # 4. Generate the answer
    response = client.chat.completions.create(
        model="openai/gpt-oss-20b",
        messages=[
            {"role": "user", "content": prompt}
        ],
        reasoning_effort="low",
        temperature=0,
        max_tokens=500
    )

    answer = response.choices[0].message.content

    if not answer or not answer.strip():
        return "No visible answer returned."

    return answer.strip()

In [55]:
question = df.iloc[1]["question"]

print("Question:")
print(question)

print("\nRAG Answer:")
print(ask_rag(question))

Question:
Who is scheduled to teach ATM S 101 Weather in Autumn 2021 and Winter 2022, and who teaches 103 Hurricanes & Thunderstorms in Spring 2022?

RAG Answer:
- **ATM S 101 Weather**
  - Autumn 2021: **Mass**
  - Winter 2022: **Hakim**

- **ATM S 103 Hurricanes & Thunderstorms** (Spring 2022): **Anderson‑Frey**

In [56]:
def ask_rag(question):
    # 1. Embed the question
    query_embedding = model.encode(
        [question]
    ).astype("float32")

    # 2. Retrieve the best matching context
    distances, indices = original_index.search(
        query_embedding, 1
    )

    context = original_contexts[indices[0][0]]

    # 3. Limit the context size
    MAX_CONTEXT_CHARS = 6000
    context = context[:MAX_CONTEXT_CHARS]

    # 4. Prepare a short prompt
    prompt = f"""
Answer the question using only the document.
Answer every part clearly. Do not invent facts.

Document:
{context}

Question:
{question}
"""

    # 5. Generate the answer
    response = client.chat.completions.create(
        model="openai/gpt-oss-20b",
        messages=[
            {"role": "user", "content": prompt}
        ],
        reasoning_effort="low",
        temperature=0,
        max_tokens=500
    )

    answer = response.choices[0].message.content

    if not answer or not answer.strip():
        return "No visible answer returned."

    return answer.strip()

In [57]:
question = df.iloc[2]["question"]

print("Question:")
print(question)

print("\nExpected answer:")
print(df.iloc[2]["answer"])

print("\nRAG answer:")
print(ask_rag(question))

Question:
In the 2015 Nevada early childhood education opinion poll of 384 adults, what share of respondents agreed ECE affects later success, and what did they identify as the biggest barrier to accessing ECE?

Expected answer:
96.6% agreed that early childhood education has an impact on a child’s ability to be successful later in life. Cost was perceived as the biggest barrier to accessing ECE, cited by 43.7% of respondents, followed by availability/location at 20.3%.

RAG answer:
**Share of respondents who agreed that early‑childhood education (ECE) affects later success:**
- **96.6 %** of the 384 adults surveyed in the 2015 Nevada opinion poll agreed that ECE has an impact on a child’s success later in life.

**Identified biggest barrier to accessing ECE:**
- The poll results presented in the document do **not** specify which barrier respondents identified as the biggest obstacle to accessing ECE. The report notes that disparities persist because of financial, availability, and quality barriers, but it does not report a single barrier as being identified by the respondents as the “biggest” one.

In [58]:
question = df.iloc[2]["question"]

query_embedding = model.encode(
    [question]
).astype("float32")

distances, indices = original_index.search(
    query_embedding, 1
)

context = original_contexts[indices[0][0]]

print("Context length:", len(context))
print("\nMentions of cost:")
for line in context.splitlines():
    if "cost" in line.lower() or "barrier" in line.lower():
        print(line[:1000])

Context length: 37565

Mentions of cost:
Still, disparities persist for those who are unable to access ECE due to financial, availability, and quality barriers. Providing access to high quality early childhood education to all children is starting to be seen as a priority among parents, and the results of this report show that Nevadans agree that more should be done to ensure the availability and quality of ECE for children in the state.
This report details the results of an opinion poll conducted in 2015 among adults aged 18 and over in the state of Nevada. Participants were asked about their opinions and perceptions regarding: living in Nevada, education within the state, and the benefits of and barriers to accessing quality early childhood education.
|Health care or health insurance costs|11.5%|
Nevadans were also asked to list what they thought was the biggest barrier to accessing early childhood education. As shown in the table below, cost was perceived to be the biggest barrier.
|Biggest barrier in accessing early childhood education:|
|Cost|43.7%|
|Taxes or budget deficit<br>Education and schools<br>Crime and drugs<br>Affordable housing<br>Child abuse or child welfare issues<br>Health care or health insurance costs<br>The environment<br>Early childhood education||17.3%<br>42.0%<br>17.3%<br>0%<br>3.7%<br>13.6%<br>0%<br>6.2%||3.8%<br>49.1%<br>17.9%<br>4.7%<br>8.5%<br>10.4%<br>2.8%<br>2.8%||10.0%<br>53.3%<br>8.3%<br>6.7%<br>6.7%<br>6.7%<br>3.3%<br>5.0%|
|**Biggest barrier in accessing early childhood**<br>**education:**|||||||
|Cost<br>Quality<br>Reliability (hours of operation<br>Availability (location)<br>Other||45.5%<br>6.5%<br>1.3%<br>16.9%<br>29.9%||37.9%<br>14.6%<br>5.8%<br>26.2%<br>15.5%||47.4%<br>8.8%<br>5.3%<br>12.3%<br>26.3%|

In [59]:
question = df.iloc[2]["question"]
context = original_contexts[indices[0][0]]

keywords = ["96.6%", "biggest barrier", "Cost|43.7%"]

for keyword in keywords:
    position = context.lower().find(keyword.lower())

    print(f"\n--- Search: {keyword} ---")

    if position != -1:
        start = max(0, position - 300)
        end = min(len(context), position + 700)
        print(context[start:end])
    else:
        print("Not found")

--- Search: 96.6% ---
the knowledge and skills required to succeed in school and think that access to quality early childhood education programs would increase children’s ability to succeed academically.

- 63.0% think that _50% or fewer of Nevada’s children_ start kindergarten with the necessary skills to succeed.

- 96.6% _AGREE_ that ECE has an impact on a child’s success later in life.

- 74.8% think that access to quality ECE is _Very Important_ to students’ K-12 success.

In addition, the majority of Nevadans feel that our state should be doing more to help ensure our children have access to quality early childhood education and are able to start school ready to learn.

- 82.2% think the _community should be doing more_ to help children begin kindergarten with better skills

- 69.9% agree that children living in low-income families _DO NOT_ begin 1[st] grade just as prepared as children living in middle-to-high income families.

- 90.3% say they _are concerned_ that children in lower-income are

--- Search: biggest barrier ---
owledge and skills they need to do their best in school.

- 82.2% of Nevadans indicated that we as a community should be doing more to ensure children begin kindergarten with the knowledge and skills they need to do their best in school.

Nevadans were also asked to list what they thought was the biggest barrier to accessing early childhood education. As shown in the table below, cost was perceived to be the biggest barrier.



<!-- Start of picture text -->
|||
|---|---|
|Biggest barrier in accessing early childhood education:|
|Cost|43.7%|
|Availability (location)|20.3%|
|Quality|8.2%|
|Reliability (hours of operation)|6.4%|
|Other|21.4%|

<!-- End of picture text -->

## _**Quality of Early Childhood Education Centers**_

There is no content to classify. The input appears to be a blank or empty image.

However, I will follow the rules and provide an output for TYPE 3 — ALL OTHER IMAGES:

%IMAGE_DESCRIPTION: Empty image%

Only 13.8% of respondents indicated that the quality of N

--- Search: Cost|43.7% ---


Nevadans were also asked to list what they thought was the biggest barrier to accessing early childhood education. As shown in the table below, cost was perceived to be the biggest barrier.



<!-- Start of picture text -->
|||
|---|---|
|Biggest barrier in accessing early childhood education:|
|Cost|43.7%|
|Availability (location)|20.3%|
|Quality|8.2%|
|Reliability (hours of operation)|6.4%|
|Other|21.4%|

<!-- End of picture text -->

## _**Quality of Early Childhood Education Centers**_

There is no content to classify. The input appears to be a blank or empty image.

However, I will follow the rules and provide an output for TYPE 3 — ALL OTHER IMAGES:

%IMAGE_DESCRIPTION: Empty image%

Only 13.8% of respondents indicated that the quality of Nevada’s ECE programs was excellent, while 47.5% indicated they were average, 31.5% indicated they were below average, and 7.3% indicated that Nevada’s ECE programs were failing.  Accordingly,

- 89.2% agree that ECE centers should partici

In [60]:
question = df.iloc[2]["question"]
context = original_contexts[indices[0][0]]

# Find the relevant passages in the full context
terms = [
    "96.6%_AGREE_",
    "biggest barrier to accessing early childhood education",
    "|Cost|43.7%"
]

passages = []

for term in terms:
    position = context.lower().find(term.lower())

    if position != -1:
        start = max(0, position - 250)
        end = min(len(context), position + 700)
        passages.append(context[start:end])

# Combine the relevant passages
focused_context = "\n\n".join(passages)

print("Focused context:\n")
print(focused_context)

Focused context:

chool.

- 82.2% of Nevadans indicated that we as a community should be doing more to ensure children begin kindergarten with the knowledge and skills they need to do their best in school.

Nevadans were also asked to list what they thought was the biggest barrier to accessing early childhood education. As shown in the table below, cost was perceived to be the biggest barrier.



<!-- Start of picture text -->
|||
|---|---|
|Biggest barrier in accessing early childhood education:|
|Cost|43.7%|
|Availability (location)|20.3%|
|Quality|8.2%|
|Reliability (hours of operation)|6.4%|
|Other|21.4%|

<!-- End of picture text -->

## _**Quality of Early Childhood Education Centers**_

There is no content to classify. The input appears to be a blank or empty image.

However, I will follow the rules and provide an output for TYPE 3 — ALL OTHER IMAGES:

%IMAGE_DESCRIPTION: Empty image%

Only 13.8% of respondents indicated that the quality of N

ght was the biggest barrier to accessing early childhood education. As shown in the table below, cost was perceived to be the biggest barrier.



<!-- Start of picture text -->
|||
|---|---|
|Biggest barrier in accessing early childhood education:|
|Cost|43.7%|
|Availability (location)|20.3%|
|Quality|8.2%|
|Reliability (hours of operation)|6.4%|
|Other|21.4%|

<!-- End of picture text -->

## _**Quality of Early Childhood Education Centers**_

There is no content to classify. The input appears to be a blank or empty image.

However, I will follow the rules and provide an output for TYPE 3 — ALL OTHER IMAGES:

%IMAGE_DESCRIPTION: Empty image%

Only 13.8% of respondents indicated that the quality of Nevada’s ECE programs was excellent, while 47.5% indicated they were average, 31.5% indicated they were below average, and 7.3% indicated that Nevada’s ECE programs were failing.  Accordingly,

- 89.2% agree that ECE centers should partic

In [61]:
response = client.chat.completions.create(
    model="openai/gpt-oss-20b",
    messages=[
        {
            "role": "user",
            "content": f"""
Answer both parts using only the evidence below.
Be concise and do not add unsupported facts.

Evidence:
{focused_context}

Question:
{df.iloc[2]["question"]}
"""
        }
    ],
    reasoning_effort="low",
    temperature=0,
    max_tokens=300
)

print("RAG answer:")
print(response.choices[0].message.content)

RAG answer:
I’m sorry, but the evidence provided does not contain the information needed to answer those questions.

In [62]:
context = original_contexts[indices[0][0]]

# Extract the sentence containing 96.6%
pos1 = context.find("96.6%")
evidence1 = context[max(0, pos1 - 200):pos1 + 250]

# Extract the table containing the cost percentage
pos2 = context.find("|Cost|43.7%")
evidence2 = context[max(0, pos2 - 150):pos2 + 300]

focused_context = evidence1 + "\n\n" + evidence2

print(focused_context)

ood education programs would increase children’s ability to succeed academically.

- 63.0% think that _50% or fewer of Nevada’s children_ start kindergarten with the necessary skills to succeed.

- 96.6% _AGREE_ that ECE has an impact on a child’s success later in life.

- 74.8% think that access to quality ECE is _Very Important_ to students’ K-12 success.

In addition, the majority of Nevadans feel that our state should be doing more to hel

t was perceived to be the biggest barrier.



<!-- Start of picture text -->
|||
|---|---|
|Biggest barrier in accessing early childhood education:|
|Cost|43.7%|
|Availability (location)|20.3%|
|Quality|8.2%|
|Reliability (hours of operation)|6.4%|
|Other|21.4%|

<!-- End of picture text -->

## _**Quality of Early Childhood Education Centers**_

There is no content to classify. The input appears to be a blank or empty image.

However, I will

In [63]:
response = client.chat.completions.create(
    model="openai/gpt-oss-20b",
    messages=[
        {
            "role": "user",
            "content": f"""
Answer both parts using the evidence below.
Return only the answer.

Evidence:
{focused_context}

Question:
{df.iloc[2]["question"]}
"""
        }
    ],
    reasoning_effort="low",
    temperature=0,
    max_tokens=250
)

print(response.choices[0].message.content)

- **Agreement that ECE affects later success:** 96.6% of respondents.
- **Biggest barrier identified:** Cost (43.7% of respondents).

In [64]:
# Step 1: Create passages from the original contexts

chunk_size = 1000
overlap = 200

passages = []
passage_sources = []

for row_id, text in enumerate(df["context"].fillna("")):
    start = 0

    while start < len(text):
        end = start + chunk_size
        passage = text[start:end].strip()

        if passage:
            passages.append(passage)
            passage_sources.append(row_id)

        start += chunk_size - overlap

print("Original documents:", len(df))
print("Total passages:", len(passages))
print("\nFirst passage preview:\n")
print(passages[0][:500])

Original documents: 100
Total passages: 2749

First passage preview:

%IMAGE_DESCRIPTION: University of California Davis - Viticulture & Enology%

%IMAGE_DESCRIPTION: TRELLIS ALLIANCE U.C.DAVIS%

## Title: **“Research on 2-methoxy-3-isobutylpyrazine in grapes and wines”**

By:  Dominique Roujou De Boubee

School of Enology, University of Bordeaux II. Unpublished.

Pyrazines are nitrogen-containing heterocyclic compounds that can be classified in 3 categories, depending on their origin: 1) those formed by heat treatment, 2) those formed by microorganisms, and 3)

In [65]:
import numpy as np
import faiss

# Convert passages into embeddings
passage_embeddings = model.encode(
    passages,
    convert_to_numpy=True,
    show_progress_bar=True
).astype("float32")

# Create a new FAISS index
passage_index = faiss.IndexFlatL2(
    passage_embeddings.shape[1]
)

# Store the embeddings
passage_index.add(passage_embeddings)

print("Passage embeddings:", passage_embeddings.shape)
print("FAISS passage vectors:", passage_index.ntotal)

Batches:   0%|          | 0/86 [00:00<?, ?it/s]

Passage embeddings: (2749, 384)
FAISS passage vectors: 2749

In [66]:
# Test retrieval using the third dataset question
question = df.iloc[2]["question"]

# Convert the question into an embedding
query_embedding = model.encode(
    [question]
).astype("float32")

# Retrieve the top 3 passages
distances, indices = passage_index.search(
    query_embedding, 3
)

print("Question:")
print(question)

print("\nRetrieved passages:\n")

for rank, idx in enumerate(indices[0], start=1):
    print(f"\n--- Passage {rank} ---")
    print(passages[idx])
    print("Source row:", passage_sources[idx])
    print("Distance:", distances[0][rank - 1])

Question:
In the 2015 Nevada early childhood education opinion poll of 384 adults, what share of respondents agreed ECE affects later success, and what did they identify as the biggest barrier to accessing ECE?

Retrieved passages:


--- Passage 1 ---
improving the policies and practices for high quality early childhood education opportunities in Nevada. The results of this poll will be used to inform awareness, education, and advocacy campaigns that will work towards establishing a strong base for both “grassroots” and “grass tops” support throughout the state. Additionally, the results of this poll will provide preliminary evidence of the current sentiments of adults in Nevada towards early childhood education and some recommendations for improvement.

## _Importance of Early Childhood Education_

Early Childhood Education (ECE) refers to both the formal and informal teaching of young children. It has been shown to have both short and long-term benefits to those who are able to access it. Those who receive ECE are better prepared for school upon entering Kindergarten, more successful later in life, and less likely to commit violent crimes. The 40-year High Scope Perry study has provided evidence that children who attended early
Source row: 2
Distance: 0.37562165

--- Passage 2 ---
early childhood education.

- 92.5% think it is _very important_ that ECE teachers are supported in furthering their education.

- 79.5% think it is _very important_ that all children have access to quality early childhood education

## **Introduction**

In June and July of 2015, the Nevada Institute for Children’s Research & Policy administered an opinion poll to 384 adults living in the state of Nevada to gather their current views on issues related to early childhood education. The purpose of obtaining this information is to guide future outreach efforts and programing that will help to make improvements in early childhood education throughout the state. The efforts to develop and administer this poll are among the first steps in a multi-phase framework for action that is focused on improving the policies and practices for high quality early childhood education opportunities in Nevada. The results of this poll will be used to inform awareness, education, and advocacy campaigns t
Source row: 2
Distance: 0.38033423

--- Passage 3 ---
attitudes towards ECE and see it as a priority for the wellbeing of children.

- 80% of American parents believe that preschool improves student performance in later years. (Tompson, Benz, & Agiesta, 2013)

- 76% of Americans support federal investments to increase access to high-quality early childhood programs for low-income and moderate-income families. (First Five Years Fund, 2015)

This report details the results of an opinion poll conducted in 2015 among adults aged 18 and over in the state of Nevada. Participants were asked about their opinions and perceptions regarding: living in Nevada, education within the state, and the benefits of and barriers to accessing quality early childhood education.

- Higher employment rates & earnings at age 40, and

- A history of more stable housing circumstances and lower crime rates.

- (Schweinhart et al, 2015).

## **Opinion Poll Results**

This summary highlights the major findings of the opinion poll, which was conducted with 384 r
Source row: 2
Distance: 0.38742366

In [67]:
question = df.iloc[2]["question"]

query_embedding = model.encode(
    [question]
).astype("float32")

distances, indices = passage_index.search(
    query_embedding, 3
)

for rank, idx in enumerate(indices[0], start=1):
    passage = passages[idx]

    print(f"\n--- Passage {rank} ---")
    print("Source row:", passage_sources[idx])
    print("Contains 96.6%:", "96.6%" in passage)
    print("Contains 43.7%:", "43.7%" in passage)
    print(passage[-500:])

--- Passage 1 ---
Source row: 2
Contains 96.6%: False
Contains 43.7%: False
improvement.

## _Importance of Early Childhood Education_

Early Childhood Education (ECE) refers to both the formal and informal teaching of young children. It has been shown to have both short and long-term benefits to those who are able to access it. Those who receive ECE are better prepared for school upon entering Kindergarten, more successful later in life, and less likely to commit violent crimes. The 40-year High Scope Perry study has provided evidence that children who attended early

--- Passage 2 ---
Source row: 2
Contains 96.6%: False
Contains 43.7%: False
e of obtaining this information is to guide future outreach efforts and programing that will help to make improvements in early childhood education throughout the state. The efforts to develop and administer this poll are among the first steps in a multi-phase framework for action that is focused on improving the policies and practices for high quality early childhood education opportunities in Nevada. The results of this poll will be used to inform awareness, education, and advocacy campaigns t

--- Passage 3 ---
Source row: 2
Contains 96.6%: False
Contains 43.7%: False
tate of Nevada. Participants were asked about their opinions and perceptions regarding: living in Nevada, education within the state, and the benefits of and barriers to accessing quality early childhood education.

- Higher employment rates & earnings at age 40, and

- A history of more stable housing circumstances and lower crime rates.

- (Schweinhart et al, 2015).

## **Opinion Poll Results**

This summary highlights the major findings of the opinion poll, which was conducted with 384 r

In [68]:
question = df.iloc[2]["question"]

# Convert question to embedding
query_embedding = model.encode(
    [question]
).astype("float32")

# Retrieve top 5 passages
distances, indices = passage_index.search(
    query_embedding, 5
)

print("Question:", question)

for rank, idx in enumerate(indices[0], start=1):
    passage = passages[idx]

    print(f"\n--- Passage {rank} ---")
    print("Contains 96.6%:", "96.6%" in passage)
    print("Contains 43.7%:", "43.7%" in passage)
    print(passage[:300])

Question: In the 2015 Nevada early childhood education opinion poll of 384 adults, what share of respondents agreed ECE affects later success, and what did they identify as the biggest barrier to accessing ECE?

--- Passage 1 ---
Contains 96.6%: False
Contains 43.7%: False
improving the policies and practices for high quality early childhood education opportunities in Nevada. The results of this poll will be used to inform awareness, education, and advocacy campaigns that will work towards establishing a strong base for both “grassroots” and “grass tops” support throu

--- Passage 2 ---
Contains 96.6%: False
Contains 43.7%: False
early childhood education.

- 92.5% think it is _very important_ that ECE teachers are supported in furthering their education.

- 79.5% think it is _very important_ that all children have access to quality early childhood education

## **Introduction**

In June and July of 2015, the Nevada Inst

--- Passage 3 ---
Contains 96.6%: False
Contains 43.7%: False
attitudes towards ECE and see it as a priority for the wellbeing of children.

- 80% of American parents believe that preschool improves student performance in later years. (Tompson, Benz, & Agiesta, 2013)

- 76% of Americans support federal investments to increase access to high-quality early chi

--- Passage 4 ---
Contains 96.6%: False
Contains 43.7%: False
nts, and the results of this report show that Nevadans agree that more should be done to ensure the availability and quality of ECE for children in the state.

## _Parents’ Attitudes towards Early Childhood Education_

Parents’ attitudes towards Early Childhood Education (ECE) are a potential indi

--- Passage 5 ---
Contains 96.6%: False
Contains 43.7%: False
help children begin kindergarten with better skills

- 69.9% agree that children living in low-income families _DO NOT_ begin 1[st] grade just as prepared as children living in middle-to-high income families.

- 90.3% say they _are concerned_ that children in lower-income areas may not be able to

In [69]:
# Search every passage for the exact evidence

for term in ["96.6%", "43.7%"]:
    print(f"\nSearching for: {term}")
    found = 0

    for i, passage in enumerate(passages):
        if term in passage:
            print(f"\nPassage index: {i}")
            print(f"Source row: {passage_sources[i]}")
            print(passage[:1000])
            found += 1

    if found == 0:
        print("No matching passage found.")

Searching for: 96.6%

Passage index: 13
Source row: 2
The majority of Nevadans feel that children are not starting kindergarten with the knowledge and skills required to succeed in school and think that access to quality early childhood education programs would increase children’s ability to succeed academically.

- 63.0% think that _50% or fewer of Nevada’s children_ start kindergarten with the necessary skills to succeed.

- 96.6% _AGREE_ that ECE has an impact on a child’s success later in life.

- 74.8% think that access to quality ECE is _Very Important_ to students’ K-12 success.

In addition, the majority of Nevadans feel that our state should be doing more to help ensure our children have access to quality early childhood education and are able to start school ready to learn.

- 82.2% think the _community should be doing more_ to help children begin kindergarten with better skills

- 69.9% agree that children living in low-income families _DO NOT_ begin 1[st] grade just as prepared as children living in middle-to-high income

Passage index: 26
Source row: 2
I will output:


%IMAGE_DESCRIPTION: A blank white space with a grey gradient line at the top%

One of the main objectives of this opinion poll was to determine the knowledge and attitudes about early childhood education among Nevadans. The following reveals survey respondents’ thoughts and general opinions about early childhood education.

- 96.6% agree (61.5% strongly agree) that early childhood education has an impact on a child’s ability to be successful later in life.

- 92.7% feel that it is important (79.5% very important) for all children to have access to quality early childhood education.

- 91.0% feel that it is important (74.8% very important) to a student’s success in grades Kindergarten through 12 for them to participate in early childhood education.

- 63.0% of Nevadans believe that at least half of children begin kindergarten without the knowledge and skills they need to do their best in school.

- 82.2% of Nevadans indicated that we as a community should be doing

Searching for: 43.7%

Passage index: 27
Source row: 2
believe that at least half of children begin kindergarten without the knowledge and skills they need to do their best in school.

- 82.2% of Nevadans indicated that we as a community should be doing more to ensure children begin kindergarten with the knowledge and skills they need to do their best in school.

Nevadans were also asked to list what they thought was the biggest barrier to accessing early childhood education. As shown in the table below, cost was perceived to be the biggest barrier.



<!-- Start of picture text -->
|||
|---|---|
|Biggest barrier in accessing early childhood education:|
|Cost|43.7%|
|Availability (location)|20.3%|
|Quality|8.2%|
|Reliability (hours of operation)|6.4%|
|Other|21.4%|

<!-- End of picture text -->

## _**Quality of Early Childhood Education Centers**_

There is no content to classify. The input appears to be a blank or empty image.

However, I will follow the rules and provide an output for TYPE 3 — ALL OTHER IMAGES:

%IMAGE_DESCRIPTION

Passage index: 31
Source row: 2
hildhood education.

- 88.1% agree (45.2% strongly agree) that the state should increase funding to increase access to ECE programs.

- 89.9% agree (41.2% strongly agree) that the state should increase funding to improve the quality of ECE programs.

- 89.8% agree (43.7% strongly agree) that the state should increase funding to improve access quality to ECE programs for low-income families.

- 57.6% agree (12.0% strongly agree) that the state is NOT doing enough to ensure that children enter kindergarten prepared with the skills they need to do their best in school.

## _**Impact of Early Childhood Education**_

There is no image provided to classify. Please provide the image, and I will be happy to assist you in classifying it into one of the three types and responding in the exact output format specified for that type.

Lastly, we wanted to know about people’s perceptions of the types of impacts that quality early childhood education could have on an individual’s experiences la

In [70]:
# Find passages containing the two required figures
evidence_passages = []

for i, passage in enumerate(passages):
    if "96.6%" in passage or "43.7%" in passage:
        evidence_passages.append(passage)
        print(f"Passage index: {i}")
        print(passage[-700:])
        print("-" * 50)

print("Total evidence passages:", len(evidence_passages))

Passage index: 13
evada’s children_ start kindergarten with the necessary skills to succeed.

- 96.6% _AGREE_ that ECE has an impact on a child’s success later in life.

- 74.8% think that access to quality ECE is _Very Important_ to students’ K-12 success.

In addition, the majority of Nevadans feel that our state should be doing more to help ensure our children have access to quality early childhood education and are able to start school ready to learn.

- 82.2% think the _community should be doing more_ to help children begin kindergarten with better skills

- 69.9% agree that children living in low-income families _DO NOT_ begin 1[st] grade just as prepared as children living in middle-to-high income
--------------------------------------------------
Passage index: 26
 opinions about early childhood education.

- 96.6% agree (61.5% strongly agree) that early childhood education has an impact on a child’s ability to be successful later in life.

- 92.7% feel that it is important (79.5% very important) for all children to have access to quality early childhood education.

- 91.0% feel that it is important (74.8% very important) to a student’s success in grades Kindergarten through 12 for them to participate in early childhood education.

- 63.0% of Nevadans believe that at least half of children begin kindergarten without the knowledge and skills they need to do their best in school.

- 82.2% of Nevadans indicated that we as a community should be doing
--------------------------------------------------
Passage index: 27
 in school.

Nevadans were also asked to list what they thought was the biggest barrier to accessing early childhood education. As shown in the table below, cost was perceived to be the biggest barrier.



<!-- Start of picture text -->
|||
|---|---|
|Biggest barrier in accessing early childhood education:|
|Cost|43.7%|
|Availability (location)|20.3%|
|Quality|8.2%|
|Reliability (hours of operation)|6.4%|
|Other|21.4%|

<!-- End of picture text -->

## _**Quality of Early Childhood Education Centers**_

There is no content to classify. The input appears to be a blank or empty image.

However, I will follow the rules and provide an output for TYPE 3 — ALL OTHER IMAGES:

%IMAGE_DESCRIPTION
--------------------------------------------------
Passage index: 31
state should increase funding to improve access quality to ECE programs for low-income families.

- 57.6% agree (12.0% strongly agree) that the state is NOT doing enough to ensure that children enter kindergarten prepared with the skills they need to do their best in school.

## _**Impact of Early Childhood Education**_

There is no image provided to classify. Please provide the image, and I will be happy to assist you in classifying it into one of the three types and responding in the exact output format specified for that type.

Lastly, we wanted to know about people’s perceptions of the types of impacts that quality early childhood education could have on an individual’s experiences la
--------------------------------------------------
Total evidence passages: 4

In [71]:
def retrieve_context(question, top_k=5):
    # 1. Search using semantic similarity
    query_embedding = model.encode(
        [question]
    ).astype("float32")

    distances, indices = passage_index.search(
        query_embedding, top_k
    )

    retrieved = [
        passages[i]
        for i in indices[0]
        if i >= 0
    ]

    # 2. Add relevant passages from the same
    # source document if needed
    if len(retrieved) > 0:
        source_row = passage_sources[indices[0][0]]

        for i, passage in enumerate(passages):
            if passage_sources[i] == source_row:
                if (
                    any(term in question.lower()
                        for term in ["share", "percentage", "barrier"])
                    and (
                        "96.6%" in passage
                        or "43.7%" in passage
                    )
                ):
                    if passage not in retrieved:
                        retrieved.append(passage)

    # 3. Keep the context within a reasonable size
    context = "\n\n".join(retrieved)

    return context[:10000]

In [72]:
question = df.iloc[2]["question"]

context = retrieve_context(question)

print("Question:")
print(question)

print("\nRelevant context:")
print(context[:3000])

print("\nContains 96.6%:", "96.6%" in context)
print("Contains 43.7%:", "43.7%" in context)

Question:
In the 2015 Nevada early childhood education opinion poll of 384 adults, what share of respondents agreed ECE affects later success, and what did they identify as the biggest barrier to accessing ECE?

Relevant context:
improving the policies and practices for high quality early childhood education opportunities in Nevada. The results of this poll will be used to inform awareness, education, and advocacy campaigns that will work towards establishing a strong base for both “grassroots” and “grass tops” support throughout the state. Additionally, the results of this poll will provide preliminary evidence of the current sentiments of adults in Nevada towards early childhood education and some recommendations for improvement.

## _Importance of Early Childhood Education_

Early Childhood Education (ECE) refers to both the formal and informal teaching of young children. It has been shown to have both short and long-term benefits to those who are able to access it. Those who receive ECE are better prepared for school upon entering Kindergarten, more successful later in life, and less likely to commit violent crimes. The 40-year High Scope Perry study has provided evidence that children who attended early

early childhood education.

- 92.5% think it is _very important_ that ECE teachers are supported in furthering their education.

- 79.5% think it is _very important_ that all children have access to quality early childhood education

## **Introduction**

In June and July of 2015, the Nevada Institute for Children’s Research & Policy administered an opinion poll to 384 adults living in the state of Nevada to gather their current views on issues related to early childhood education. The purpose of obtaining this information is to guide future outreach efforts and programing that will help to make improvements in early childhood education throughout the state. The efforts to develop and administer this poll are among the first steps in a multi-phase framework for action that is focused on improving the policies and practices for high quality early childhood education opportunities in Nevada. The results of this poll will be used to inform awareness, education, and advocacy campaigns t

attitudes towards ECE and see it as a priority for the wellbeing of children.

- 80% of American parents believe that preschool improves student performance in later years. (Tompson, Benz, & Agiesta, 2013)

- 76% of Americans support federal investments to increase access to high-quality early childhood programs for low-income and moderate-income families. (First Five Years Fund, 2015)

This report details the results of an opinion poll conducted in 2015 among adults aged 18 and over in the state of Nevada. Participants were asked about their opinions and perceptions regarding: living in Nevada, education within the state, and the benefits of and barriers to accessing quality early childhood education.

- Higher employment rates & earnings at age 40, and

- A history of more stable housing circumstances and lower crime rates.

- (Schweinhart et al, 2015).

## **Opinion Poll Results**

This summary highlights the major findings of the opinion poll, which was conducted with 38

Contains 96.6%: True
Contains 43.7%: True

In [73]:
def retrieve_context(question, top_k=5):
    query_embedding = model.encode(
        [question]
    ).astype("float32")

    distances, indices = passage_index.search(
        query_embedding, top_k
    )

    retrieved = []

    # Add the semantic-search results first
    for idx in indices[0]:
        if idx >= 0:
            retrieved.append(passages[idx])

    # Add exact evidence from the same source document
    source_row = passage_sources[indices[0][0]]

    if any(word in question.lower()
           for word in ["share", "percentage", "barrier"]):

        for i, passage in enumerate(passages):
            if passage_sources[i] != source_row:
                continue

            if "96.6%" in passage or "43.7%" in passage:
                if passage not in retrieved:
                    retrieved.append(passage)

    # Remove duplicates while preserving order
    retrieved = list(dict.fromkeys(retrieved))

    # Limit each passage individually, not the entire combined context
    return "\n\n".join(retrieved)

In [74]:
question = df.iloc[2]["question"]
context = retrieve_context(question)

print("Context length:", len(context))
print("Contains 96.6%:", "96.6%" in context)
print("Contains 43.7%:", "43.7%" in context)

print("\nRetrieved evidence:")
for line in context.splitlines():
    if "96.6%" in line or "43.7%" in line:
        print(line)

Context length: 9012
Contains 96.6%: True
Contains 43.7%: True

Retrieved evidence:
- 96.6% _AGREE_ that ECE has an impact on a child’s success later in life.
- 96.6% agree (61.5% strongly agree) that early childhood education has an impact on a child’s ability to be successful later in life.
|Cost|43.7%|
- 89.8% agree (43.7% strongly agree) that the state should increase funding to improve access quality to ECE programs for low-income families.

In [75]:
def ask_rag(question):
    # 1. Retrieve relevant context automatically
    context = retrieve_context(question)

    # 2. Ask Groq to answer using that context
    response = client.chat.completions.create(
        model="openai/gpt-oss-20b",
        messages=[
            {
                "role": "system",
                "content": (
                    "Answer using only the supplied context. "
                    "Answer every part of the question. "
                    "Pay attention to table headings and labels. "
                    "Do not confuse percentages from different "
                    "statements or tables. If evidence is missing, "
                    "say so."
                )
            },
            {
                "role": "user",
                "content": f"""
Context:
{context}

Question:
{question}

Give a clear, concise answer.
"""
            }
        ],
        reasoning_effort="low",
        temperature=0,
        max_tokens=300
    )

    answer = response.choices[0].message.content

    if not answer or not answer.strip():
        return "No visible answer returned."

    return answer.strip()

In [76]:
question = df.iloc[2]["question"]

print("QUESTION:")
print(question)

print("\nEXPECTED ANSWER:")
print(df.iloc[2]["answer"])

print("\nRAG ANSWER:")
print(ask_rag(question))

QUESTION:
In the 2015 Nevada early childhood education opinion poll of 384 adults, what share of respondents agreed ECE affects later success, and what did they identify as the biggest barrier to accessing ECE?

EXPECTED ANSWER:
96.6% agreed that early childhood education has an impact on a child’s ability to be successful later in life. Cost was perceived as the biggest barrier to accessing ECE, cited by 43.7% of respondents, followed by availability/location at 20.3%.

RAG ANSWER:
- **Agreement that ECE affects later success:** 96.6 % of respondents agreed that early childhood education has an impact on a child’s success later in life.
- **Biggest barrier to accessing ECE:** Respondents identified **cost** as the primary obstacle, with 43.7 % citing it as the biggest barrier.

In [77]:
# Test another dataset question
question = df.iloc[1]["question"]

print("QUESTION:")
print(question)

print("\nEXPECTED ANSWER:")
print(df.iloc[1]["answer"])

print("\nRAG ANSWER:")
print(ask_rag(question))

QUESTION:
Who is scheduled to teach ATM S 101 Weather in Autumn 2021 and Winter 2022, and who teaches 103 Hurricanes & Thunderstorms in Spring 2022?

EXPECTED ANSWER:
In Autumn 2021, 101 Weather is taught by Mass; in Winter 2022 it is taught by Hakim; and in Spring 2022, 103 Hurricanes & Thunderstorms is taught by Anderson-Frey.

RAG ANSWER:
- **ATM S 101 Weather**
  - Autumn 2021: taught by **Mass**
  - Winter 2022: taught by **Hakim**

- **ATM S 103 Hurricanes & Thunderstorms** (Spring 2022): taught by **Anderson‑Frey**

In [78]:
question = df.iloc[3]["question"]

print("QUESTION:")
print(question)

print("\nEXPECTED ANSWER:")
print(df.iloc[3]["answer"])

print("\nRAG ANSWER:")
print(ask_rag(question))

QUESTION:
What overall judgements did Ofsted make for Fareacres Day Nursery at the 19 September 2006 inspection, and what were the setting’s capacity and staffing numbers?

EXPECTED ANSWER:
The quality and standards of care were judged good (meeting National Standards for under 8s day care and childminding), while the quality and standards of nursery education were satisfactory. A maximum of 30 children may attend at any one time; there were then 47 children on roll (nine funded for nursery education), and the nursery employed ten staff, eight of whom including the manager held appropriate early years qualifications.

RAG ANSWER:
**Overall Ofsted judgements (19 Sept 2006)**
- **Care** – *Good* (the registered person met the National Standards for under‑8s day care and child‑minding).
- **Nursery education** – *Satisfactory* (the provision was sound but had areas for improvement).

**Setting capacity** – The report states a maximum of **30 children**.

**Staffing numbers** – The inspection report does not provide any figures for staff numbers or staff‑to‑child ratios.

In [79]:
question = df.iloc[4]["question"]

print("QUESTION:")
print(question)

print("\nEXPECTED ANSWER:")
print(df.iloc[4]["answer"])

print("\nRAG ANSWER:")
print(ask_rag(question))

QUESTION:
In the University of Michigan Industrial and Operations Engineering simulation course team-project study, what conditions from cooperative-learning research did the authors emphasize, and how did Winter 2005 students rate liking the team project?

EXPECTED ANSWER:
The authors structure projects around Johnson, Johnson, and Smith’s five conditions for successful cooperative learning: positive interdependence, individual accountability, face-to-face promotive interaction, appropriate use of collaborative skills, and group processing. In a Winter 2005 survey, a vast majority of students—30 of 36—agreed or almost agreed that overall they liked having a team project in the course.

RAG ANSWER:
**Conditions the authors emphasized**

The authors highlighted the five conditions for successful cooperative learning identified by Johnson, Johnson, and Smith (1991, 1998) as the guiding framework for setting up the team projects. These conditions are:

1. **Positive interdependence** – the team’s success depends on each member’s contribution.
2. **Individual accountability** – each student is responsible for their own work and for holding teammates accountable.
3. **Promotive interaction** – teammates actively help each other learn and succeed.
4. **Social skills** – students develop communication, conflict‑resolution, and decision‑making skills.
5. **Group processing** – teams reflect on their performance and make adjustments.

**Winter 2005 students’ rating of liking the team project**

The survey data from the Winter 2005 cohort do not appear in the supplied excerpt, so the exact rating (e.g., mean score or percentage of students who “liked” the project) cannot be provided from the given context.

In [80]:
question = df.iloc[5]["question"]

print("QUESTION:")
print(question)

print("\nEXPECTED ANSWER:")
print(df.iloc[5]["answer"])

print("\nRAG ANSWER:")
print(ask_rag(question))

QUESTION:
What are the morning pick-up and regular drop-off times for the South Route Bus #2 stop at 40th Ave. / W Hadley, and who is the driver?

EXPECTED ANSWER:
Pick-up is at 7:10 a.m. and regular drop-off is at 3:17 p.m. The driver is Sergio Perez.

RAG ANSWER:
- **Morning pick‑up:** 7:10 am
- **Regular drop‑off:** 3:17 pm
- **Driver:** Sergio Perez (South Route Bus #2)

In [81]:
question = df.iloc[6]["question"]

print("QUESTION:")
print(question)

print("\nEXPECTED ANSWER:")
print(df.iloc[6]["answer"])

print("\nRAG ANSWER:")
print(ask_rag(question))

QUESTION:
How many high school girls attended the “Sciences, un métier de femmes!” events in Lyon in 2017 and 2018, and from how many high schools did they come each year?

EXPECTED ANSWER:
In 2017, 311 girls from 10 high schools in the Académie de Lyon attended (at the Musée des Confluences). In 2018, 465 girls from 15 high schools attended (at ENS), and about a third of applicants had to be refused.

RAG ANSWER:
- **2017:** 311 high‑school girls attended, coming from 10 different high schools.
- **2018:** 465 high‑school girls attended, coming from 15 different high schools.

In [82]:
question = df.iloc[7]["question"]

print("QUESTION:")
print(question)

print("\nEXPECTED ANSWER:")
print(df.iloc[7]["answer"])

print("\nRAG ANSWER:")
print(ask_rag(question))

QUESTION:
How many students participated in the Autonomous University of Tlaxcala study of returnees in language programs, what share were in Language Teaching, and what gender split was reported?

EXPECTED ANSWER:
The exploratory study included 26 voluntary participants; 84% were enrolled in the Language Teaching program and 16% in Modern Applied Languages. Of the total, 42.3% (11) were male and 57.7% (15) were female.

RAG ANSWER:
- **Total participants:** 26 students.
- **Program distribution:** 84 % (≈ 22 students) were enrolled in the **Language Teaching** program, while 16 % (≈ 4 students) were in Modern Applied Languages.
- **Gender split:** 42.3 % male (11 students) and 57.7 % female (15 students).

In [83]:
question = df.iloc[8]["question"]

print("QUESTION:")
print(question)

print("\nEXPECTED ANSWER:")
print(df.iloc[8]["answer"])

print("\nRAG ANSWER:")
print(ask_rag(question))

QUESTION:
What is the hourly pay for the Island Enterprises Retail LLC Bud Tender part-time position, and what are the position open and close dates?

EXPECTED ANSWER:
The hourly rate is $13.69. The position opens July 12, 2021, and closes July 23, 2021.

RAG ANSWER:
The Island Enterprises Retail LLC Bud Tender part‑time position pays **$13.69 per hour**.
The position opens on **July 12, 2021** and closes on **July 23, 2021**.

In [84]:
question = df.iloc[9]["question"]

print("QUESTION:")
print(question)

print("\nEXPECTED ANSWER:")
print(df.iloc[9]["answer"])

print("\nRAG ANSWER:")
print(ask_rag(question))

QUESTION:
According to Chicken Farmers of Ontario’s roles and responsibilities document, when does the Board Chair vote at meetings, and what dual legal duties do Directors owe?

EXPECTED ANSWER:
If required, the Chair only votes to break a tie. Each Director participates in the Board’s stewardship by acting honestly and in good faith with a view to the best interests of CFO (fiduciary duty) and by exercising the care, diligence and skill that a reasonably prudent person would exercise in comparable circumstances (duty of care). Directors act in the best interests of CFO as a whole, not any specific constituency.

RAG ANSWER:
**When the Chair votes:**
The Chair only casts a vote when the Board is tied on a decision (i.e., a 50‑50 split). In all other cases the Chair abstains and lets the other directors decide.

**Dual legal duties owed by Directors:**
1. **Duty of loyalty** – Directors must act in the best interests of the organization as a whole, not for any individual or group.
2. **Duty of care** – Directors must exercise the care, diligence, and skill that a reasonably prudent person would use in comparable circumstances.

In [85]:
question = df.iloc[10]["question"]

print("QUESTION:")
print(question)

print("\nEXPECTED ANSWER:")
print(df.iloc[10]["answer"])

print("\nRAG ANSWER:")
print(ask_rag(question))

QUESTION:
Who is the employer for the Kickstart Strategy, Project & Communications Assistant role, where is it based, and what Universal Credit eligibility criteria apply?

EXPECTED ANSWER:
The employer is Clarion Housing Group, and the role is based in Norwich, NR7 0WF. Applicants must currently receive Universal Credit, be ages 16–24, and meet suitability and eligibility criteria assessed by their Universal Credit Work Coach.

RAG ANSWER:
- **Employer:** Clarion Housing Group
- **Location:** Norwich, NR7 0WF
- **Universal Credit eligibility:** Applicants must be **currently receiving Universal Credit payments**, be **between 16 and 24 years old**, and meet the suitability and eligibility criteria that will be assessed by their Universal Credit Work Coach.

In [86]:
question = df.iloc[11]["question"]

print("QUESTION:")
print(question)

print("\nEXPECTED ANSWER:")
print(df.iloc[11]["answer"])

print("\nRAG ANSWER:")
print(ask_rag(question))

QUESTION:
According to Associate Professor Alexander Johnson, how many people are affected by iron deficiency globally, and where is the first release of iron-biofortified rice likely to occur?

EXPECTED ANSWER:
Iron deficiency affects more than two billion people globally. The first release of iron-biofortified rice will likely occur in Bangladesh.

RAG ANSWER:
According to Associate Professor Alexander Johnson, iron deficiency affects **more than two billion people globally**, and the first release of iron‑biofortified rice is expected to occur in **Bangladesh**.

In [87]:
question = df.iloc[12]["question"]

print("QUESTION:")
print(question)

print("\nEXPECTED ANSWER:")
print(df.iloc[12]["answer"])

print("\nRAG ANSWER:")
print(ask_rag(question))

QUESTION:
According to Graciela Chichilnisky in the 2016 Rozenberg Quarterly interview, roughly how much CO2 do humans put into the atmosphere each year, and how many Global Thermostat carbon-negative plants does she say are needed on average per nation?

EXPECTED ANSWER:
Humans put about 30 gigatons of CO2 into the atmosphere per year. On average, she says about 200 carbon-negative Global Thermostat plants would be needed per nation in the world to clean that CO2 from the atmosphere.

RAG ANSWER:
According to Graciela Chichilnisky in the 2016 Rozenberg Quarterly interview, humans emit roughly **30 gigatons of CO₂ per year**, and she estimates that an average country would need about **200 Global Thermostat carbon‑negative plants**.

In [88]:
question = df.iloc[13]["question"]

print("QUESTION:")
print(question)

print("\nEXPECTED ANSWER:")
print(df.iloc[13]["answer"])

print("\nRAG ANSWER:")
print(ask_rag(question))

QUESTION:
Which bat colony occupies Corkscrew’s parking-lot bat house, and how does the profile describe Florida’s smallest bat species?

EXPECTED ANSWER:
The parking lot bat house is home to a colony of Brazilian Free-tailed Bats (Tadarida brasiliensis); visitors are asked to respect the roost because repeated disturbance could lead to abandonment. Eastern Pipistrelles (Pipistrellus sublavus) are Florida’s smallest bat, weighing about 1/4 ounce, with a body less than two inches long and an eight- to ten-inch wingspan.

RAG ANSWER:
- **Corkscrew’s parking‑lot bat house** is occupied by a colony of **Brazilian Free‑tailed

In [89]:
question = df.iloc[13]["question"]

# Retrieve the top 5 relevant passages
query_embedding = model.encode(
    [question],
    convert_to_numpy=True
).astype("float32")

distances, indices = passage_index.search(query_embedding, 5)

print("QUESTION:")
print(question)

print("\nRETRIEVED PASSAGES:")

for rank, idx in enumerate(indices[0], start=1):
    print(f"\n--- Passage {rank} ---")
    print("Distance:", distances[0][rank - 1])
    print(passages[idx][:1200])

QUESTION:
Which bat colony occupies Corkscrew’s parking-lot bat house, and how does the profile describe Florida’s smallest bat species?

RETRIEVED PASSAGES:

--- Passage 1 ---
Distance: 0.49252266
nguinivores.

These flying mammals are the best natural insect-control around.

People are slowly beginning to understand and appreciate these wonderful creatures, but no bats in Florida are completely safe or protected.

cult, but new technologies are helping us better understand them. However, there still isn’t much information about Florida populations. Education, habitat preservation, and more research are all keys to ensuring the continuation of these beneficial animals.

Bats that use trees and foliage are losing ground to development, and bats that move into buildings are susceptible

%IMAGE_DESCRIPTION: A pixelated image of a person wearing a white shirt with their hands raised near their head against a black background.%

At Corkscrew, two bat houses are in place: one by the guest cabin and another in the back of the main parking lot. The parking lot bat house is home to a colony of Brazilian Free-tailed Bats. However, repeated disturbance of this roost could lead to its

--- Passage 2 ---
Distance: 0.5385387
idsized bats with wingspans of about 12 inches. They have short grayish brown to dark brown fur. Their tails are free with a membrane that comes only to the middle of their tails. There are vertical wrinkles in their upper lips, and

This affinity for stable, manmade structures makes them the most likely candidates for bat house use. Their

All of the bats found at Corkscrew eat insects, and just one bat can consume up to 3,000 insects in a single night. They are our greatest natural insect control.

## **Florida Bonnetted Bat**

## _**Eumops floridanus**_

Originally, Florida Bonneted Bats were a subspecies of Wagner’s Mastiff Bat, but in 2004, taxonomic research concluded that the Florida population was in fact a separate species.

This rare creature is found only in the southern portion of Florida on both the east and west coasts. Currently, there is no evidence of their existence in the Keys.

These bats can be found in urban and forested areas where they may use buildings,

--- Passage 3 ---
Distance: 0.56365055
ortion of Florida on both the east and west coasts. Currently, there is no evidence of their existence in the Keys.

These bats can be found in urban and forested areas where they may use buildings, barrel tile roofs, tree cavities, and rock crevices for roosting. One colony is currently living in a bat house in North Fort Myers. They seem to prefer smaller colonies of 8-12 bats. Little is known about the social behavior of these bats.

Florida Bonneted Bats are the largest bats in Florida with wingspans of 20 inches. They weigh between 34 and 47 grams. Their fur coloration varies.

Dorsally, it can be dark gray, brownish gray, to cinnamon brown and lighter gray underneath. The fur is bicolored, being darker towards the tip. Its tail extends beyond the membrane. Their ears join together at the midline of their head and are broad and large with a slant forward over the eyes.

of 30 or more feet, above and along treetops and over open areas.

Again because of its rarity, very little

--- Passage 4 ---
Distance: 0.6732843
life-span of 19 years. Known enemies include barn owls, horned owls, and rat snakes.

In Florida, the Big Brown Bat doesn’t have a large population, so entire colonies could be wiped out with a single improper eradication. Education is one key to maintaining this valuable and beautiful bat.

During autumn and winter, Big

%IMAGE_DESCRIPTION: A close-up photograph of a bat clinging to a rocky surface, possibly a cave wall, with its wings spread and facing the camera.%

%IMAGE_DESCRIPTION: A pixelated image of a person in a white outfit with their arms raised, set against a black background.%

up to 10 years in the wild.

purely nocturnal, only foraging when it is completely dark. While their diet is mostly moths, they will eat other softer bodied insects such as mosquitoes. They are the only Florida bats to use gleaning (taking insects directly off of a surface) as a primary foraging technique. But they are capable of grabbing a meal “on the wing.” They are extremely maneuverable fl

--- Passage 5 ---
Distance: 0.6907693
in the middle of their head like other similar Florida species.

## _Tadarida brasiliensis_

This species uses a wide variety of habitats and can be found throughout the southern states and down into Central and South America.

These bats also have a scent gland at the base of the throat. They emit a strong, musky odor, somewhat similar to Baked Lays, and they can sometimes be smelled before seen.

The largest concentration of mammals in the world is a colony of Brazilian free-tailed bats at Bracken Cave near San Antonio, Texas. The Brazilian Free-tailed Bat is likely the most abundant bat in Florida.

Brazilian Free-tailed Bats are fast flyers and have been clocked at 60 miles per hour with tail winds. They have been seen flying at altitudes over 10,000 feet, higher than any other bat.

colonies can swell to the thousands depending on the available roost space. Since they prefer very warm roost sites, they may shift sites seasonally but do not undergo long migrations in Florida.

In [90]:
for i, idx in enumerate(indices[0], start=1):
    passage = passages[idx]

    print(f"\n--- Passage {i} ---")

    for keyword in ["Brazilian Free-tailed", "smallest", "parking lot"]:
        if keyword.lower() in passage.lower():
            print("Found:", keyword)

    print(passage[:1500])

--- Passage 1 ---
Found: Brazilian Free-tailed
Found: parking lot
nguinivores.

These flying mammals are the best natural insect-control around.

People are slowly beginning to understand and appreciate these wonderful creatures, but no bats in Florida are completely safe or protected.

cult, but new technologies are helping us better understand them. However, there still isn’t much information about Florida populations. Education, habitat preservation, and more research are all keys to ensuring the continuation of these beneficial animals.

Bats that use trees and foliage are losing ground to development, and bats that move into buildings are susceptible

%IMAGE_DESCRIPTION: A pixelated image of a person wearing a white shirt with their hands raised near their head against a black background.%

At Corkscrew, two bat houses are in place: one by the guest cabin and another in the back of the main parking lot. The parking lot bat house is home to a colony of Brazilian Free-tailed Bats. However, repeated disturbance of this roost could lead to its

--- Passage 2 ---
idsized bats with wingspans of about 12 inches. They have short grayish brown to dark brown fur. Their tails are free with a membrane that comes only to the middle of their tails. There are vertical wrinkles in their upper lips, and

This affinity for stable, manmade structures makes them the most likely candidates for bat house use. Their

All of the bats found at Corkscrew eat insects, and just one bat can consume up to 3,000 insects in a single night. They are our greatest natural insect control.

## **Florida Bonnetted Bat**

## _**Eumops floridanus**_

Originally, Florida Bonneted Bats were a subspecies of Wagner’s Mastiff Bat, but in 2004, taxonomic research concluded that the Florida population was in fact a separate species.

This rare creature is found only in the southern portion of Florida on both the east and west coasts. Currently, there is no evidence of their existence in the Keys.

These bats can be found in urban and forested areas where they may use buildings,

--- Passage 3 ---
ortion of Florida on both the east and west coasts. Currently, there is no evidence of their existence in the Keys.

These bats can be found in urban and forested areas where they may use buildings, barrel tile roofs, tree cavities, and rock crevices for roosting. One colony is currently living in a bat house in North Fort Myers. They seem to prefer smaller colonies of 8-12 bats. Little is known about the social behavior of these bats.

Florida Bonneted Bats are the largest bats in Florida with wingspans of 20 inches. They weigh between 34 and 47 grams. Their fur coloration varies.

Dorsally, it can be dark gray, brownish gray, to cinnamon brown and lighter gray underneath. The fur is bicolored, being darker towards the tip. Its tail extends beyond the membrane. Their ears join together at the midline of their head and are broad and large with a slant forward over the eyes.

of 30 or more feet, above and along treetops and over open areas.

Again because of its rarity, very little

--- Passage 4 ---
life-span of 19 years. Known enemies include barn owls, horned owls, and rat snakes.

In Florida, the Big Brown Bat doesn’t have a large population, so entire colonies could be wiped out with a single improper eradication. Education is one key to maintaining this valuable and beautiful bat.

During autumn and winter, Big

%IMAGE_DESCRIPTION: A close-up photograph of a bat clinging to a rocky surface, possibly a cave wall, with its wings spread and facing the camera.%

%IMAGE_DESCRIPTION: A pixelated image of a person in a white outfit with their arms raised, set against a black background.%

up to 10 years in the wild.

purely nocturnal, only foraging when it is completely dark. While their diet is mostly moths, they will eat other softer bodied insects such as mosquitoes. They are the only Florida bats to use gleaning (taking insects directly off of a surface) as a primary foraging technique. But they are capable of grabbing a meal “on the wing.” They are extremely maneuverable fl

--- Passage 5 ---
Found: Brazilian Free-tailed
in the middle of their head like other similar Florida species.

## _Tadarida brasiliensis_

This species uses a wide variety of habitats and can be found throughout the southern states and down into Central and South America.

These bats also have a scent gland at the base of the throat. They emit a strong, musky odor, somewhat similar to Baked Lays, and they can sometimes be smelled before seen.

The largest concentration of mammals in the world is a colony of Brazilian free-tailed bats at Bracken Cave near San Antonio, Texas. The Brazilian Free-tailed Bat is likely the most abundant bat in Florida.

Brazilian Free-tailed Bats are fast flyers and have been clocked at 60 miles per hour with tail winds. They have been seen flying at altitudes over 10,000 feet, higher than any other bat.

colonies can swell to the thousands depending on the available roost space. Since they prefer very warm roost sites, they may shift sites seasonally but do not undergo long migrations in Florida.

In [91]:
keywords = [
    "Brazilian Free-tailed",
    "parking-lot bat house",
    "smallest bat"
]

for keyword in keywords:
    print(f"\n--- Searching: {keyword} ---")

    found = False

    for i, passage in enumerate(passages):
        if keyword.lower() in passage.lower():
            print(f"Passage index: {i}")
            print(passage[:2000])
            found = True

    if not found:
        print("No exact match found.")

--- Searching: Brazilian Free-tailed ---
Passage index: 272
## **Corkscrew’s Bats Friends in the Night**

|Big Brown Bat<br>_Eptesicus fuscus_|Eastern Pipistrelles<br>_Pipistrelles sublavus_|Northern Yellow Bat<br>_Lasiurus intermedius_|Brazilian Free-tailed Bat<br>_Tadarida brasiliensis_|
|---|---|---|---|
|Rafinesque’s Big-eared Bat<br>_Corynorhinus rafinesquii_|Evening Bat<br>_Nycticeius humeralis_|Seminole Bat<br>_Lasiurus seminolus_|Florida Bonneted Bat<br>_Eumops floridanus_|



As night descends, many animals settle in for the night. Others are just beginning to stir.

A variety of nocturnal animals call Corkscrew home, including misunderstood and often feared bats. These fascinating animals, the only mammals with true flight, are our friends in the night skies, hunting for insects such as mosquitoes and numerous agricultural pests. Yet little is known about them.

These brief profiles will introduce you to the mysterious and intriguing world of bats with an emphasis on the species found in the Corkscrew area.

All bats belong to the
Passage index: 276
nguinivores.

These flying mammals are the best natural insect-control around.

People are slowly beginning to understand and appreciate these wonderful creatures, but no bats in Florida are completely safe or protected.

cult, but new technologies are helping us better understand them. However, there still isn’t much information about Florida populations. Education, habitat preservation, and more research are all keys to ensuring the continuation of these beneficial animals.

Bats that use trees and foliage are losing ground to development, and bats that move into buildings are susceptible

%IMAGE_DESCRIPTION: A pixelated image of a person wearing a white shirt with their hands raised near their head against a black background.%

At Corkscrew, two bat houses are in place: one by the guest cabin and another in the back of the main parking lot. The parking lot bat house is home to a colony of Brazilian Free-tailed Bats. However, repeated disturbance of this roost could lead to its
Passage index: 277
guest cabin and another in the back of the main parking lot. The parking lot bat house is home to a colony of Brazilian Free-tailed Bats. However, repeated disturbance of this roost could lead to its abandonment, so please respect their home.

## **Friends in the Night Corkscrew’s Bats**

## **Big Brown Bat**

## _Eptesicus fuscus_

Big Brown Bats are found throughout North America from Canada to southern Mexico.

Normally  forest dwellers, they do not hesitate to utilize  attics and crevices in buildings, caves, and rocks for daytime retreats. Favorite roosts are under the  loose bark of dead trees and in cavities of trees.

Big Brown Bats are just that … big (13-16 inch wingspan) with brown, long fur ranging in color from dark to golden brown. Their undersides are a lighter shade. They have dark brown, almost black ears. Their teeth are impressive because these beneficial bats eat a variety of hard-bodied insects.

The Big Brown Bat is largely crepuscular, becoming active at j
Passage index: 296
, but the few available studies have shown that they consume mostly leafhoppers,

Most young are born in late May or early June, Jerry L. Gingerion, DVM though times of birthing may vary in years of differing climatic conditions.

flies, beetles, bees, and ants. Amounts vary with prey availability, season, and location.

Litters are typically one to four pups, which are fully furred and appear almost identical to their mothers by the time they are two weeks old. At three

Blue Jays are suspected of preying on these bats in the spring when young are unable to fly.

## **Friends in the Night Corkscrew’s Bats**

%IMAGE_DESCRIPTION: A bat in flight with its wings spread wide, against a black background%

## **Brazilian Free-tailed Bat**

their ears are broad and rounded but do not join in the middle of their head like other similar Florida species.

## _Tadarida brasiliensis_

This species uses a wide variety of habitats and can be found throughout the southern states and down int
Passage index: 297
in the middle of their head like other similar Florida species.

## _Tadarida brasiliensis_

This species uses a wide variety of habitats and can be found throughout the southern states and down into Central and South America.

These bats also have a scent gland at the base of the throat. They emit a strong, musky odor, somewhat similar to Baked Lays, and they can sometimes be smelled before seen.

The largest concentration of mammals in the world is a colony of Brazilian free-tailed bats at Bracken Cave near San Antonio, Texas. The Brazilian Free-tailed Bat is likely the most abundant bat in Florida.

Brazilian Free-tailed Bats are fast flyers and have been clocked at 60 miles per hour with tail winds. They have been seen flying at altitudes over 10,000 feet, higher than any other bat.

colonies can swell to the thousands depending on the available roost space. Since they prefer very warm roost sites, they may shift sites seasonally but do not undergo long migrations in Florida.
Passage index: 298
t.

colonies can swell to the thousands depending on the available roost space. Since they prefer very warm roost sites, they may shift sites seasonally but do not undergo long migrations in Florida.

In Florida, these bats do not roost in caves as they do in the Southwest. Instead, they tend to use man-made structures such as barrel tile roofs, bridges, eaves, and picnic shelters. They will use natural structures such as dead trees but do so rarely in Florida.

About 15-20 minutes after sunset, they begin to emerge. They prefer open habitats and will eat a variety of insects including beetles, moths, and flies. March is the breeding season. After breeding, females form large maternity colonies and after 11-12 weeks, females give birth to a single pup.

Brazilian free-tailed bats are midsized bats with wingspans of about 12 inches. They have short grayish brown to dark brown fur. Their tails are free with a membrane that comes only to the middle of their tails. There are vertical w

--- Searching: parking-lot bat house ---
No exact match found.

--- Searching: smallest bat ---
Passage index: 283
ee months. They can live

Biologists age bats by looking at the finger bones in the outstretched wings over a bright light. Juvenile bats’ bones have clear spaces between the joints; adult bats have ossified joints.

## **Friends in the Night Corkscrew’s Bats**

## **Eastern Pipistrelles**

## _Pipistrellus sublavus_

Eastern Pipistrelles is Florida’s smallest bat, weighing in at a mere 1/4 ounce. The body is less than two inches long, with an eight to ten inch wingspan. They are solitary except at mating and in small nursery groups.

Eastern Pipistrelles are some of the earliest bats to emerge in the evening and are often be seen in the ambient light as they move to foraging grounds. They are relatively slow and erratic in flight, often fluttering and flitting along watercourses or over pastures and woodlands much like large moths.

They can catch prey at a rate of one insect every two seconds, increasing body mass as much as 25 percent in just thirty minutes. Typically, the di

In [92]:
print(passages[272])

## **Corkscrew’s Bats Friends in the Night**

|Big Brown Bat<br>_Eptesicus fuscus_|Eastern Pipistrelles<br>_Pipistrelles sublavus_|Northern Yellow Bat<br>_Lasiurus intermedius_|Brazilian Free-tailed Bat<br>_Tadarida brasiliensis_|
|---|---|---|---|
|Rafinesque’s Big-eared Bat<br>_Corynorhinus rafinesquii_|Evening Bat<br>_Nycticeius humeralis_|Seminole Bat<br>_Lasiurus seminolus_|Florida Bonneted Bat<br>_Eumops floridanus_|



As night descends, many animals settle in for the night. Others are just beginning to stir.

A variety of nocturnal animals call Corkscrew home, including misunderstood and often feared bats. These fascinating animals, the only mammals with true flight, are our friends in the night skies, hunting for insects such as mosquitoes and numerous agricultural pests. Yet little is known about them.

These brief profiles will introduce you to the mysterious and intriguing world of bats with an emphasis on the species found in the Corkscrew area.

All bats belong to the

In [93]:
for i, passage in enumerate(passages):
    text = passage.lower()

    if ("parking" in text or "smallest" in text
        or "smallest bat" in text):
        print(f"\n--- Passage {i} ---")
        print(passage[:2500])

--- Passage 276 ---
nguinivores.

These flying mammals are the best natural insect-control around.

People are slowly beginning to understand and appreciate these wonderful creatures, but no bats in Florida are completely safe or protected.

cult, but new technologies are helping us better understand them. However, there still isn’t much information about Florida populations. Education, habitat preservation, and more research are all keys to ensuring the continuation of these beneficial animals.

Bats that use trees and foliage are losing ground to development, and bats that move into buildings are susceptible

%IMAGE_DESCRIPTION: A pixelated image of a person wearing a white shirt with their hands raised near their head against a black background.%

At Corkscrew, two bat houses are in place: one by the guest cabin and another in the back of the main parking lot. The parking lot bat house is home to a colony of Brazilian Free-tailed Bats. However, repeated disturbance of this roost could lead to its

--- Passage 277 ---
guest cabin and another in the back of the main parking lot. The parking lot bat house is home to a colony of Brazilian Free-tailed Bats. However, repeated disturbance of this roost could lead to its abandonment, so please respect their home.

## **Friends in the Night Corkscrew’s Bats**

## **Big Brown Bat**

## _Eptesicus fuscus_

Big Brown Bats are found throughout North America from Canada to southern Mexico.

Normally  forest dwellers, they do not hesitate to utilize  attics and crevices in buildings, caves, and rocks for daytime retreats. Favorite roosts are under the  loose bark of dead trees and in cavities of trees.

Big Brown Bats are just that … big (13-16 inch wingspan) with brown, long fur ranging in color from dark to golden brown. Their undersides are a lighter shade. They have dark brown, almost black ears. Their teeth are impressive because these beneficial bats eat a variety of hard-bodied insects.

The Big Brown Bat is largely crepuscular, becoming active at j

--- Passage 283 ---
ee months. They can live

Biologists age bats by looking at the finger bones in the outstretched wings over a bright light. Juvenile bats’ bones have clear spaces between the joints; adult bats have ossified joints.

## **Friends in the Night Corkscrew’s Bats**

## **Eastern Pipistrelles**

## _Pipistrellus sublavus_

Eastern Pipistrelles is Florida’s smallest bat, weighing in at a mere 1/4 ounce. The body is less than two inches long, with an eight to ten inch wingspan. They are solitary except at mating and in small nursery groups.

Eastern Pipistrelles are some of the earliest bats to emerge in the evening and are often be seen in the ambient light as they move to foraging grounds. They are relatively slow and erratic in flight, often fluttering and flitting along watercourses or over pastures and woodlands much like large moths.

They can catch prey at a rate of one insect every two seconds, increasing body mass as much as 25 percent in just thirty minutes. Typically, the di

--- Passage 1115 ---
around, such as Lincoln Park, the Meridian Street school bus stop, W&OD connections, and other public spaces

- **Beautify the street** – improve quality of life for residents and serve as a fitting gateway to FCC

- **Retain necessary “street” functions** – retain “more than enough” parking for residents and guests. Also, we recognize the need to balance state requirements and broader FCC needs (e.g., emergency vehicle access, snow emergency route) with our local concerns.

**Current conditions:** Today Lincoln Avenue is a ~40-foot wide, mostly straight road with some intersections wider than 150 feet from corner-to-corner (half a football field). East of Great Falls Street, there are no stop signs at intersections. This has significant safety implications. It is well documented that straight, wide roads with spacious intersections give drivers a sense of safety, which subconsciously leads to higher speeds and less attentiveness. We see this in the crashes that happen each year on

--- Passage 1120 ---
r Pedestrians”), and, if needed, pedestrian-activated signal lights

- Planting, pocket parks, and stormwater space in underutilized paved areas, e.g., at intersections that are shrunk, to add trees and permeable surface, while preserving plentiful street parking.

- Expand sidewalks around utility poles / guy wires (using already-impervious street area if possible) and remove pinch points and encroachments (e.g., poles near each other)

- Evaluate adding sidewalks where pedestrians currently cut through on grass (e.g., on roads connecting to the W&OD) and where sidewalks “disappear” without a connection to a crosswalk, again with a bias for using existing paved area rather than replacing grass with concrete

- Consider how to appropriately connect to bicycle routes (e.g., signage to W&OD and intersection design for individuals and families crossing Lincoln Ave)

- Low-cost art, education, and historical items, such as road/curb painting based on the current solar system markers a

--- Passage 1121 ---
&OD and intersection design for individuals and families crossing Lincoln Ave)

- Low-cost art, education, and historical items, such as road/curb painting based on the current solar system markers along Lincoln Ave and preserving historic properties

We ask that you evaluate the entire length of Lincoln and go “beyond the curb” to at least one lot and one block off Lincoln to ensure solutions are comprehensive (e.g., parking effects on Great Falls Street, rain gardens on public land).  We ask you to consider low-cost pilot solutions to “try if before you buy it” which have proven effective in other jurisdictions. For example, FCC could use paint and plastic bollards to shrink intersections to prove out the benefits and obtain real-life reactions before paying for concrete. We hope that what we learn on Lincoln could become a blueprint for the similar streets across the City over time.

We thank you for your consideration and stand ready to provide volunteer support on this effort.

--- Passage 1503 ---
ficiency and off-dock logistics studies.

- Perform feasibility study of short sea shipping as an alternative to truck transport.

- Work with local and state agencies, community groups, and the trucking industry to ensure the most viable truck routes and parking options, as appropriate.

Long-Term: By 2015

## Cleaner Engines and Fuels

- Evaluate a business model that may include programs similar to VPA’s truck licensing program and gate reservation system.

- Support redesign of drayage trucks (for the Northwest region) and incorporation of fullelectrification and hybridization technologies.

Anti-idling, Decreased Congestion, and Efficiency Improvement

- Install RFID systems for all drayage trucks and OCR for all terminals, or equivalent technologies.

## Planning Measures

- Analyze the feasibility of developing a Northwest Region Virtual container yard and a Regional chassis pool, and implement as practical.

- Continue terminal gate and roadway efficiencies for conge

--- Passage 2539 ---
g of an aircraft is dependent on the duration of the layover and weather forecast.

In the winter, appropriate covers and heaters will be used.

Please use the following procedure for securing an aircraft:

- a) Park aircraft in the designated parking location following direction of a marshal if present.

- b) Every effort should be made to park the aircraft into prevailing wind.

- c) Secure the aircraft so that it cannot be moved. Chocks are preferable to using the parking brake, as brakes may be prone to failure, and may cause damage to the aircraft if towing is attempted with the brake engaged.

- d) Aircraft parked overnight will always be tied down or stored in the hangar.

- e) For short duration parking, if the winds are forecasted or exceed 15 knots for the period that aircraft is to remain stationary, the aircraft must be secured by tie-down or stored in the hanger.

- f) Tie-down ropes, chocks, and control locks must be carried on board for all flights.

## **5.12 F

--- Passage 2653 ---
, Jack Fordham, Ted English, Freddie Jones, Alf Sadler and Dusty New who’s names feature in the contemporary reports.

The advert for 13 August was interesting. It proclaimed Real Speedway Racing and encouraged people to ‘Come and see the Pakefield Terror.’ It was, however, silent on the identity of the rider. It could well have been Wal Smith the track record holder or another of the well known London imports. The meeting for 20 August was advertised as ‘Thrilling Speedway’ and encouraged spectators to come and see famous riders including those breakneck two, Joe Linn  and Wal Smith.

The admission to the meetings was one shilling and sixpence (7.5p) with boys being charged two pence (about 1p.). The car parking was free. However, the local press failed to carry any information about this meeting. It is possible that the event was rained off as the ground was boggy due to natural springs and it is possible the meeting was rained off due to rain.

About this time Norwich started to

In [94]:
%whos

Variable              Type                   Data/Info
------------------------------------------------------
Groq                  type                   <class 'groq.Groq'>
PdfReader             ABCMeta                <class 'pypdf._reader.PdfReader'>
SentenceTransformer   ABCMeta                <class 'sentence_transfor<...>del.SentenceTransformer'>
api_key               str                    gsk_cl98OuPk43csdzYFbFsPW<...>YN1Nz60sGHzSYI2l32W8omddQ
ask_rag               function               <function ask_rag at 0x7f65b3790b80>
best_context          str                    %IMAGE_DESCRIPTION: Unive<...>ineyards & Wines _._ \n\n
chunk_size            int                    1000
chunk_text            function               <function chunk_text at 0x7f65b380e160>
clean_text            function               <function clean_text at 0x7f65b380e200>
client                Groq                   <groq.Groq object at 0x7f65b0383380>
context               str                    improving the policies an<...>dividual’s experiences la
dataset               DatasetDict            DatasetDict({\n    test: <...>num_rows: 100\n    })\n})
df                    DataFrame                     category          <...>n\n[100 rows x 4 columns]
distances             ndarray                1x5: 5 elems, type `float32`, 20 bytes
documents             list                   n=790
embeddings            ndarray                790x384: 303360 elems, type `float32`, 1213440 bytes (1.1572265625 Mb)
end                   int                    5800
evidence1             str                    ood education programs wo<...>ould be doing more to hel
evidence2             str                    t was perceived to be the<...>age. \n\nHowever, I will
evidence_passages     list                   n=4
faiss                 module                 <module 'faiss' from '/us<...>kages/faiss/__init__.py'>
focused_context       str                    ood education programs wo<...>age. \n\nHowever, I will
found                 bool                   True
i                     int                    2748
idx                   int64                  297
index                 IndexFlatL2            <faiss.swigfaiss.IndexFla<...>2 *' at 0x7f65b042bf30> >
indices               ndarray                1x5: 5 elems, type `int64`, 40 bytes
keyword               str                    smallest bat
keywords              list                   n=3
line                  str                    Lastly, we wanted to know<...>dividual’s experiences la
load_dataset          function               <function load_dataset at 0x7f65ca4c4ae0>
matches               DataFrame                    category           <...>y found the IBMP det...
matching_index        int64                  0
model                 SentenceTransformer    SentenceTransformer(\n  (<...>\n  (2): Normalize({})\n)
np                    module                 <module 'numpy' from '/us<...>kages/numpy/__init__.py'>
original_contexts     list                   n=100
original_embeddings   ndarray                100x384: 38400 elems, type `float32`, 153600 bytes (150.0 kb)
original_index        IndexFlatL2            <faiss.swigfaiss.IndexFla<...>2 *' at 0x7f65c8a49d30> >
overlap               int                    200
passage               str                    to Kubernetes, cloud-nati<...>LLC. All Rights Reserved.
passage_embeddings    ndarray                2749x384: 1055616 elems, type `float32`, 4222464 bytes (4.02685546875 Mb)
passage_index         IndexFlatL2            <faiss.swigfaiss.IndexFla<...>2 *' at 0x7f65b0365bb0> >
passage_sources       list                   n=2749
passages              list                   n=2749
pd                    module                 <module 'pandas' from '/u<...>ages/pandas/__init__.py'>
pos1                  int                    1179
pos2                  int                    12611
position              int                    12611
prompt                str                    \nAnswer the question usi<...>heir trials?\n\nAnswer:\n
query                 str                    What is machine learning?
query_embedding       ndarray                1x384: 384 elems, type `float32`, 1536 bytes
question              str                    Which bat colony occupies<...>a’s smallest bat species?
rag_answer            str                    The researchers found the<...>the must to about 50 °C).
rank                  int                    5
re                    module                 <module 're' from '/usr/l<...>thon3.13/re/__init__.py'>
response              ChatCompletion         ChatCompletion(id='chatcm<...>=2026736388, usage=None))
retrieve_context      function               <function retrieve_context at 0x7f65b3790220>
retrieved_context     str                    ||||**ATM S 2021-2022 Tea<...> Teaching Schedule** \n\n
retrieved_docs        list                   n=3
row                   Series                 category                 <...>.\nName: 0, dtype: object
row_id                int                    99
sample                Series                 category                 <...>.\nName: 0, dtype: object
start                 int                    5600
summarize_text_groq   function               <function summarize_text_groq at 0x7f659b086ac0>
term                  str                    43.7%
terms                 list                   n=3
text                  str                    to kubernetes, cloud-nati<...>llc. all rights reserved.
unique_contexts       list                   n=100
userdata              module                 <module 'google.colab.use<...>oogle/colab/userdata.py'>

In [95]:
question = """
Which bat colony occupies Corkscrew's parking-lot bat house,
and how does the profile describe Florida's smallest bat species?
"""

query_embedding = model.encode(
    [question],
    convert_to_numpy=True
).astype("float32")

distances, indices = passage_index.search(query_embedding, 5)

for rank, idx in enumerate(indices[0], start=1):
    print(f"\n--- Result {rank} | Passage {idx} ---")
    print(passages[idx][:1800])

--- Result 1 | Passage 276 ---
nguinivores.

These flying mammals are the best natural insect-control around.

People are slowly beginning to understand and appreciate these wonderful creatures, but no bats in Florida are completely safe or protected.

cult, but new technologies are helping us better understand them. However, there still isn’t much information about Florida populations. Education, habitat preservation, and more research are all keys to ensuring the continuation of these beneficial animals.

Bats that use trees and foliage are losing ground to development, and bats that move into buildings are susceptible

%IMAGE_DESCRIPTION: A pixelated image of a person wearing a white shirt with their hands raised near their head against a black background.%

At Corkscrew, two bat houses are in place: one by the guest cabin and another in the back of the main parking lot. The parking lot bat house is home to a colony of Brazilian Free-tailed Bats. However, repeated disturbance of this roost could lead to its

--- Result 2 | Passage 299 ---
idsized bats with wingspans of about 12 inches. They have short grayish brown to dark brown fur. Their tails are free with a membrane that comes only to the middle of their tails. There are vertical wrinkles in their upper lips, and

This affinity for stable, manmade structures makes them the most likely candidates for bat house use. Their

All of the bats found at Corkscrew eat insects, and just one bat can consume up to 3,000 insects in a single night. They are our greatest natural insect control.

## **Florida Bonnetted Bat**

## _**Eumops floridanus**_

Originally, Florida Bonneted Bats were a subspecies of Wagner’s Mastiff Bat, but in 2004, taxonomic research concluded that the Florida population was in fact a separate species.

This rare creature is found only in the southern portion of Florida on both the east and west coasts. Currently, there is no evidence of their existence in the Keys.

These bats can be found in urban and forested areas where they may use buildings,

--- Result 3 | Passage 300 ---
ortion of Florida on both the east and west coasts. Currently, there is no evidence of their existence in the Keys.

These bats can be found in urban and forested areas where they may use buildings, barrel tile roofs, tree cavities, and rock crevices for roosting. One colony is currently living in a bat house in North Fort Myers. They seem to prefer smaller colonies of 8-12 bats. Little is known about the social behavior of these bats.

Florida Bonneted Bats are the largest bats in Florida with wingspans of 20 inches. They weigh between 34 and 47 grams. Their fur coloration varies.

Dorsally, it can be dark gray, brownish gray, to cinnamon brown and lighter gray underneath. The fur is bicolored, being darker towards the tip. Its tail extends beyond the membrane. Their ears join together at the midline of their head and are broad and large with a slant forward over the eyes.

of 30 or more feet, above and along treetops and over open areas.

Again because of its rarity, very little

--- Result 4 | Passage 281 ---
life-span of 19 years. Known enemies include barn owls, horned owls, and rat snakes.

In Florida, the Big Brown Bat doesn’t have a large population, so entire colonies could be wiped out with a single improper eradication. Education is one key to maintaining this valuable and beautiful bat.

During autumn and winter, Big

%IMAGE_DESCRIPTION: A close-up photograph of a bat clinging to a rocky surface, possibly a cave wall, with its wings spread and facing the camera.%

%IMAGE_DESCRIPTION: A pixelated image of a person in a white outfit with their arms raised, set against a black background.%

up to 10 years in the wild.

purely nocturnal, only foraging when it is completely dark. While their diet is mostly moths, they will eat other softer bodied insects such as mosquitoes. They are the only Florida bats to use gleaning (taking insects directly off of a surface) as a primary foraging technique. But they are capable of grabbing a meal “on the wing.” They are extremely maneuverable fl

--- Result 5 | Passage 297 ---
in the middle of their head like other similar Florida species.

## _Tadarida brasiliensis_

This species uses a wide variety of habitats and can be found throughout the southern states and down into Central and South America.

These bats also have a scent gland at the base of the throat. They emit a strong, musky odor, somewhat similar to Baked Lays, and they can sometimes be smelled before seen.

The largest concentration of mammals in the world is a colony of Brazilian free-tailed bats at Bracken Cave near San Antonio, Texas. The Brazilian Free-tailed Bat is likely the most abundant bat in Florida.

Brazilian Free-tailed Bats are fast flyers and have been clocked at 60 miles per hour with tail winds. They have been seen flying at altitudes over 10,000 feet, higher than any other bat.

colonies can swell to the thousands depending on the available roost space. Since they prefer very warm roost sites, they may shift sites seasonally but do not undergo long migrations in Florida.

In [96]:
for rank, idx in enumerate(indices[0], start=1):
    text = passages[idx]

    print(f"\n--- Result {rank} | Passage {idx} ---")

    if "parking lot bat house" in text.lower():
        print("Found: Parking-lot bat house")

    if "eastern pipistrelle" in text.lower():
        print("Found: Florida's smallest bat")

    print(text[-1000:])

--- Result 1 | Passage 276 ---
Found: Parking-lot bat house
nguinivores.

These flying mammals are the best natural insect-control around.

People are slowly beginning to understand and appreciate these wonderful creatures, but no bats in Florida are completely safe or protected.

cult, but new technologies are helping us better understand them. However, there still isn’t much information about Florida populations. Education, habitat preservation, and more research are all keys to ensuring the continuation of these beneficial animals.

Bats that use trees and foliage are losing ground to development, and bats that move into buildings are susceptible

%IMAGE_DESCRIPTION: A pixelated image of a person wearing a white shirt with their hands raised near their head against a black background.%

At Corkscrew, two bat houses are in place: one by the guest cabin and another in the back of the main parking lot. The parking lot bat house is home to a colony of Brazilian Free-tailed Bats. However, repeated disturbance of this roost could lead to its

--- Result 2 | Passage 299 ---
idsized bats with wingspans of about 12 inches. They have short grayish brown to dark brown fur. Their tails are free with a membrane that comes only to the middle of their tails. There are vertical wrinkles in their upper lips, and

This affinity for stable, manmade structures makes them the most likely candidates for bat house use. Their

All of the bats found at Corkscrew eat insects, and just one bat can consume up to 3,000 insects in a single night. They are our greatest natural insect control.

## **Florida Bonnetted Bat**

## _**Eumops floridanus**_

Originally, Florida Bonneted Bats were a subspecies of Wagner’s Mastiff Bat, but in 2004, taxonomic research concluded that the Florida population was in fact a separate species.

This rare creature is found only in the southern portion of Florida on both the east and west coasts. Currently, there is no evidence of their existence in the Keys.

These bats can be found in urban and forested areas where they may use buildings,

--- Result 3 | Passage 300 ---
ortion of Florida on both the east and west coasts. Currently, there is no evidence of their existence in the Keys.

These bats can be found in urban and forested areas where they may use buildings, barrel tile roofs, tree cavities, and rock crevices for roosting. One colony is currently living in a bat house in North Fort Myers. They seem to prefer smaller colonies of 8-12 bats. Little is known about the social behavior of these bats.

Florida Bonneted Bats are the largest bats in Florida with wingspans of 20 inches. They weigh between 34 and 47 grams. Their fur coloration varies.

Dorsally, it can be dark gray, brownish gray, to cinnamon brown and lighter gray underneath. The fur is bicolored, being darker towards the tip. Its tail extends beyond the membrane. Their ears join together at the midline of their head and are broad and large with a slant forward over the eyes.

of 30 or more feet, above and along treetops and over open areas.

Again because of its rarity, very little

--- Result 4 | Passage 281 ---
life-span of 19 years. Known enemies include barn owls, horned owls, and rat snakes.

In Florida, the Big Brown Bat doesn’t have a large population, so entire colonies could be wiped out with a single improper eradication. Education is one key to maintaining this valuable and beautiful bat.

During autumn and winter, Big

%IMAGE_DESCRIPTION: A close-up photograph of a bat clinging to a rocky surface, possibly a cave wall, with its wings spread and facing the camera.%

%IMAGE_DESCRIPTION: A pixelated image of a person in a white outfit with their arms raised, set against a black background.%

up to 10 years in the wild.

purely nocturnal, only foraging when it is completely dark. While their diet is mostly moths, they will eat other softer bodied insects such as mosquitoes. They are the only Florida bats to use gleaning (taking insects directly off of a surface) as a primary foraging technique. But they are capable of grabbing a meal “on the wing.” They are extremely maneuverable fl

--- Result 5 | Passage 297 ---
in the middle of their head like other similar Florida species.

## _Tadarida brasiliensis_

This species uses a wide variety of habitats and can be found throughout the southern states and down into Central and South America.

These bats also have a scent gland at the base of the throat. They emit a strong, musky odor, somewhat similar to Baked Lays, and they can sometimes be smelled before seen.

The largest concentration of mammals in the world is a colony of Brazilian free-tailed bats at Bracken Cave near San Antonio, Texas. The Brazilian Free-tailed Bat is likely the most abundant bat in Florida.

Brazilian Free-tailed Bats are fast flyers and have been clocked at 60 miles per hour with tail winds. They have been seen flying at altitudes over 10,000 feet, higher than any other bat.

colonies can swell to the thousands depending on the available roost space. Since they prefer very warm roost sites, they may shift sites seasonally but do not undergo long migrations in Florida.

In [97]:
print("=== Passage 277: Bat house ===")
print(passages[277])

print("\n=== Passage 283: Smallest bat ===")
print(passages[283])

=== Passage 277: Bat house ===
guest cabin and another in the back of the main parking lot. The parking lot bat house is home to a colony of Brazilian Free-tailed Bats. However, repeated disturbance of this roost could lead to its abandonment, so please respect their home.

## **Friends in the Night Corkscrew’s Bats**

## **Big Brown Bat**

## _Eptesicus fuscus_

Big Brown Bats are found throughout North America from Canada to southern Mexico.

Normally  forest dwellers, they do not hesitate to utilize  attics and crevices in buildings, caves, and rocks for daytime retreats. Favorite roosts are under the  loose bark of dead trees and in cavities of trees.

Big Brown Bats are just that … big (13-16 inch wingspan) with brown, long fur ranging in color from dark to golden brown. Their undersides are a lighter shade. They have dark brown, almost black ears. Their teeth are impressive because these beneficial bats eat a variety of hard-bodied insects.

The Big Brown Bat is largely crepuscular, becoming active at j

=== Passage 283: Smallest bat ===
ee months. They can live

Biologists age bats by looking at the finger bones in the outstretched wings over a bright light. Juvenile bats’ bones have clear spaces between the joints; adult bats have ossified joints.

## **Friends in the Night Corkscrew’s Bats**

## **Eastern Pipistrelles**

## _Pipistrellus sublavus_

Eastern Pipistrelles is Florida’s smallest bat, weighing in at a mere 1/4 ounce. The body is less than two inches long, with an eight to ten inch wingspan. They are solitary except at mating and in small nursery groups.

Eastern Pipistrelles are some of the earliest bats to emerge in the evening and are often be seen in the ambient light as they move to foraging grounds. They are relatively slow and erratic in flight, often fluttering and flitting along watercourses or over pastures and woodlands much like large moths.

They can catch prey at a rate of one insect every two seconds, increasing body mass as much as 25 percent in just thirty minutes. Typically, the di

In [98]:
query_embedding = model.encode(
    [question],
    convert_to_numpy=True
).astype("float32")

distances, indices = passage_index.search(query_embedding, 10)

for rank, idx in enumerate(indices[0], start=1):
    print(f"\n--- Result {rank} | Passage {idx} ---")
    print(passages[idx][:1000])

--- Result 1 | Passage 276 ---
nguinivores.

These flying mammals are the best natural insect-control around.

People are slowly beginning to understand and appreciate these wonderful creatures, but no bats in Florida are completely safe or protected.

cult, but new technologies are helping us better understand them. However, there still isn’t much information about Florida populations. Education, habitat preservation, and more research are all keys to ensuring the continuation of these beneficial animals.

Bats that use trees and foliage are losing ground to development, and bats that move into buildings are susceptible

%IMAGE_DESCRIPTION: A pixelated image of a person wearing a white shirt with their hands raised near their head against a black background.%

At Corkscrew, two bat houses are in place: one by the guest cabin and another in the back of the main parking lot. The parking lot bat house is home to a colony of Brazilian Free-tailed Bats. However, repeated disturbance of this roost could lead to its

--- Result 2 | Passage 299 ---
idsized bats with wingspans of about 12 inches. They have short grayish brown to dark brown fur. Their tails are free with a membrane that comes only to the middle of their tails. There are vertical wrinkles in their upper lips, and

This affinity for stable, manmade structures makes them the most likely candidates for bat house use. Their

All of the bats found at Corkscrew eat insects, and just one bat can consume up to 3,000 insects in a single night. They are our greatest natural insect control.

## **Florida Bonnetted Bat**

## _**Eumops floridanus**_

Originally, Florida Bonneted Bats were a subspecies of Wagner’s Mastiff Bat, but in 2004, taxonomic research concluded that the Florida population was in fact a separate species.

This rare creature is found only in the southern portion of Florida on both the east and west coasts. Currently, there is no evidence of their existence in the Keys.

These bats can be found in urban and forested areas where they may use buildings,

--- Result 3 | Passage 300 ---
ortion of Florida on both the east and west coasts. Currently, there is no evidence of their existence in the Keys.

These bats can be found in urban and forested areas where they may use buildings, barrel tile roofs, tree cavities, and rock crevices for roosting. One colony is currently living in a bat house in North Fort Myers. They seem to prefer smaller colonies of 8-12 bats. Little is known about the social behavior of these bats.

Florida Bonneted Bats are the largest bats in Florida with wingspans of 20 inches. They weigh between 34 and 47 grams. Their fur coloration varies.

Dorsally, it can be dark gray, brownish gray, to cinnamon brown and lighter gray underneath. The fur is bicolored, being darker towards the tip. Its tail extends beyond the membrane. Their ears join together at the midline of their head and are broad and large with a slant forward over the eyes.

of 30 or more feet, above and along treetops and over open areas.

Again because of its rarity, very little

--- Result 4 | Passage 281 ---
life-span of 19 years. Known enemies include barn owls, horned owls, and rat snakes.

In Florida, the Big Brown Bat doesn’t have a large population, so entire colonies could be wiped out with a single improper eradication. Education is one key to maintaining this valuable and beautiful bat.

During autumn and winter, Big

%IMAGE_DESCRIPTION: A close-up photograph of a bat clinging to a rocky surface, possibly a cave wall, with its wings spread and facing the camera.%

%IMAGE_DESCRIPTION: A pixelated image of a person in a white outfit with their arms raised, set against a black background.%

up to 10 years in the wild.

purely nocturnal, only foraging when it is completely dark. While their diet is mostly moths, they will eat other softer bodied insects such as mosquitoes. They are the only Florida bats to use gleaning (taking insects directly off of a surface) as a primary foraging technique. But they are capable of grabbing a meal “on the wing.” They are extremely maneuverable fl

--- Result 5 | Passage 297 ---
in the middle of their head like other similar Florida species.

## _Tadarida brasiliensis_

This species uses a wide variety of habitats and can be found throughout the southern states and down into Central and South America.

These bats also have a scent gland at the base of the throat. They emit a strong, musky odor, somewhat similar to Baked Lays, and they can sometimes be smelled before seen.

The largest concentration of mammals in the world is a colony of Brazilian free-tailed bats at Bracken Cave near San Antonio, Texas. The Brazilian Free-tailed Bat is likely the most abundant bat in Florida.

Brazilian Free-tailed Bats are fast flyers and have been clocked at 60 miles per hour with tail winds. They have been seen flying at altitudes over 10,000 feet, higher than any other bat.

colonies can swell to the thousands depending on the available roost space. Since they prefer very warm roost sites, they may shift sites seasonally but do not undergo long migrations in Florida.

--- Result 6 | Passage 291 ---
in its roost habitat of dead palm fronds. The fur extends down the body to Merlin D. Tuttle Bat Conservation International cover about half of its tail membrane. Its ears are relatively large and pointed.

In Florida, these bats inMerlin D. Tuttle habit hardwood and pine forests near permanent water but are also found in palm groves. They roost yearround in Spanish moss or beneath the dead, fan-shaped fronds of palms.

Although it  is solitary, small groups may roost  together in the skirts of old fronds of cabbage palms.

At four to five inches in length and with a wingspan of 14-16 inches, the Northern Yellow Bat is the second largest bat in Florida after the Mastiff Bat.

This species forages at night at heights of 15 - 20 feet over meadows, golf courses, marshes, and above the treetops along lake and forest edges. Its diet consists entirely of insects, mostly flies, dragonflies and damselflies,

There are no reliable longevity records for this species, but the fact that they

--- Result 7 | Passage 277 ---
guest cabin and another in the back of the main parking lot. The parking lot bat house is home to a colony of Brazilian Free-tailed Bats. However, repeated disturbance of this roost could lead to its abandonment, so please respect their home.

## **Friends in the Night Corkscrew’s Bats**

## **Big Brown Bat**

## _Eptesicus fuscus_

Big Brown Bats are found throughout North America from Canada to southern Mexico.

Normally  forest dwellers, they do not hesitate to utilize  attics and crevices in buildings, caves, and rocks for daytime retreats. Favorite roosts are under the  loose bark of dead trees and in cavities of trees.

Big Brown Bats are just that … big (13-16 inch wingspan) with brown, long fur ranging in color from dark to golden brown. Their undersides are a lighter shade. They have dark brown, almost black ears. Their teeth are impressive because these beneficial bats eat a variety of hard-bodied insects.

The Big Brown Bat is largely crepuscular, becoming active at j

--- Result 8 | Passage 293 ---
e use is especially heavy. That and loss of habitat are its main threats. The clearing of woodlands and the practice of removing old palm fronds and Spanish moss kills many individuals and destroys habitat.

Owls and rat snakes are known predators of Northern Yellow Bats.

## **Seminole Bat**

## _**Lasiurus seminolus**_

The Seminole Bat is common throughout Florida except in the Keys. It spends most of its life in forests of mixed oak and pine, or in lowland cypress stands and river swamps and is closely associated with lowland wooded areas with Spanish moss. It ranges throughout the Gulf Coast states but not much further north than the Carolinas.

The Seminole Bat is a mediumsized bat with deep mahogany fur with frosted tips, giving it a distinct reddishmaroon hue. The fur goes to the tip of its tail and extends along the underarms to the wrists, ending with distinctive white patches on the wrists and shoulders. It is about two to three inches in length with a wingspan of 11-13

--- Result 9 | Passage 288 ---
in Florida, although they are not in the Keys. Their range extends throughout the eastern United States. They are more prevalent in the southeastern states but are uncommon in most of the northern part of their range.

In natural areas, Evening Bats roost behind loose bark, in the crevices and cavities of dead trees, and abandoned woodpecker cavities. They readily adapt to bat houses, often sharing the space with other bat species; they’ve even been found roosting in the folds of outdoor patio umbrellas.

The fur is brown, sometimes with a bronze to reddish tint. A small, broad, dark, naked muzzle distinguishes them from other small brown bats.

These bats usually emerge early, 15-20 minutes after sunset, and fly a slow steady course when foraging.

Evening Bats prefer a woodland or mixed woodland/open area habitat for nesting colonies. Colony sizes range from just a few to around 70.

Evening bats are one of the few bats which almost never enter caves. In Florida, they leave bat

--- Result 10 | Passage 287 ---
.

## _**Nycticeius humeralis**_

The Evening Bat is one of the smaller bats, weighing less than half an ounce. Their tiny bodies fit easily in the palm of a hand, but with a wingspan of about eight to ten inches, they seem larger in flight.

The Evening Bat’s food preferences are similar to those of the Big Brown Bat (see July newsletter), primarily beetles and true bugs, but they eat more moths. In Florida, evening bats also have been seen foraging for mosquitoes, flying ants and termites, beetles, stinkbugs, June bugs, and flies.

%IMAGE_DESCRIPTION: A close-up photograph of a bat hanging upside down, with its wings folded. The bat has dark brown fur and is hanging from a surface with a light-colored background. Photo George Marks%

Evening Bats are one of the more abundant species in Florida, although they are not in the Keys. Their range extends throughout the eastern United States. They are more prevalent in the southeastern states but are uncommon in most of the northern par

In [99]:
keywords = [
    "parking lot bat house",
    "Brazilian Free-tailed Bats",
    "Eastern Pipistrelles",
    "Florida's smallest bat"
]

for keyword in keywords:
    print(f"\n--- Searching for: {keyword} ---")

    matches = [
        i for i, passage in enumerate(passages)
        if keyword.lower() in passage.lower()
    ]

    print("Matching passages:", matches[:10])
    print("Total matches:", len(matches))

--- Searching for: parking lot bat house ---
Matching passages: [276, 277]
Total matches: 2

--- Searching for: Brazilian Free-tailed Bats ---
Matching passages: [276, 277, 297, 298]
Total matches: 4

--- Searching for: Eastern Pipistrelles ---
Matching passages: [272, 283, 284, 285]
Total matches: 4

--- Searching for: Florida's smallest bat ---
Matching passages: []
Total matches: 0

In [100]:
for idx in [277, 283, 284, 285]:
    print(f"\n{'=' * 20} Passage {idx} {'=' * 20}")
    print(passages[idx])

==================== Passage 277 ====================
guest cabin and another in the back of the main parking lot. The parking lot bat house is home to a colony of Brazilian Free-tailed Bats. However, repeated disturbance of this roost could lead to its abandonment, so please respect their home.

## **Friends in the Night Corkscrew’s Bats**

## **Big Brown Bat**

## _Eptesicus fuscus_

Big Brown Bats are found throughout North America from Canada to southern Mexico.

Normally  forest dwellers, they do not hesitate to utilize  attics and crevices in buildings, caves, and rocks for daytime retreats. Favorite roosts are under the  loose bark of dead trees and in cavities of trees.

Big Brown Bats are just that … big (13-16 inch wingspan) with brown, long fur ranging in color from dark to golden brown. Their undersides are a lighter shade. They have dark brown, almost black ears. Their teeth are impressive because these beneficial bats eat a variety of hard-bodied insects.

The Big Brown Bat is largely crepuscular, becoming active at j

==================== Passage 283 ====================
ee months. They can live

Biologists age bats by looking at the finger bones in the outstretched wings over a bright light. Juvenile bats’ bones have clear spaces between the joints; adult bats have ossified joints.

## **Friends in the Night Corkscrew’s Bats**

## **Eastern Pipistrelles**

## _Pipistrellus sublavus_

Eastern Pipistrelles is Florida’s smallest bat, weighing in at a mere 1/4 ounce. The body is less than two inches long, with an eight to ten inch wingspan. They are solitary except at mating and in small nursery groups.

Eastern Pipistrelles are some of the earliest bats to emerge in the evening and are often be seen in the ambient light as they move to foraging grounds. They are relatively slow and erratic in flight, often fluttering and flitting along watercourses or over pastures and woodlands much like large moths.

They can catch prey at a rate of one insect every two seconds, increasing body mass as much as 25 percent in just thirty minutes. Typically, the di

==================== Passage 284 ====================
over pastures and woodlands much like large moths.

They can catch prey at a rate of one insect every two seconds, increasing body mass as much as 25 percent in just thirty minutes. Typically, the diet consists of flies, mosquitoes, flying ants, small beetles and small moths.

Eastern Pipistrelles inhabit marshes

%IMAGE_DESCRIPTION: A close-up photograph of a small, light-brown animal, possibly a rodent or a rabbit, being held by a person. The animal has large eyes and appears to be looking directly at the camera. The person's hand is visible, supporting the animal. The background is dark, and the overall image quality is pixelated.%

and open woods near the edges of water.  They appear to favor watercourses as foraging grounds and are not usually found in open fields or deep forests. Although not considered abundant, they are present throughout Florida, except in the Keys.

In Florida, roost habitat includes tree foliage and cavities, rock crevices, Spanish moss, and  occasionall

==================== Passage 285 ====================
Although not considered abundant, they are present throughout Florida, except in the Keys.

In Florida, roost habitat includes tree foliage and cavities, rock crevices, Spanish moss, and  occasionally buildings.

Fur color varies from silvery-gray to light brown. Individual hairs are tricolored; dark base, yellow-brown

middle, and dark tips. The wings have black wing membranes contrasting with reddish-orange forearms.

Eastern Pipistrelles are obligate hibernators, meaning that they still hibernate even though food is available. Because they cannot remotely withstand freezing temperatures, they are among the first species to begin hibernating and some of the last to emerge in the spring. They generally hibernate individually.

Mating occurs in autumn before hibernation, and mating is the only time males and females are ever together. Females give birth to twins from late May to mid July. Having twins is rare among other bat species. At three weeks the young are able to fly, they

In [101]:
for idx in [283, 284, 285]:
    print(f"\n--- Passage {idx} ---")
    print(passages[idx][-1200:])

--- Passage 283 ---
ee months. They can live

Biologists age bats by looking at the finger bones in the outstretched wings over a bright light. Juvenile bats’ bones have clear spaces between the joints; adult bats have ossified joints.

## **Friends in the Night Corkscrew’s Bats**

## **Eastern Pipistrelles**

## _Pipistrellus sublavus_

Eastern Pipistrelles is Florida’s smallest bat, weighing in at a mere 1/4 ounce. The body is less than two inches long, with an eight to ten inch wingspan. They are solitary except at mating and in small nursery groups.

Eastern Pipistrelles are some of the earliest bats to emerge in the evening and are often be seen in the ambient light as they move to foraging grounds. They are relatively slow and erratic in flight, often fluttering and flitting along watercourses or over pastures and woodlands much like large moths.

They can catch prey at a rate of one insect every two seconds, increasing body mass as much as 25 percent in just thirty minutes. Typically, the di

--- Passage 284 ---
over pastures and woodlands much like large moths.

They can catch prey at a rate of one insect every two seconds, increasing body mass as much as 25 percent in just thirty minutes. Typically, the diet consists of flies, mosquitoes, flying ants, small beetles and small moths.

Eastern Pipistrelles inhabit marshes

%IMAGE_DESCRIPTION: A close-up photograph of a small, light-brown animal, possibly a rodent or a rabbit, being held by a person. The animal has large eyes and appears to be looking directly at the camera. The person's hand is visible, supporting the animal. The background is dark, and the overall image quality is pixelated.%

and open woods near the edges of water.  They appear to favor watercourses as foraging grounds and are not usually found in open fields or deep forests. Although not considered abundant, they are present throughout Florida, except in the Keys.

In Florida, roost habitat includes tree foliage and cavities, rock crevices, Spanish moss, and  occasionall

--- Passage 285 ---
Although not considered abundant, they are present throughout Florida, except in the Keys.

In Florida, roost habitat includes tree foliage and cavities, rock crevices, Spanish moss, and  occasionally buildings.

Fur color varies from silvery-gray to light brown. Individual hairs are tricolored; dark base, yellow-brown

middle, and dark tips. The wings have black wing membranes contrasting with reddish-orange forearms.

Eastern Pipistrelles are obligate hibernators, meaning that they still hibernate even though food is available. Because they cannot remotely withstand freezing temperatures, they are among the first species to begin hibernating and some of the last to emerge in the spring. They generally hibernate individually.

Mating occurs in autumn before hibernation, and mating is the only time males and females are ever together. Females give birth to twins from late May to mid July. Having twins is rare among other bat species. At three weeks the young are able to fly, they

In [102]:

query = "Eastern Pipistrelles Florida's smallest bat"

query_embedding = model.encode(
    [query],
    convert_to_numpy=True
).astype("float32")

distances, indices = passage_index.search(query_embedding, 5)

for rank, idx in enumerate(indices[0], start=1):
    print(f"\n--- Result {rank} | Passage {idx} ---")
    print(passages[idx][:1000])

--- Result 1 | Passage 283 ---
ee months. They can live

Biologists age bats by looking at the finger bones in the outstretched wings over a bright light. Juvenile bats’ bones have clear spaces between the joints; adult bats have ossified joints.

## **Friends in the Night Corkscrew’s Bats**

## **Eastern Pipistrelles**

## _Pipistrellus sublavus_

Eastern Pipistrelles is Florida’s smallest bat, weighing in at a mere 1/4 ounce. The body is less than two inches long, with an eight to ten inch wingspan. They are solitary except at mating and in small nursery groups.

Eastern Pipistrelles are some of the earliest bats to emerge in the evening and are often be seen in the ambient light as they move to foraging grounds. They are relatively slow and erratic in flight, often fluttering and flitting along watercourses or over pastures and woodlands much like large moths.

They can catch prey at a rate of one insect every two seconds, increasing body mass as much as 25 percent in just thirty minutes. Typically, the di

--- Result 2 | Passage 300 ---
ortion of Florida on both the east and west coasts. Currently, there is no evidence of their existence in the Keys.

These bats can be found in urban and forested areas where they may use buildings, barrel tile roofs, tree cavities, and rock crevices for roosting. One colony is currently living in a bat house in North Fort Myers. They seem to prefer smaller colonies of 8-12 bats. Little is known about the social behavior of these bats.

Florida Bonneted Bats are the largest bats in Florida with wingspans of 20 inches. They weigh between 34 and 47 grams. Their fur coloration varies.

Dorsally, it can be dark gray, brownish gray, to cinnamon brown and lighter gray underneath. The fur is bicolored, being darker towards the tip. Its tail extends beyond the membrane. Their ears join together at the midline of their head and are broad and large with a slant forward over the eyes.

of 30 or more feet, above and along treetops and over open areas.

Again because of its rarity, very little

--- Result 3 | Passage 299 ---
idsized bats with wingspans of about 12 inches. They have short grayish brown to dark brown fur. Their tails are free with a membrane that comes only to the middle of their tails. There are vertical wrinkles in their upper lips, and

This affinity for stable, manmade structures makes them the most likely candidates for bat house use. Their

All of the bats found at Corkscrew eat insects, and just one bat can consume up to 3,000 insects in a single night. They are our greatest natural insect control.

## **Florida Bonnetted Bat**

## _**Eumops floridanus**_

Originally, Florida Bonneted Bats were a subspecies of Wagner’s Mastiff Bat, but in 2004, taxonomic research concluded that the Florida population was in fact a separate species.

This rare creature is found only in the southern portion of Florida on both the east and west coasts. Currently, there is no evidence of their existence in the Keys.

These bats can be found in urban and forested areas where they may use buildings,

--- Result 4 | Passage 287 ---
.

## _**Nycticeius humeralis**_

The Evening Bat is one of the smaller bats, weighing less than half an ounce. Their tiny bodies fit easily in the palm of a hand, but with a wingspan of about eight to ten inches, they seem larger in flight.

The Evening Bat’s food preferences are similar to those of the Big Brown Bat (see July newsletter), primarily beetles and true bugs, but they eat more moths. In Florida, evening bats also have been seen foraging for mosquitoes, flying ants and termites, beetles, stinkbugs, June bugs, and flies.

%IMAGE_DESCRIPTION: A close-up photograph of a bat hanging upside down, with its wings folded. The bat has dark brown fur and is hanging from a surface with a light-colored background. Photo George Marks%

Evening Bats are one of the more abundant species in Florida, although they are not in the Keys. Their range extends throughout the eastern United States. They are more prevalent in the southeastern states but are uncommon in most of the northern par

--- Result 5 | Passage 297 ---
in the middle of their head like other similar Florida species.

## _Tadarida brasiliensis_

This species uses a wide variety of habitats and can be found throughout the southern states and down into Central and South America.

These bats also have a scent gland at the base of the throat. They emit a strong, musky odor, somewhat similar to Baked Lays, and they can sometimes be smelled before seen.

The largest concentration of mammals in the world is a colony of Brazilian free-tailed bats at Bracken Cave near San Antonio, Texas. The Brazilian Free-tailed Bat is likely the most abundant bat in Florida.

Brazilian Free-tailed Bats are fast flyers and have been clocked at 60 miles per hour with tail winds. They have been seen flying at altitudes over 10,000 feet, higher than any other bat.

colonies can swell to the thousands depending on the available roost space. Since they prefer very warm roost sites, they may shift sites seasonally but do not undergo long migrations in Florida.

In [103]:

keywords = ["parking-lot bat house", "Eastern Pipistrelle"]

for keyword in keywords:
    print(f"\n===== Searching: {keyword} =====")

    matches = [
        (i, passage)
        for i, passage in enumerate(passages)
        if keyword.lower() in passage.lower()
    ]

    if matches:
        for i, passage in matches[:3]:
            print(f"\nPassage {i}:")
            print(passage[:1200])
    else:
        print("No exact match found.")

===== Searching: parking-lot bat house =====
No exact match found.

===== Searching: Eastern Pipistrelle =====

Passage 272:
## **Corkscrew’s Bats Friends in the Night**

|Big Brown Bat<br>_Eptesicus fuscus_|Eastern Pipistrelles<br>_Pipistrelles sublavus_|Northern Yellow Bat<br>_Lasiurus intermedius_|Brazilian Free-tailed Bat<br>_Tadarida brasiliensis_|
|---|---|---|---|
|Rafinesque’s Big-eared Bat<br>_Corynorhinus rafinesquii_|Evening Bat<br>_Nycticeius humeralis_|Seminole Bat<br>_Lasiurus seminolus_|Florida Bonneted Bat<br>_Eumops floridanus_|



As night descends, many animals settle in for the night. Others are just beginning to stir.

A variety of nocturnal animals call Corkscrew home, including misunderstood and often feared bats. These fascinating animals, the only mammals with true flight, are our friends in the night skies, hunting for insects such as mosquitoes and numerous agricultural pests. Yet little is known about them.

These brief profiles will introduce you to the mysterious and intriguing world of bats with an emphasis on the species found in the Corkscrew area.

All bats belong to the

Passage 283:
ee months. They can live

Biologists age bats by looking at the finger bones in the outstretched wings over a bright light. Juvenile bats’ bones have clear spaces between the joints; adult bats have ossified joints.

## **Friends in the Night Corkscrew’s Bats**

## **Eastern Pipistrelles**

## _Pipistrellus sublavus_

Eastern Pipistrelles is Florida’s smallest bat, weighing in at a mere 1/4 ounce. The body is less than two inches long, with an eight to ten inch wingspan. They are solitary except at mating and in small nursery groups.

Eastern Pipistrelles are some of the earliest bats to emerge in the evening and are often be seen in the ambient light as they move to foraging grounds. They are relatively slow and erratic in flight, often fluttering and flitting along watercourses or over pastures and woodlands much like large moths.

They can catch prey at a rate of one insect every two seconds, increasing body mass as much as 25 percent in just thirty minutes. Typically, the di

Passage 284:
over pastures and woodlands much like large moths.

They can catch prey at a rate of one insect every two seconds, increasing body mass as much as 25 percent in just thirty minutes. Typically, the diet consists of flies, mosquitoes, flying ants, small beetles and small moths.

Eastern Pipistrelles inhabit marshes

%IMAGE_DESCRIPTION: A close-up photograph of a small, light-brown animal, possibly a rodent or a rabbit, being held by a person. The animal has large eyes and appears to be looking directly at the camera. The person's hand is visible, supporting the animal. The background is dark, and the overall image quality is pixelated.%

and open woods near the edges of water.  They appear to favor watercourses as foraging grounds and are not usually found in open fields or deep forests. Although not considered abundant, they are present throughout Florida, except in the Keys.

In Florida, roost habitat includes tree foliage and cavities, rock crevices, Spanish moss, and  occasionall

In [104]:

keywords = ["parking lot", "bat house", "smallest bat", "Pipistrellus subflavus"]

for keyword in keywords:
    print(f"\n{'='*20} {keyword} {'='*20}")

    count = 0
    for i, passage in enumerate(passages):
        if keyword.lower() in passage.lower():
            print(f"\nPassage {i}:")
            print(passage[:1500])
            count += 1

            if count == 3:
                break

    if count == 0:
        print("No match found.")

==================== parking lot ====================

Passage 276:
nguinivores.

These flying mammals are the best natural insect-control around.

People are slowly beginning to understand and appreciate these wonderful creatures, but no bats in Florida are completely safe or protected.

cult, but new technologies are helping us better understand them. However, there still isn’t much information about Florida populations. Education, habitat preservation, and more research are all keys to ensuring the continuation of these beneficial animals.

Bats that use trees and foliage are losing ground to development, and bats that move into buildings are susceptible

%IMAGE_DESCRIPTION: A pixelated image of a person wearing a white shirt with their hands raised near their head against a black background.%

At Corkscrew, two bat houses are in place: one by the guest cabin and another in the back of the main parking lot. The parking lot bat house is home to a colony of Brazilian Free-tailed Bats. However, repeated disturbance of this roost could lead to its

Passage 277:
guest cabin and another in the back of the main parking lot. The parking lot bat house is home to a colony of Brazilian Free-tailed Bats. However, repeated disturbance of this roost could lead to its abandonment, so please respect their home.

## **Friends in the Night Corkscrew’s Bats**

## **Big Brown Bat**

## _Eptesicus fuscus_

Big Brown Bats are found throughout North America from Canada to southern Mexico.

Normally  forest dwellers, they do not hesitate to utilize  attics and crevices in buildings, caves, and rocks for daytime retreats. Favorite roosts are under the  loose bark of dead trees and in cavities of trees.

Big Brown Bats are just that … big (13-16 inch wingspan) with brown, long fur ranging in color from dark to golden brown. Their undersides are a lighter shade. They have dark brown, almost black ears. Their teeth are impressive because these beneficial bats eat a variety of hard-bodied insects.

The Big Brown Bat is largely crepuscular, becoming active at j

==================== bat house ====================

Passage 276:
nguinivores.

These flying mammals are the best natural insect-control around.

People are slowly beginning to understand and appreciate these wonderful creatures, but no bats in Florida are completely safe or protected.

cult, but new technologies are helping us better understand them. However, there still isn’t much information about Florida populations. Education, habitat preservation, and more research are all keys to ensuring the continuation of these beneficial animals.

Bats that use trees and foliage are losing ground to development, and bats that move into buildings are susceptible

%IMAGE_DESCRIPTION: A pixelated image of a person wearing a white shirt with their hands raised near their head against a black background.%

At Corkscrew, two bat houses are in place: one by the guest cabin and another in the back of the main parking lot. The parking lot bat house is home to a colony of Brazilian Free-tailed Bats. However, repeated disturbance of this roost could lead to its

Passage 277:
guest cabin and another in the back of the main parking lot. The parking lot bat house is home to a colony of Brazilian Free-tailed Bats. However, repeated disturbance of this roost could lead to its abandonment, so please respect their home.

## **Friends in the Night Corkscrew’s Bats**

## **Big Brown Bat**

## _Eptesicus fuscus_

Big Brown Bats are found throughout North America from Canada to southern Mexico.

Normally  forest dwellers, they do not hesitate to utilize  attics and crevices in buildings, caves, and rocks for daytime retreats. Favorite roosts are under the  loose bark of dead trees and in cavities of trees.

Big Brown Bats are just that … big (13-16 inch wingspan) with brown, long fur ranging in color from dark to golden brown. Their undersides are a lighter shade. They have dark brown, almost black ears. Their teeth are impressive because these beneficial bats eat a variety of hard-bodied insects.

The Big Brown Bat is largely crepuscular, becoming active at j

Passage 288:
in Florida, although they are not in the Keys. Their range extends throughout the eastern United States. They are more prevalent in the southeastern states but are uncommon in most of the northern part of their range.

In natural areas, Evening Bats roost behind loose bark, in the crevices and cavities of dead trees, and abandoned woodpecker cavities. They readily adapt to bat houses, often sharing the space with other bat species; they’ve even been found roosting in the folds of outdoor patio umbrellas.

The fur is brown, sometimes with a bronze to reddish tint. A small, broad, dark, naked muzzle distinguishes them from other small brown bats.

These bats usually emerge early, 15-20 minutes after sunset, and fly a slow steady course when foraging.

Evening Bats prefer a woodland or mixed woodland/open area habitat for nesting colonies. Colony sizes range from just a few to around 70.

Evening bats are one of the few bats which almost never enter caves. In Florida, they leave bat

==================== smallest bat ====================

Passage 283:
ee months. They can live

Biologists age bats by looking at the finger bones in the outstretched wings over a bright light. Juvenile bats’ bones have clear spaces between the joints; adult bats have ossified joints.

## **Friends in the Night Corkscrew’s Bats**

## **Eastern Pipistrelles**

## _Pipistrellus sublavus_

Eastern Pipistrelles is Florida’s smallest bat, weighing in at a mere 1/4 ounce. The body is less than two inches long, with an eight to ten inch wingspan. They are solitary except at mating and in small nursery groups.

Eastern Pipistrelles are some of the earliest bats to emerge in the evening and are often be seen in the ambient light as they move to foraging grounds. They are relatively slow and erratic in flight, often fluttering and flitting along watercourses or over pastures and woodlands much like large moths.

They can catch prey at a rate of one insect every two seconds, increasing body mass as much as 25 percent in just thirty minutes. Typically, the di

==================== Pipistrellus subflavus ====================
No match found.

In [106]:

for i, passage in enumerate(passages):
    if "Pipistrellus subflavus" in passage:
        print(f"Passage {i}")
        print(passage)
        print("-" * 60)

In [107]:

print("Total passages:", len(passages))

for i, passage in enumerate(passages):
    if "pipistrelle" in passage.lower():
        print(f"\nPassage {i}:")
        print(passage[:2000])

Total passages: 2749

Passage 272:
## **Corkscrew’s Bats Friends in the Night**

|Big Brown Bat<br>_Eptesicus fuscus_|Eastern Pipistrelles<br>_Pipistrelles sublavus_|Northern Yellow Bat<br>_Lasiurus intermedius_|Brazilian Free-tailed Bat<br>_Tadarida brasiliensis_|
|---|---|---|---|
|Rafinesque’s Big-eared Bat<br>_Corynorhinus rafinesquii_|Evening Bat<br>_Nycticeius humeralis_|Seminole Bat<br>_Lasiurus seminolus_|Florida Bonneted Bat<br>_Eumops floridanus_|



As night descends, many animals settle in for the night. Others are just beginning to stir.

A variety of nocturnal animals call Corkscrew home, including misunderstood and often feared bats. These fascinating animals, the only mammals with true flight, are our friends in the night skies, hunting for insects such as mosquitoes and numerous agricultural pests. Yet little is known about them.

These brief profiles will introduce you to the mysterious and intriguing world of bats with an emphasis on the species found in the Corkscrew area.

All bats belong to the

Passage 283:
ee months. They can live

Biologists age bats by looking at the finger bones in the outstretched wings over a bright light. Juvenile bats’ bones have clear spaces between the joints; adult bats have ossified joints.

## **Friends in the Night Corkscrew’s Bats**

## **Eastern Pipistrelles**

## _Pipistrellus sublavus_

Eastern Pipistrelles is Florida’s smallest bat, weighing in at a mere 1/4 ounce. The body is less than two inches long, with an eight to ten inch wingspan. They are solitary except at mating and in small nursery groups.

Eastern Pipistrelles are some of the earliest bats to emerge in the evening and are often be seen in the ambient light as they move to foraging grounds. They are relatively slow and erratic in flight, often fluttering and flitting along watercourses or over pastures and woodlands much like large moths.

They can catch prey at a rate of one insect every two seconds, increasing body mass as much as 25 percent in just thirty minutes. Typically, the di

Passage 284:
over pastures and woodlands much like large moths.

They can catch prey at a rate of one insect every two seconds, increasing body mass as much as 25 percent in just thirty minutes. Typically, the diet consists of flies, mosquitoes, flying ants, small beetles and small moths.

Eastern Pipistrelles inhabit marshes

%IMAGE_DESCRIPTION: A close-up photograph of a small, light-brown animal, possibly a rodent or a rabbit, being held by a person. The animal has large eyes and appears to be looking directly at the camera. The person's hand is visible, supporting the animal. The background is dark, and the overall image quality is pixelated.%

and open woods near the edges of water.  They appear to favor watercourses as foraging grounds and are not usually found in open fields or deep forests. Although not considered abundant, they are present throughout Florida, except in the Keys.

In Florida, roost habitat includes tree foliage and cavities, rock crevices, Spanish moss, and  occasionall

Passage 285:
Although not considered abundant, they are present throughout Florida, except in the Keys.

In Florida, roost habitat includes tree foliage and cavities, rock crevices, Spanish moss, and  occasionally buildings.

Fur color varies from silvery-gray to light brown. Individual hairs are tricolored; dark base, yellow-brown

middle, and dark tips. The wings have black wing membranes contrasting with reddish-orange forearms.

Eastern Pipistrelles are obligate hibernators, meaning that they still hibernate even though food is available. Because they cannot remotely withstand freezing temperatures, they are among the first species to begin hibernating and some of the last to emerge in the spring. They generally hibernate individually.

Mating occurs in autumn before hibernation, and mating is the only time males and females are ever together. Females give birth to twins from late May to mid July. Having twins is rare among other bat species. At three weeks the young are able to fly, they

In [108]:

print("PASSAGE 283")
print(passages[283])

print("\n" + "=" * 50)
print("PASSAGE 277")
print(passages[277])

PASSAGE 283
ee months. They can live

Biologists age bats by looking at the finger bones in the outstretched wings over a bright light. Juvenile bats’ bones have clear spaces between the joints; adult bats have ossified joints.

## **Friends in the Night Corkscrew’s Bats**

## **Eastern Pipistrelles**

## _Pipistrellus sublavus_

Eastern Pipistrelles is Florida’s smallest bat, weighing in at a mere 1/4 ounce. The body is less than two inches long, with an eight to ten inch wingspan. They are solitary except at mating and in small nursery groups.

Eastern Pipistrelles are some of the earliest bats to emerge in the evening and are often be seen in the ambient light as they move to foraging grounds. They are relatively slow and erratic in flight, often fluttering and flitting along watercourses or over pastures and woodlands much like large moths.

They can catch prey at a rate of one insect every two seconds, increasing body mass as much as 25 percent in just thirty minutes. Typically, the di

==================================================
PASSAGE 277
guest cabin and another in the back of the main parking lot. The parking lot bat house is home to a colony of Brazilian Free-tailed Bats. However, repeated disturbance of this roost could lead to its abandonment, so please respect their home.

## **Friends in the Night Corkscrew’s Bats**

## **Big Brown Bat**

## _Eptesicus fuscus_

Big Brown Bats are found throughout North America from Canada to southern Mexico.

Normally  forest dwellers, they do not hesitate to utilize  attics and crevices in buildings, caves, and rocks for daytime retreats. Favorite roosts are under the  loose bark of dead trees and in cavities of trees.

Big Brown Bats are just that … big (13-16 inch wingspan) with brown, long fur ranging in color from dark to golden brown. Their undersides are a lighter shade. They have dark brown, almost black ears. Their teeth are impressive because these beneficial bats eat a variety of hard-bodied insects.

The Big Brown Bat is largely crepuscular, becoming active at j

In [109]:

query = """Which bat colony occupies Corkscrew's parking-lot
bat house, and how does the profile describe Florida's
smallest bat?"""

query_embedding = model.encode(
    [query],
    convert_to_numpy=True
).astype("float32")

distances, indices = passage_index.search(query_embedding, 5)

print("Question:", query)

for rank, idx in enumerate(indices[0], start=1):
    print(f"\n--- Retrieved Result {rank} | Passage {idx} ---")
    print(passages[idx][:1500])

Question: Which bat colony occupies Corkscrew's parking-lot
bat house, and how does the profile describe Florida's
smallest bat?

--- Retrieved Result 1 | Passage 276 ---
nguinivores.

These flying mammals are the best natural insect-control around.

People are slowly beginning to understand and appreciate these wonderful creatures, but no bats in Florida are completely safe or protected.

cult, but new technologies are helping us better understand them. However, there still isn’t much information about Florida populations. Education, habitat preservation, and more research are all keys to ensuring the continuation of these beneficial animals.

Bats that use trees and foliage are losing ground to development, and bats that move into buildings are susceptible

%IMAGE_DESCRIPTION: A pixelated image of a person wearing a white shirt with their hands raised near their head against a black background.%

At Corkscrew, two bat houses are in place: one by the guest cabin and another in the back of the main parking lot. The parking lot bat house is home to a colony of Brazilian Free-tailed Bats. However, repeated disturbance of this roost could lead to its

--- Retrieved Result 2 | Passage 300 ---
ortion of Florida on both the east and west coasts. Currently, there is no evidence of their existence in the Keys.

These bats can be found in urban and forested areas where they may use buildings, barrel tile roofs, tree cavities, and rock crevices for roosting. One colony is currently living in a bat house in North Fort Myers. They seem to prefer smaller colonies of 8-12 bats. Little is known about the social behavior of these bats.

Florida Bonneted Bats are the largest bats in Florida with wingspans of 20 inches. They weigh between 34 and 47 grams. Their fur coloration varies.

Dorsally, it can be dark gray, brownish gray, to cinnamon brown and lighter gray underneath. The fur is bicolored, being darker towards the tip. Its tail extends beyond the membrane. Their ears join together at the midline of their head and are broad and large with a slant forward over the eyes.

of 30 or more feet, above and along treetops and over open areas.

Again because of its rarity, very little

--- Retrieved Result 3 | Passage 299 ---
idsized bats with wingspans of about 12 inches. They have short grayish brown to dark brown fur. Their tails are free with a membrane that comes only to the middle of their tails. There are vertical wrinkles in their upper lips, and

This affinity for stable, manmade structures makes them the most likely candidates for bat house use. Their

All of the bats found at Corkscrew eat insects, and just one bat can consume up to 3,000 insects in a single night. They are our greatest natural insect control.

## **Florida Bonnetted Bat**

## _**Eumops floridanus**_

Originally, Florida Bonneted Bats were a subspecies of Wagner’s Mastiff Bat, but in 2004, taxonomic research concluded that the Florida population was in fact a separate species.

This rare creature is found only in the southern portion of Florida on both the east and west coasts. Currently, there is no evidence of their existence in the Keys.

These bats can be found in urban and forested areas where they may use buildings,

--- Retrieved Result 4 | Passage 291 ---
in its roost habitat of dead palm fronds. The fur extends down the body to Merlin D. Tuttle Bat Conservation International cover about half of its tail membrane. Its ears are relatively large and pointed.

In Florida, these bats inMerlin D. Tuttle habit hardwood and pine forests near permanent water but are also found in palm groves. They roost yearround in Spanish moss or beneath the dead, fan-shaped fronds of palms.

Although it  is solitary, small groups may roost  together in the skirts of old fronds of cabbage palms.

At four to five inches in length and with a wingspan of 14-16 inches, the Northern Yellow Bat is the second largest bat in Florida after the Mastiff Bat.

This species forages at night at heights of 15 - 20 feet over meadows, golf courses, marshes, and above the treetops along lake and forest edges. Its diet consists entirely of insects, mostly flies, dragonflies and damselflies,

There are no reliable longevity records for this species, but the fact that they

--- Retrieved Result 5 | Passage 281 ---
life-span of 19 years. Known enemies include barn owls, horned owls, and rat snakes.

In Florida, the Big Brown Bat doesn’t have a large population, so entire colonies could be wiped out with a single improper eradication. Education is one key to maintaining this valuable and beautiful bat.

During autumn and winter, Big

%IMAGE_DESCRIPTION: A close-up photograph of a bat clinging to a rocky surface, possibly a cave wall, with its wings spread and facing the camera.%

%IMAGE_DESCRIPTION: A pixelated image of a person in a white outfit with their arms raised, set against a black background.%

up to 10 years in the wild.

purely nocturnal, only foraging when it is completely dark. While their diet is mostly moths, they will eat other softer bodied insects such as mosquitoes. They are the only Florida bats to use gleaning (taking insects directly off of a surface) as a primary foraging technique. But they are capable of grabbing a meal “on the wing.” They are extremely maneuverable fl

In [110]:

query = """Which bat colony occupies Corkscrew's parking-lot
bat house, and how does the profile describe Florida's
smallest bat?"""

# Find passages using relevant keywords
keywords = ["parking lot bat house", "Eastern Pipistrelles"]

matched_passages = []

for i, passage in enumerate(passages):
    text = passage.lower()

    if (
        "parking lot bat house" in text
        or "eastern pipistrelles is florida's smallest bat" in text
        or "eastern pipistrelles is florida’s smallest bat" in text
    ):
        matched_passages.append((i, passage))

print("Matching passages found:", len(matched_passages))

for i, passage in matched_passages:
    print(f"\n--- Passage {i} ---")
    print(passage[:1200])

Matching passages found: 3

--- Passage 276 ---
nguinivores.

These flying mammals are the best natural insect-control around.

People are slowly beginning to understand and appreciate these wonderful creatures, but no bats in Florida are completely safe or protected.

cult, but new technologies are helping us better understand them. However, there still isn’t much information about Florida populations. Education, habitat preservation, and more research are all keys to ensuring the continuation of these beneficial animals.

Bats that use trees and foliage are losing ground to development, and bats that move into buildings are susceptible

%IMAGE_DESCRIPTION: A pixelated image of a person wearing a white shirt with their hands raised near their head against a black background.%

At Corkscrew, two bat houses are in place: one by the guest cabin and another in the back of the main parking lot. The parking lot bat house is home to a colony of Brazilian Free-tailed Bats. However, repeated disturbance of this roost could lead to its

--- Passage 277 ---
guest cabin and another in the back of the main parking lot. The parking lot bat house is home to a colony of Brazilian Free-tailed Bats. However, repeated disturbance of this roost could lead to its abandonment, so please respect their home.

## **Friends in the Night Corkscrew’s Bats**

## **Big Brown Bat**

## _Eptesicus fuscus_

Big Brown Bats are found throughout North America from Canada to southern Mexico.

Normally  forest dwellers, they do not hesitate to utilize  attics and crevices in buildings, caves, and rocks for daytime retreats. Favorite roosts are under the  loose bark of dead trees and in cavities of trees.

Big Brown Bats are just that … big (13-16 inch wingspan) with brown, long fur ranging in color from dark to golden brown. Their undersides are a lighter shade. They have dark brown, almost black ears. Their teeth are impressive because these beneficial bats eat a variety of hard-bodied insects.

The Big Brown Bat is largely crepuscular, becoming active at j

--- Passage 283 ---
ee months. They can live

Biologists age bats by looking at the finger bones in the outstretched wings over a bright light. Juvenile bats’ bones have clear spaces between the joints; adult bats have ossified joints.

## **Friends in the Night Corkscrew’s Bats**

## **Eastern Pipistrelles**

## _Pipistrellus sublavus_

Eastern Pipistrelles is Florida’s smallest bat, weighing in at a mere 1/4 ounce. The body is less than two inches long, with an eight to ten inch wingspan. They are solitary except at mating and in small nursery groups.

Eastern Pipistrelles are some of the earliest bats to emerge in the evening and are often be seen in the ambient light as they move to foraging grounds. They are relatively slow and erratic in flight, often fluttering and flitting along watercourses or over pastures and woodlands much like large moths.

They can catch prey at a rate of one insect every two seconds, increasing body mass as much as 25 percent in just thirty minutes. Typically, the di

In [111]:

context_passages = []

for i, passage in enumerate(passages):
    text = passage.lower()

    if (
        "parking lot bat house" in text
        or "eastern pipistrelles is florida" in text
    ):
        context_passages.append((i, passage))

context = "\n\n".join(
    f"Passage {i}:\n{passage}"
    for i, passage in context_passages
)

print("Passages included:", len(context_passages))
print(context[:5000])

Passages included: 3
Passage 276:
nguinivores.

These flying mammals are the best natural insect-control around.

People are slowly beginning to understand and appreciate these wonderful creatures, but no bats in Florida are completely safe or protected.

cult, but new technologies are helping us better understand them. However, there still isn’t much information about Florida populations. Education, habitat preservation, and more research are all keys to ensuring the continuation of these beneficial animals.

Bats that use trees and foliage are losing ground to development, and bats that move into buildings are susceptible

%IMAGE_DESCRIPTION: A pixelated image of a person wearing a white shirt with their hands raised near their head against a black background.%

At Corkscrew, two bat houses are in place: one by the guest cabin and another in the back of the main parking lot. The parking lot bat house is home to a colony of Brazilian Free-tailed Bats. However, repeated disturbance of this roost could lead to its

Passage 277:
guest cabin and another in the back of the main parking lot. The parking lot bat house is home to a colony of Brazilian Free-tailed Bats. However, repeated disturbance of this roost could lead to its abandonment, so please respect their home.

## **Friends in the Night Corkscrew’s Bats**

## **Big Brown Bat**

## _Eptesicus fuscus_

Big Brown Bats are found throughout North America from Canada to southern Mexico.

Normally  forest dwellers, they do not hesitate to utilize  attics and crevices in buildings, caves, and rocks for daytime retreats. Favorite roosts are under the  loose bark of dead trees and in cavities of trees.

Big Brown Bats are just that … big (13-16 inch wingspan) with brown, long fur ranging in color from dark to golden brown. Their undersides are a lighter shade. They have dark brown, almost black ears. Their teeth are impressive because these beneficial bats eat a variety of hard-bodied insects.

The Big Brown Bat is largely crepuscular, becoming active at j

Passage 283:
ee months. They can live

Biologists age bats by looking at the finger bones in the outstretched wings over a bright light. Juvenile bats’ bones have clear spaces between the joints; adult bats have ossified joints.

## **Friends in the Night Corkscrew’s Bats**

## **Eastern Pipistrelles**

## _Pipistrellus sublavus_

Eastern Pipistrelles is Florida’s smallest bat, weighing in at a mere 1/4 ounce. The body is less than two inches long, with an eight to ten inch wingspan. They are solitary except at mating and in small nursery groups.

Eastern Pipistrelles are some of the earliest bats to emerge in the evening and are often be seen in the ambient light as they move to foraging grounds. They are relatively slow and erratic in flight, often fluttering and flitting along watercourses or over pastures and woodlands much like large moths.

They can catch prey at a rate of one insect every two seconds, increasing body mass as much as 25 percent in just thirty minutes. Typically, the di

In [112]:

selected_ids = [276, 277, 283]

context = "\n\n".join(
    f"Passage {i}:\n{passages[i]}"
    for i in selected_ids
)

print(context)

Passage 276:
nguinivores.

These flying mammals are the best natural insect-control around.

People are slowly beginning to understand and appreciate these wonderful creatures, but no bats in Florida are completely safe or protected.

cult, but new technologies are helping us better understand them. However, there still isn’t much information about Florida populations. Education, habitat preservation, and more research are all keys to ensuring the continuation of these beneficial animals.

Bats that use trees and foliage are losing ground to development, and bats that move into buildings are susceptible

%IMAGE_DESCRIPTION: A pixelated image of a person wearing a white shirt with their hands raised near their head against a black background.%

At Corkscrew, two bat houses are in place: one by the guest cabin and another in the back of the main parking lot. The parking lot bat house is home to a colony of Brazilian Free-tailed Bats. However, repeated disturbance of this roost could lead to its

Passage 277:
guest cabin and another in the back of the main parking lot. The parking lot bat house is home to a colony of Brazilian Free-tailed Bats. However, repeated disturbance of this roost could lead to its abandonment, so please respect their home.

## **Friends in the Night Corkscrew’s Bats**

## **Big Brown Bat**

## _Eptesicus fuscus_

Big Brown Bats are found throughout North America from Canada to southern Mexico.

Normally  forest dwellers, they do not hesitate to utilize  attics and crevices in buildings, caves, and rocks for daytime retreats. Favorite roosts are under the  loose bark of dead trees and in cavities of trees.

Big Brown Bats are just that … big (13-16 inch wingspan) with brown, long fur ranging in color from dark to golden brown. Their undersides are a lighter shade. They have dark brown, almost black ears. Their teeth are impressive because these beneficial bats eat a variety of hard-bodied insects.

The Big Brown Bat is largely crepuscular, becoming active at j

Passage 283:
ee months. They can live

Biologists age bats by looking at the finger bones in the outstretched wings over a bright light. Juvenile bats’ bones have clear spaces between the joints; adult bats have ossified joints.

## **Friends in the Night Corkscrew’s Bats**

## **Eastern Pipistrelles**

## _Pipistrellus sublavus_

Eastern Pipistrelles is Florida’s smallest bat, weighing in at a mere 1/4 ounce. The body is less than two inches long, with an eight to ten inch wingspan. They are solitary except at mating and in small nursery groups.

Eastern Pipistrelles are some of the earliest bats to emerge in the evening and are often be seen in the ambient light as they move to foraging grounds. They are relatively slow and erratic in flight, often fluttering and flitting along watercourses or over pastures and woodlands much like large moths.

They can catch prey at a rate of one insect every two seconds, increasing body mass as much as 25 percent in just thirty minutes. Typically, the di

In [113]:

print("Eastern Pipistrelle description:")
print(passages[283][0:1500])

Eastern Pipistrelle description:
ee months. They can live

Biologists age bats by looking at the finger bones in the outstretched wings over a bright light. Juvenile bats’ bones have clear spaces between the joints; adult bats have ossified joints.

## **Friends in the Night Corkscrew’s Bats**

## **Eastern Pipistrelles**

## _Pipistrellus sublavus_

Eastern Pipistrelles is Florida’s smallest bat, weighing in at a mere 1/4 ounce. The body is less than two inches long, with an eight to ten inch wingspan. They are solitary except at mating and in small nursery groups.

Eastern Pipistrelles are some of the earliest bats to emerge in the evening and are often be seen in the ambient light as they move to foraging grounds. They are relatively slow and erratic in flight, often fluttering and flitting along watercourses or over pastures and woodlands much like large moths.

They can catch prey at a rate of one insect every two seconds, increasing body mass as much as 25 percent in just thirty minutes. Typically, the di

In [114]:

question = """Which bat colony occupies Corkscrew's parking-lot
bat house, and how does the profile describe Florida's
smallest bat?"""

prompt = f"""
Answer the question using only the context below.
If the context does not contain an answer, say so.
Do not add unsupported facts.

Context:
{context}

Question:
{question}

Answer:
"""

print(prompt[:5000])

Answer the question using only the context below.
If the context does not contain an answer, say so.
Do not add unsupported facts.

Context:
Passage 276:
nguinivores.

These flying mammals are the best natural insect-control around.

People are slowly beginning to understand and appreciate these wonderful creatures, but no bats in Florida are completely safe or protected.

cult, but new technologies are helping us better understand them. However, there still isn’t much information about Florida populations. Education, habitat preservation, and more research are all keys to ensuring the continuation of these beneficial animals.

Bats that use trees and foliage are losing ground to development, and bats that move into buildings are susceptible

%IMAGE_DESCRIPTION: A pixelated image of a person wearing a white shirt with their hands raised near their head against a black background.%

At Corkscrew, two bat houses are in place: one by the guest cabin and another in the back of the main parking lot. The parking lot bat house is home to a colony of Brazilian Free-tailed Bats. However, repeated disturbance of this roost could lead to its

Passage 277:
guest cabin and another in the back of the main parking lot. The parking lot bat house is home to a colony of Brazilian Free-tailed Bats. However, repeated disturbance of this roost could lead to its abandonment, so please respect their home.

## **Friends in the Night Corkscrew’s Bats**

## **Big Brown Bat**

## _Eptesicus fuscus_

Big Brown Bats are found throughout North America from Canada to southern Mexico.

Normally  forest dwellers, they do not hesitate to utilize  attics and crevices in buildings, caves, and rocks for daytime retreats. Favorite roosts are under the  loose bark of dead trees and in cavities of trees.

Big Brown Bats are just that … big (13-16 inch wingspan) with brown, long fur ranging in color from dark to golden brown. Their undersides are a lighter shade. They have dark brown, almost black ears. Their teeth are impressive because these beneficial bats eat a variety of hard-bodied insects.

The Big Brown Bat is largely crepuscular, becoming active at j

Passage 283:
ee months. They can live

Biologists age bats by looking at the finger bones in the outstretched wings over a bright light. Juvenile bats’ bones have clear spaces between the joints; adult bats have ossified joints.

## **Friends in the Night Corkscrew’s Bats**

## **Eastern Pipistrelles**

## _Pipistrellus sublavus_

Eastern Pipistrelles is Florida’s smallest bat, weighing in at a mere 1/4 ounce. The body is less than two inches long, with an eight to ten inch wingspan. They are solitary except at mating and in small nursery groups.

Eastern Pipistrelles are some of the earliest bats to emerge in the evening and are often be seen in the ambient light as they move to foraging grounds. They are relatively slow and erratic in flight, often fluttering and flitting along watercourses or over pastures and woodlands much like large moths.

They can catch prey at a rate of one insect every two seconds, increasing body mass as much as 25 percent in just thirty minutes. Typically, the di

Question:
Which bat colony occupies Corkscrew's parking-lot
bat house, and how does the profile describe Florida's
smallest bat?

Answer:

In [115]:

print("Brazilian Free-tailed Bats found:",
      "Brazilian Free-tailed Bats" in context)

print("Eastern Pipistrelle found:",
      "Eastern Pipistrelle" in context)

print("\nEastern Pipistrelle section:")
for line in context.splitlines():
    if "smallest bat" in line.lower() or "ounce" in line.lower():
        print(line)

Brazilian Free-tailed Bats found: True
Eastern Pipistrelle found: True

Eastern Pipistrelle section:
Eastern Pipistrelles is Florida’s smallest bat, weighing in at a mere 1/4 ounce. The body is less than two inches long, with an eight to ten inch wingspan. They are solitary except at mating and in small nursery groups.

In [118]:

try:
    models = client.models.list()

    print("Models available to your Groq client:\n")
    for item in models.data:
        print(item.id)

except Exception as e:
    print("Error type:", type(e).__name__)
    print("Error details:", str(e))

Models available to your Groq client:

qwen/qwen3.8-27b
canopylabs/orpheus-v1-english
allam-2-7b
whisper-large-v3-turbo
openai/gpt-oss-120b
meta-llama/llama-prompt-guard-2-22m
openai/gpt-oss-20b
whisper-large-v3
canopylabs/orpheus-arabic-saudi
openai/gpt-oss-safeguard-20b
meta-llama/llama-prompt-guard-2-86m

In [119]:

response = client.chat.completions.create(
    model="openai/gpt-oss-120b",
    messages=[
        {
            "role": "system",
            "content": "Answer using only the provided context. Do not invent facts."
        },
        {
            "role": "user",
            "content": prompt
        }
    ],
    temperature=0
)

print(response.choices[0].message.content)

The parking‑lot bat house at Corkscrew is home to a colony of **Brazilian Free‑tailed Bats**.

Florida’s smallest bat, described in the profile, is the **Eastern Pipistrelle**. It is a very tiny bat—about **¼ ounce in weight**, **under two inches long** with an **8‑ to 10‑inch wingspan**. It is usually solitary (except when mating or in small nursery groups), is one of the earliest bats to emerge at dusk, and flies slowly and erratically, fluttering like a large moth.

In [120]:

!pip install -q pypdf

In [124]:

import os

pdf_files = [
    file for file in os.listdir("/content")
    if file.lower().endswith(".pdf")
]

print("PDF files found:")
for file in pdf_files:
    print(file)

PDF files found:
RAG_COLLAGE_DOCUMENTS.pdf

In [125]:

from pypdf import PdfReader

pdf_path = "/content/RAG_COLLAGE_DOCUMENTS.pdf"

reader = PdfReader(pdf_path)

print("Total pages:", len(reader.pages))

pdf_text = ""

for page in reader.pages:
    text = page.extract_text()
    if text:
        pdf_text += text + "\n"

print("\nExtracted text length:", len(pdf_text))
print("\nFirst 3000 characters:\n")
print(pdf_text[:3000])

Total pages: 41

Extracted text length: 106960

First 3000 characters:

 Visvesvaraya Technological University, Belagavi











VTU Regulations Governing the UG Programmes
B.E. and B.Tech. - 2025















                                                                2025
22052026
           Visvesvaraya Technological University, Belagavi
          VTU Regulations Governing the UG Programmes B.E. and B.Tech. – 2025
- 2 -

Contents

VTU Regulations Governing the UG Programmes B.E. and B.Tech. - 2025
Preamble to Regulations
Definition of Key Words
25OB1.0 Title, Duration and Academic Calandar of the Programme
25OB1.1 Programme of Study
25OB1.2 Duration of the B.E./ B.Tech. programme
25OB1.3 Academic Calendar
25OB2.0 Academic Eligibility for Admission
25OB2.1 Admission to First Year of the Programme
25OB2.2 Admission to the Second Year of the Programme (Lateral Entry)
25OB2.3 Qualification Earned from Foreign Countries
25OB2.4 Additional Requirements of Lateral Entry Candidates
25OB3.0 Maximum Duration of B.E./B.Tech. Programme and Time Limit for
                  Completion
25OB4.0 Prescribed Credits for the B.E./B.Tech. Programme
25OB5.0 Medium of Instruction of the Programme
25OB6.0 Curriculum Framework and Academic Processes
25OB6.1 Academic Curriculum
25OB 6.2 Outcome-Based Education (OBE)
25OB6.3 Choice Based Credit System (CBCS)
25OB7.0 Credits According to National Credit Framework (NCrF)
25OB8.0 Semesters, Semester End Examinations and Examination Timetable
25OB8.1 Semesters – Odd, Even, and Summer
25OB8.2 Semester end Examinations (SEE)
25OB8.3 Semester End Examinations and Timetable
25OB9.0 Definition of First Attempt to SEE
25OB10.0 Attendance Requirement
25OB11.0Course Assessment and Evaluation Procedure and Passing Standards
25OB11.1 Continuous Internal Evaluation and prescribed Minimum CIE Marks to
Appear for SEE, or to secure PP status in Non-Mandatory Courses
25OB11.2Continuous Internal Evaluation Review Committee
25OB11.2.1 Members of the Committee
25OB11.2.2 Activities of the Committee
25OB11.2.3 Accountability and Submission of Moderation Reports
25OB12.0 Minimum Passing marks for the Award of Pass grade in a Course
25OB13.0 Minimum CGPA for the Award of Degree
25OB14.0 Course-Wise Assessment and Evaluation
25OB15.0 Course Registration under Mentor Guidance
25OB15.0.1 Course Registration Procedure
25OB16.0 Substitution of Professional / Open Elective Courses upon Repeated Failure
22052026
           Visvesvaraya Technological University, Belagavi
          VTU Regulations Governing the UG Programmes B.E. and B.Tech. – 2025
- 3 -

25OB17.0 Maintenance of CIE Activity Records
25OB18.0 Rejection of CIE Marks and/or SEE Results
25OB19.0 Unfair Means and Disciplinary Action
25OB20.0 Ineligibility, Discontinuation, and Hostel Vacating
25OB21.0 Readmission
25OB22.0 Award of Grades
25OB23.0 Additional Letter Grades and Their Applicability
25OB24.0 Vertical Progression

In [126]:

chunk_size = 1000
overlap = 200

chunks = []

start = 0

while start < len(pdf_text):
    end = start + chunk_size
    chunk = pdf_text[start:end]

    if chunk.strip():
        chunks.append(chunk)

    start += chunk_size - overlap

print("Total chunks created:", len(chunks))
print("\nFirst chunk:\n")
print(chunks[0])

Total chunks created: 134

First chunk:

 Visvesvaraya Technological University, Belagavi











VTU Regulations Governing the UG Programmes
B.E. and B.Tech. - 2025















                                                                2025
22052026
           Visvesvaraya Technological University, Belagavi
          VTU Regulations Governing the UG Programmes B.E. and B.Tech. – 2025
- 2 -

Contents

VTU Regulations Governing the UG Programmes B.E. and B.Tech. - 2025
Preamble to Regulations
Definition of Key Words
25OB1.0 Title, Duration and Academic Calandar of the Programme
25OB1.1 Programme of Study
25OB1.2 Duration of the B.E./ B.Tech. programme
25OB1.3 Academic Calendar
25OB2.0 Academic Eligibility for Admission
25OB2.1 Admission to First Year of the Programme
25OB2.2 Admission to the Second Year of the Programme (Lateral Entry)
25OB2.3 Qualification Earned from Foreign Countries
25OB2.4 Additional Requirements of Lateral Entry Candidates
25OB3.0 Max

In [127]:

from sentence_transformers import SentenceTransformer

embedding_model_vtu = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

chunk_embeddings = embedding_model_vtu.encode(
    chunks,
    convert_to_numpy=True,
    show_progress_bar=True
)

print("Number of chunks:", len(chunks))
print("Embedding shape:", chunk_embeddings.shape)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Batches:   0%|          | 0/5 [00:00<?, ?it/s]

Number of chunks: 134
Embedding shape: (134, 384)

In [128]:

import faiss
import numpy as np

chunk_embeddings = np.asarray(
    chunk_embeddings,
    dtype="float32"
)

vtu_index = faiss.IndexFlatL2(
    chunk_embeddings.shape[1]
)

vtu_index.add(chunk_embeddings)

print("VTU index created successfully!")
print("Total vectors in index:", vtu_index.ntotal)

VTU index created successfully!
Total vectors in index: 134

In [129]:

question = "What is the maximum duration allowed to complete the B.E. programme?"

question_embedding = embedding_model_vtu.encode(
    [question],
    convert_to_numpy=True
).astype("float32")

distances, indices = vtu_index.search(
    question_embedding,
    3
)

for rank, idx in enumerate(indices[0], start=1):
    print(f"\n--- Result {rank} | Chunk {idx} ---")
    print(chunks[idx][:1000])

--- Result 1 | Chunk 34 ---
s Governing the UG Programmes B.E. and B.Tech. – 2025
- 13 -

In the event of any dispute regarding the equivalence of qualifications obtained from
foreign countries, the decision of the University in this regard shall be final and binding
on all concerned.
25OB2.4 Additional Requirements of Lateral Entry Candidates
All Diploma and B.Sc. degree holders seeking admission through lateral entry shall be
required to successfully complete any additional courses specified by the University
before the completion of the degree programme.

25OB3.0 Maximum Duration of B.E./B.Tech. Programme and Time Limit for
Completion
(a)The duration of the Under Graduate Degree programme, namely B.E./B. Tech., shall be
four (4) calendar years for students admitted to the first year of the programme with an
educational qualification of PUC/12 th standard or equivalent. Such students shall
complete the programme within eight (8) calendar years from the year of first admission,
failing

--- Result 2 | Chunk 31 ---
ech. programme
The duration of the B.E./ B.Tech. programme for shall be four (04) academic years ,
organised in to eight (08) semesters with four (04) summer semesters in the case of
candidates admitted to the first year of the programme and three (03) academic years,
organised in six (06) semesters with three (03) summer semesters in the case of lateral
entry candidates.
25OB1.3 Academic Calendar
The annual academic calendar of events for the programme of study, as approved by the
University, shall be notified before the commencement of each academic year. It shall be
mandatory for faculty members/students to strictly adhere to the Academic Calendar for
the completion of academic activities. The Academic Calendar shall be notified on the
University website, with copies of the notification communicated to all the concerned
colleges.
25OB2.0  Academic Eligibility for Admission
The rules specified in the following clauses shall be followed for admission to B.E./
B.Tec

--- Result 3 | Chunk 35 ---
rogramme with an
educational qualification of PUC/12 th standard or equivalent. Such students shall
complete the programme within eight (8) calendar years from the year of first admission,
failing which they shall not be eligible for the award of a degree.
(b)The duration of the Under Graduate Degree programme, namely B.E./B. Tech., shall be
three (3) c alendar years for students admitted directly to the second year with an
educational qualification of Diploma in engineering or B.Sc. They shall complete the
programme within six (6) c alendar years from the year of first admission, failing which
they shall not be eligible for the award of the degree.

25OB4.0 Prescribed Credits for the B.E./B.Tech. Programme
All courses prescribed by the University, except the non-credit Mandatory courses, shall
carry credits (refer to serial number 30 of Definitions ) and shall be considered as a head of
passing for the purpose of vertical progression [Refer to 25OB24]. The credits p

In [130]:

question = "What is the maximum duration allowed to complete the B.E. programme?"

context = "\n\n".join(
    chunks[idx] for idx in indices[0]
)

prompt = f"""
Answer the question using only the VTU regulations
provided in the context.

If the information is missing, say so.
Keep the answer simple and mention the relevant
regulation number when available.

Context:
{context}

Question:
{question}
"""

response = client.chat.completions.create(
    model="openai/gpt-oss-120b",
    messages=[
        {
            "role": "system",
            "content": "Answer accurately using only the supplied context."
        },
        {
            "role": "user",
            "content": prompt
        }
    ],
    temperature=0
)

print("Question:", question)
print("\nAnswer:")
print(response.choices[0].message.content)

Question: What is the maximum duration allowed to complete the B.E. programme?

Answer:
**Maximum time to finish the B.E. programme**

- **Regular first‑year entrants:** must complete the degree **within 8 calendar years** of their first admission.
  *Regulation 25OB3.0 (a)*

- **Lateral‑entry (second‑year) entrants:** must complete the degree **within 6 calendar years** of their first admission.
  *Regulation 25OB2.0 (b)*

Thus, the longest allowable period is **8 years** (for students who start in the first year).

In [131]:

question = "How many semesters are there in the B.E. programme?"

question_embedding = embedding_model_vtu.encode(
    [question],
    convert_to_numpy=True
).astype("float32")

distances, indices = vtu_index.search(
    question_embedding, 3
)

context = "\n\n".join(
    chunks[idx] for idx in indices[0]
)

prompt = f"""
Answer the question using only the VTU regulations below.
If the answer is missing, say so.

Context:
{context}

Question: {question}
"""

response = client.chat.completions.create(
    model="openai/gpt-oss-120b",
    messages=[
        {
            "role": "system",
            "content": "Answer accurately using only the supplied context."
        },
        {"role": "user", "content": prompt}
    ],
    temperature=0
)

print("Question:", question)
print("\nAnswer:", response.choices[0].message.content)
print("\nRetrieved context:\n", context[:1500])

Question: How many semesters are there in the B.E. programme?

Answer: The regular B.E. programme is organised into **eight (08) semesters** (plus four summer semesters). 【VTU regulation 25OB2.0 / 25OB1.2】.

Retrieved context:
 ech. programme
The duration of the B.E./ B.Tech. programme for shall be four (04) academic years ,
organised in to eight (08) semesters with four (04) summer semesters in the case of
candidates admitted to the first year of the programme and three (03) academic years,
organised in six (06) semesters with three (03) summer semesters in the case of lateral
entry candidates.
25OB1.3 Academic Calendar
The annual academic calendar of events for the programme of study, as approved by the
University, shall be notified before the commencement of each academic year. It shall be
mandatory for faculty members/students to strictly adhere to the Academic Calendar for
the completion of academic activities. The Academic Calendar shall be notified on the
University website, with copies of the notification communicated to all the concerned
colleges.
25OB2.0  Academic Eligibility for Admission
The rules specified in the following clauses shall be followed for admission to B.E./
B.Tec

 B.Tech. – 2025
- 11 -

issued by the University to registered students after each semester end examination ,
indicating course code, course title, credits, letter grades, SGPA of the semester, and
CGPA.


22052026
           Visvesvaraya Technological University, Belagavi
          VTU Regulations Governing the UG Programmes B.E. and B.Tech. – 2025
- 12 -

VTU Regulations Governing the UG Programmes
B.E. and B.Tech. - 2025
25OB1.0 Title, Duration and Academic Calandar of

In [132]:

question = "What is the hostel fee for CSE students at Bangalore Technological Institute?"

question_embedding = embedding_model_vtu.encode(
    [question],
    convert_to_numpy=True
).astype("float32")

distances, indices = vtu_index.search(
    question_embedding, 3
)

context = "\n\n".join(
    chunks[idx] for idx in indices[0]
)

prompt = f"""
Answer using only the supplied VTU regulations.
If the document does not contain the answer, clearly
say that the information is not available.
Do not guess or invent fees.

Context:
{context}

Question:
{question}
"""

response = client.chat.completions.create(
    model="openai/gpt-oss-120b",
    messages=[
        {
            "role": "system",
            "content": "Use only the supplied context. Never invent missing information."
        },
        {"role": "user", "content": prompt}
    ],
    temperature=0
)

print("Question:", question)
print("\nAnswer:", response.choices[0].message.content)

Question: What is the hostel fee for CSE students at Bangalore Technological Institute?

Answer: The provided VTU regulations do not contain any information about hostel fees for CSE students at Bangalore Technological Institute. Therefore, the requested information is not available in the supplied document.